import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

// Execute the actual packaged UI logic with an inert DOM. No browser, tiles,
// location permission or live service is contacted by these lifecycle tests.
class Element{
  constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.className='';this.textContent='';this.clientWidth=760;this.clientHeight=320;this.classList={add:()=>{},remove:()=>{},toggle:()=>{}};}
  append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(){}addEventListener(){}focus(){}
}
function harness(){const nodes=new Map(),actions=[],navigation=[];const get=id=>{if(!nodes.has(id))nodes.set(id,new Element('div'));return nodes.get(id);};const context=vm.createContext({console,Date,Math,Number,JSON,Map,Object,Array,String,confirm:()=>true,setInterval:()=>0,document:{getElementById:get,createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),querySelectorAll:()=>[]},window:{scrollTo:()=>{}},Rider:{action:raw=>actions.push(JSON.parse(raw)),navigate:()=>navigation.push('navigate'),start:()=>navigation.push('start'),stop:()=>navigation.push('stop'),sync:()=>{},privacy:()=>{},settings:()=>{},permissions:()=>{},pair:()=>{},unlink:()=>{},discard:()=>{}}});
 const html=readFileSync('android-driver/app/src/main/assets/rider.html','utf8');vm.runInContext(html.split('<script>')[1].split('</script>')[0],context);return {context,nodes,get,actions,navigation};}
const orderId='10000000-0000-4000-8000-000000000001',dispatchId='20000000-0000-4000-8000-000000000001';
function fixture(commands=[]){const order={id:orderId,title:'Synthetic parcel',status:'assigned',pickup:{name:'Test pickup',address:'Fixture'},destination:{name:'Test destination',address:'Fixture'},measuredKm:0};return {paired:true,recording:true,gpsEnabled:true,driver:'Synthetic rider',events:5,busy:false,commands,canStop:false,data:{assignment:{id:dispatchId,orderId,name:'Synthetic parcel',stops:[{id:'pickup',name:'Collect',address:'Fixture',lat:-1.28,lng:36.82,deliveredAt:null},{id:'delivery',name:'Drop',address:'Fixture',lat:-1.29,lng:36.83,deliveredAt:null}]},order,recentOrders:[order],payments:[],offers:[]}};}
function all(root){return [root,...root.children.flatMap(child=>all(child))];}
function load(h,state){h.context.fixture=state;vm.runInContext('applyState(fixture)',h.context);}
test('rider can finish an offline delivery after collection is queued, preserving order and dispatch identity',()=>{const h=harness();load(h,fixture([{payload:{action:'collected',orderId,operationId:'fixture'},error:''}]));const finish=all(h.get('homecontent')).find(e=>e.textContent==='✓ Finish delivery / ride');assert.ok(finish&&!finish.disabled);finish.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,orderId}]);});
test('an offline finish exposes one customer report with exact method and amount, without marking the server order paid',()=>{const h=harness(),s=fixture([{payload:{action:'delivered',dispatchId,orderId,operationId:'fixture'},error:''}]);load(h,s);vm.runInContext("go('trips')",h.context);const report=all(h.get('tripcontent')).find(e=>e.textContent==='Report cash / till payment');assert.ok(report);report.onclick();h.get('amount').value='8799.25';h.get('method').value='till';h.get('reference').value='Synthetic till reference';vm.runInContext('submitPayment({preventDefault(){}})',h.context);assert.deepEqual(h.actions,[{action:'payment',orderId,amount:8799.25,method:'till',reference:'Synthetic till reference'}]);assert.equal(s.data.order.status,'assigned');});
test('legacy multi-stop rider confirmation includes the exact next stop ID so crash retries cannot advance another stop',()=>{const h=harness(),s=fixture();delete s.data.assignment.orderId;s.data.assignment.stops.push({id:'third',name:'Final stop',address:'Fixture',lat:-1.3,lng:36.84,deliveredAt:null});load(h,s);const complete=all(h.get('homecontent')).find(e=>e.textContent==='✓ Confirm Collect');assert.ok(complete);complete.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,stopId:'pickup'}]);});
