import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

// Execute the actual packaged UI logic with an inert DOM. No browser, tiles,
// location permission or live service is contacted by these lifecycle tests.
class Element{
  constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.className='';this.textContent='';this.clientWidth=760;this.clientHeight=320;this.classList={add:()=>{},remove:()=>{},toggle:()=>{}};}
  append(...nodes){this.children.push(...nodes);}prepend(...nodes){this.children.unshift(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(){}addEventListener(){}focus(){}
}
function harness(){const nodes=new Map(),actions=[],navigation=[];let now=Date.now();class Clock extends Date{static now(){return now;}}const get=id=>{if(!nodes.has(id))nodes.set(id,new Element('div'));return nodes.get(id);};const context=vm.createContext({console,Date:Clock,Math,Number,JSON,Map,Object,Array,String,confirm:()=>true,setInterval:()=>0,document:{getElementById:get,createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),querySelectorAll:()=>[]},window:{scrollTo:()=>{}},Rider:{action:raw=>actions.push(JSON.parse(raw)),navigate:()=>navigation.push('navigate'),start:()=>navigation.push('start'),stop:()=>navigation.push('stop'),sync:()=>{},privacy:()=>{},settings:()=>{},permissions:()=>{},login:()=>{},logout:()=>{},unlink:()=>{},discard:()=>{},testAlert:()=>{},alertSettings:()=>{}}});
 const html=readFileSync('android-driver/app/src/main/assets/rider.html','utf8');vm.runInContext(html.split('<script>')[1].split('</script>')[0],context);return {context,nodes,get,actions,navigation,now:()=>now,advance:ms=>{now+=ms;vm.runInContext('tickOffers()',context);}};}
const orderId='10000000-0000-4000-8000-000000000001',dispatchId='20000000-0000-4000-8000-000000000001';
function fixture(commands=[]){const order={id:orderId,title:'Synthetic parcel',status:'assigned',pickup:{name:'Test pickup',address:'Fixture'},destination:{name:'Test destination',address:'Fixture'},measuredKm:0};return {paired:true,recording:true,gpsEnabled:true,driver:'Synthetic rider',events:5,busy:false,commands,canStop:false,data:{assignment:{id:dispatchId,orderId,name:'Synthetic parcel',stops:[{id:'pickup',name:'Collect',address:'Fixture',lat:-1.28,lng:36.82,deliveredAt:null},{id:'delivery',name:'Drop',address:'Fixture',lat:-1.29,lng:36.83,deliveredAt:null}]},order,recentOrders:[order],payments:[],offers:[]}};}
function all(root){return [root,...root.children.flatMap(child=>all(child))];}
function load(h,state){h.context.fixture=state;vm.runInContext('applyState(fixture)',h.context);}
test('rider can finish an offline delivery after collection is queued, preserving order and dispatch identity',()=>{const h=harness();load(h,fixture([{payload:{action:'collected',orderId,operationId:'fixture'},error:''}]));const finish=all(h.get('homecontent')).find(e=>e.textContent==='✓ Finish delivery / ride');assert.ok(finish&&!finish.disabled);finish.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,orderId}]);});
test('an offline finish exposes one customer report with exact method and amount, without marking the server order paid',()=>{const h=harness(),s=fixture([{payload:{action:'delivered',dispatchId,orderId,operationId:'fixture'},error:''}]);load(h,s);vm.runInContext("go('trips')",h.context);const report=all(h.get('tripcontent')).find(e=>e.textContent==='Report cash / till payment');assert.ok(report);report.onclick();h.get('amount').value='8799.25';h.get('method').value='till';h.get('reference').value='Synthetic till reference';vm.runInContext('submitPayment({preventDefault(){}})',h.context);assert.deepEqual(h.actions,[{action:'payment',orderId,amount:8799.25,method:'till',reference:'Synthetic till reference'}]);assert.equal(s.data.order.status,'assigned');});
test('legacy multi-stop rider confirmation includes the exact next stop ID so crash retries cannot advance another stop',()=>{const h=harness(),s=fixture();delete s.data.assignment.orderId;s.data.assignment.stops.push({id:'third',name:'Final stop',address:'Fixture',lat:-1.3,lng:36.84,deliveredAt:null});load(h,s);const complete=all(h.get('homecontent')).find(e=>e.textContent==='✓ Confirm Collect');assert.ok(complete);complete.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,stopId:'pickup'}]);});

function offer(h,remaining=30000){return {id:orderId,title:'Synthetic offered parcel',pickup:{name:'Collect here',address:'Fixture'},destination:{name:'Deliver here',address:'Fixture'},offerStartedAt:h.now()-30000+remaining,offerDeadline:h.now()+remaining};}
function free(h,offers=[]){return {...fixture(),canStop:true,data:{assignment:null,offers,serverTime:h.now(),receivedAt:h.now(),recentOrders:[],payments:[]}};}
test('an offer is visible and claimable from Account without changing the current tab',()=>{const h=harness();vm.runInContext("go('account')",h.context);load(h,free(h,[offer(h)]));const claim=all(h.get('deliveryalert')).find(e=>e.textContent==='Claim this delivery →');assert.ok(claim&&!claim.disabled);assert.equal(vm.runInContext('page',h.context),'account');claim.onclick();assert.deepEqual(h.actions,[{action:'accept',orderId}]);});
test('the claim line moves left to right using the office deadline, then expired controls disappear',()=>{const h=harness();load(h,free(h,[offer(h,22500)]));const progress=all(h.get('deliveryalert')).find(e=>e.className==='offertrack');assert.equal(progress.children[0].style.width,'25%');h.advance(23000);assert.equal(h.get('deliveryalert').style.display,'none');assert.equal(all(h.get('deliveryalert')).filter(e=>e.textContent==='Claim this delivery →').length,0);});
test('a busy rider hides even a stale offer and cannot invoke its old claim button',()=>{const h=harness(),o=offer(h);load(h,free(h,[o]));const old=all(h.get('deliveryalert')).find(e=>e.textContent==='Claim this delivery →');const s=fixture();s.data.offers=[o];load(h,s);old.onclick();vm.runInContext("go('offers')",h.context);assert.deepEqual(h.actions,[]);assert.ok(all(h.get('offercontent')).some(e=>e.textContent==='Finish your active delivery before accepting another.'));assert.equal(all(h.get('deliveryalert')).some(e=>e.textContent==='Claim this delivery →'),false);});
test('assigned rides remain prominent from every tab and keep a customer payment draft intact',()=>{const h=harness(),s=fixture();vm.runInContext("go('account')",h.context);load(h,s);assert.ok(all(h.get('deliveryalert')).some(e=>e.textContent==='ACTIVE DELIVERY'));h.context.order=s.data.order;vm.runInContext('openPay(order)',h.context);h.get('amount').value='1234.50';h.get('reference').value='Draft reference';load(h,s);assert.equal(h.get('amount').value,'1234.50');assert.equal(h.get('reference').value,'Draft reference');assert.equal(vm.runInContext('page',h.context),'account');});
test('off duty, disabled GPS and an old connection snapshot cannot expose claim controls',()=>{for(const changes of [{recording:false},{gpsEnabled:false},{old:true}]){const h=harness(),s=free(h,[offer(h)]);Object.assign(s,changes);if(changes.old)s.data.receivedAt-=16000;load(h,s);assert.equal(h.get('deliveryalert').style.display,'none');assert.equal(all(h.get('deliveryalert')).some(e=>e.textContent==='Claim this delivery →'),false);}});
test('offline confirmation of one legacy stop keeps the rest of the trip available',()=>{const h=harness(),s=fixture();delete s.data.assignment.orderId;s.commands=[{payload:{action:'delivered',dispatchId,stopId:'pickup'},error:''}];load(h,s);const next=all(h.get('homecontent')).find(e=>e.textContent==='✓ Confirm Drop');assert.ok(next&&!next.disabled);next.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,stopId:'delivery'}]);assert.equal(all(h.get('homecontent')).some(e=>e.textContent==='Delivery finished locally · waiting for office receipt'),false);});
test('a failed delivery update remains visible separately from a successful GPS upload',()=>{const h=harness(),s=fixture();s.error='';s.stateError='Delivery connection interrupted.';load(h,s);assert.equal(h.get('notice').textContent,s.stateError);assert.equal(h.get('notice').style.display,'block');assert.ok(all(h.get('deliveryalert')).some(e=>e.textContent==='ACTIVE DELIVERY'));});
