import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

// Execute the actual packaged UI logic with an inert DOM. No browser, tiles,
// location permission or live service is contacted by these lifecycle tests.
class Element{
  constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.attributes={};this.className='';this.textContent='';this.clientWidth=760;this.clientHeight=320;const classes=new Set();this.classList={add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle:(x,v)=>{if(v??!classes.has(x))classes.add(x);else classes.delete(x);}};}
  append(...nodes){this.children.push(...nodes);}prepend(...nodes){this.children.unshift(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(k,v){this.attributes[k]=v;}addEventListener(){}focus(){}
}
function harness(){const nodes=new Map(),actions=[],navigation=[],logins=[];let now=Date.now();class Clock extends Date{static now(){return now;}}const get=id=>{if(!nodes.has(id))nodes.set(id,new Element('div'));return nodes.get(id);};const context=vm.createContext({console,Date:Clock,Math,Number,JSON,Map,Object,Array,String,confirm:()=>true,setInterval:()=>0,document:{getElementById:get,createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),querySelectorAll:()=>[]},window:{scrollTo:()=>{}},Rider:{mapCredits:()=>{},cancelRoads:()=>navigation.push('cancelRoads'),updateApp:()=>navigation.push('updateApp'),checkUpdate:()=>navigation.push('checkUpdate'),history:(action,kind,id)=>navigation.push({history:action,kind,id}),countyMap:id=>navigation.push({county:id}),kenyaMap:()=>navigation.push('kenyaMap'),route:(dispatchId,stopId,force)=>navigation.push({dispatchId,stopId,force}),retryOtp:(id,otp)=>navigation.push({retryOtp:id,otp}),contactCustomer:()=>navigation.push('contactCustomer'),action:raw=>actions.push(JSON.parse(raw)),navigate:()=>navigation.push('navigate'),start:()=>navigation.push('start'),stop:()=>navigation.push('stop'),sync:()=>{},privacy:()=>{},settings:()=>{},permissions:()=>{},login:(username,password,agreed)=>logins.push({username,password,agreed}),logout:()=>{},unlink:()=>{},discard:()=>{},testAlert:()=>{},alertSettings:()=>{}}});
 const html=readFileSync('android-driver/app/src/main/assets/rider.html','utf8');vm.runInContext(html.split('<script>')[1].split('</script>')[0],context);return {context,nodes,get,actions,navigation,logins,now:()=>now,advance:ms=>{now+=ms;vm.runInContext('tickOffers()',context);}};}
const orderId='10000000-0000-4000-8000-000000000001',dispatchId='20000000-0000-4000-8000-000000000001';
function fixture(commands=[]){const order={id:orderId,title:'Synthetic parcel',status:'assigned',pickup:{name:'Test pickup',address:'Fixture'},destination:{name:'Test destination',address:'Fixture'},measuredKm:0};return {paired:true,recording:true,gpsEnabled:true,driver:'Synthetic rider',events:5,busy:false,commands,canStop:false,data:{assignment:{id:dispatchId,orderId,name:'Synthetic parcel',stops:[{id:'pickup',name:'Collect',address:'Fixture',lat:-1.28,lng:36.82,deliveredAt:null},{id:'delivery',name:'Drop',address:'Fixture',lat:-1.29,lng:36.83,deliveredAt:null}]},order,recentOrders:[order],payments:[],offers:[]}};}
function all(root){return [root,...root.children.flatMap(child=>all(child))];}
function load(h,state){h.context.fixture=state;vm.runInContext('applyState(fixture)',h.context);}
test('rider can finish an offline delivery after collection is queued, preserving order and dispatch identity',()=>{const h=harness();load(h,fixture([{payload:{action:'collected',orderId,operationId:'fixture'},error:''}]));const finish=all(h.get('homecontent')).find(e=>e.textContent==='✓ Finish delivery / ride');assert.ok(finish&&!finish.disabled);finish.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,orderId}]);});
test('an offline finish exposes one customer report with exact method and amount, without marking the server order paid',()=>{const h=harness(),s=fixture([{payload:{action:'delivered',dispatchId,orderId,operationId:'fixture'},error:''}]);load(h,s);vm.runInContext("go('trips')",h.context);const report=all(h.get('tripcontent')).find(e=>e.textContent==='Report cash / till payment');assert.ok(report);report.onclick();h.get('amount').value='8799.25';h.get('method').value='till';h.get('reference').value='Synthetic till reference';vm.runInContext('submitPayment({preventDefault(){}})',h.context);assert.deepEqual(h.actions,[{action:'payment',orderId,amount:8799.25,method:'till',reference:'Synthetic till reference'}]);assert.equal(s.data.order.status,'assigned');});
test('legacy multi-stop rider confirmation includes the exact next stop ID so crash retries cannot advance another stop',()=>{const h=harness(),s=fixture();delete s.data.assignment.orderId;s.data.assignment.stops.push({id:'third',name:'Final stop',address:'Fixture',lat:-1.3,lng:36.84,deliveredAt:null});load(h,s);const complete=all(h.get('homecontent')).find(e=>e.textContent==='✓ Confirm Collect');assert.ok(complete);complete.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,stopId:'pickup'}]);});

function offer(h,remaining=30000){return {id:orderId,title:'Synthetic offered parcel',pickup:{name:'Collect here',address:'Fixture'},destination:{name:'Deliver here',address:'Fixture'},offerStartedAt:h.now()-30000+remaining,offerDeadline:h.now()+remaining};}
function free(h,offers=[]){return {...fixture(),canStop:true,data:{assignment:null,offers,serverTime:h.now(),receivedAt:h.now(),recentOrders:[],payments:[]}};}
test('an offer is visible and claimable from Account without changing the current tab',()=>{const h=harness();vm.runInContext("go('account')",h.context);load(h,free(h,[offer(h)]));const claim=all(h.get('deliveryalert')).find(e=>e.textContent==='Claim this delivery →');assert.ok(claim&&!claim.disabled);assert.equal(vm.runInContext('page',h.context),'account');claim.onclick();assert.deepEqual(h.actions,[{action:'accept',orderId}]);});
test('the claim line moves left to right using the office deadline, then expired controls disappear',()=>{const h=harness();load(h,free(h,[offer(h,22500)]));const progress=all(h.get('deliveryalert')).find(e=>e.className==='offertrack');assert.equal(progress.children[0].style.width,'25%');h.advance(23000);assert.equal(h.get('deliveryalert').style.display,'none');assert.equal(all(h.get('deliveryalert')).filter(e=>e.textContent==='Claim this delivery →').length,0);});
test('a busy rider hides even a stale offer and cannot invoke its old claim button',()=>{const h=harness(),o=offer(h);load(h,free(h,[o]));const old=all(h.get('deliveryalert')).find(e=>e.textContent==='Claim this delivery →');const s=fixture();s.data.offers=[o];load(h,s);old.onclick();vm.runInContext("go('offers')",h.context);assert.deepEqual(h.actions,[]);assert.ok(all(h.get('offercontent')).some(e=>e.textContent==='Finish your active delivery before accepting another.'));assert.equal(all(h.get('deliveryalert')).some(e=>e.textContent==='Claim this delivery →'),false);});
test('assigned rides remain prominent from every tab and keep a customer payment draft intact',()=>{const h=harness(),s=fixture();vm.runInContext("go('account')",h.context);load(h,s);assert.ok(all(h.get('deliveryalert')).some(e=>e.textContent==='ACTIVE DELIVERY'));h.context.order=s.data.order;vm.runInContext('openPay(order)',h.context);h.get('amount').value='1234.50';h.get('reference').value='Draft reference';load(h,s);assert.equal(h.get('amount').value,'1234.50');assert.equal(h.get('reference').value,'Draft reference');assert.equal(vm.runInContext('page',h.context),'account');});
test('off duty, disabled GPS and an old connection snapshot cannot expose claim controls',()=>{for(const changes of [{recording:false},{gpsEnabled:false},{old:true}]){const h=harness(),s=free(h,[offer(h)]);Object.assign(s,changes);if(changes.old)s.data.receivedAt-=16000;load(h,s);assert.equal(h.get('deliveryalert').style.display,'none');assert.equal(all(h.get('deliveryalert')).some(e=>e.textContent==='Claim this delivery →'),false);}});
test('offline confirmation of one legacy stop keeps the rest of the trip available',()=>{const h=harness(),s=fixture();delete s.data.assignment.orderId;s.commands=[{payload:{action:'delivered',dispatchId,stopId:'pickup'},error:''}];load(h,s);const next=all(h.get('homecontent')).find(e=>e.textContent==='✓ Confirm Drop');assert.ok(next&&!next.disabled);next.onclick();assert.deepEqual(h.actions,[{action:'delivered',dispatchId,stopId:'delivery'}]);assert.equal(all(h.get('homecontent')).some(e=>e.textContent==='Delivery finished locally · waiting for office receipt'),false);});
test('a failed delivery update remains visible separately from a successful GPS upload',()=>{const h=harness(),s=fixture();s.error='';s.stateError='Delivery connection interrupted.';load(h,s);assert.equal(h.get('notice').textContent,s.stateError);assert.equal(h.get('notice').style.display,'block');assert.ok(all(h.get('deliveryalert')).some(e=>e.textContent==='ACTIVE DELIVERY'));});

test('signed-out rider UI hides a cached assignment and payment details until login',()=>{const h=harness(),s=fixture();s.paired=false;s.savedReports=1;load(h,s);assert.equal(h.get('loginscreen').style.display,'block');assert.equal(h.get('ridernav').style.display,'none');assert.equal(h.get('appcontent').style.display,'none');assert.equal(h.get('deliveryalert').style.display,'none');assert.equal(all(h.get('homecontent')).some(e=>e.textContent==='Synthetic parcel'),false);assert.deepEqual(h.actions,[]);});
test('rider login submits the chosen account through the native bridge and immediately clears the password field',()=>{const h=harness();load(h,{paired:false,events:0,savedReports:0,busy:false,data:{}});h.get('loginusername').value='TestRider';h.get('loginpassword').value='Synthetic-only-password';h.get('loginconsent').checked=true;vm.runInContext('nativeLogin({preventDefault(){}})',h.context);assert.deepEqual(h.logins,[{username:'TestRider',password:'Synthetic-only-password',agreed:true}]);assert.equal(h.get('loginpassword').value,'');assert.deepEqual(h.navigation,[]);});

function merchantFixture(commands=[]){const s=fixture(commands);s.data.order={...s.data.order,network:true,requiresOtp:true,customer:{name:'Fixture customer',phone:'+254712345678'}};s.data.recentOrders=[s.data.order];s.data.network=[{order:s.data.order,customer:s.data.order.customer,merchantName:'Fixture shop',branchName:'Main pickup',feeMinor:20000,earningsMinor:null,fleet:'owned',proofRequired:true}];return s;}
test('native merchant completion requires a six-digit OTP and preserves offline collection-before-delivery identity',()=>{const h=harness();load(h,merchantFixture([{payload:{action:'collected',orderId,dispatchId},error:''}]));const finish=all(h.get('homecontent')).find(e=>e.textContent==='✓ Confirm delivery with OTP');assert.ok(finish);finish.onclick();h.get('deliveryotp').value='123';vm.runInContext('submitProof({preventDefault(){}})',h.context);assert.deepEqual(h.actions,[]);assert.match(h.get('prooferror').textContent,/six-digit/);h.get('deliveryotp').value='012345';vm.runInContext('submitProof({preventDefault(){}})',h.context);assert.deepEqual(h.actions,[{action:'delivered',dispatchId,otp:'012345',orderId}]);assert.equal(h.get('deliveryotp').value,'');});
test('merchant OTP draft survives state refreshes and is cleared when signing out',()=>{const h=harness(),s=merchantFixture();s.data.assignment.stops[0].deliveredAt=h.now();load(h,s);vm.runInContext('openProof(active())',h.context);h.get('deliveryotp').value='012345';load(h,s);assert.equal(h.get('deliveryotp').value,'012345');s.paired=false;load(h,s);assert.equal(h.get('deliveryotp').value,'');assert.equal(vm.runInContext('proofDraft',h.context),null);assert.deepEqual(h.actions,[]);});
test('OTP confirmation rejects a changed assignment and requires collection first',()=>{const h=harness(),s=merchantFixture();load(h,s);vm.runInContext('openProof(active())',h.context);h.get('deliveryotp').value='123456';vm.runInContext('submitProof({preventDefault(){}})',h.context);assert.match(h.get('prooferror').textContent,/collection/);s.data.assignment.id='changed-fixture';load(h,s);assert.equal(vm.runInContext('proofDraft',h.context),null);vm.runInContext('submitProof({preventDefault(){}})',h.context);assert.deepEqual(h.actions,[]);});
test('merchant history displays fee and applicable earnings without customer payment controls',()=>{const h=harness(),s=merchantFixture();s.data.order.status='delivered';s.data.assignment.stops.forEach(stop=>stop.deliveredAt=h.now());s.data.network[0].earningsMinor=18000;s.data.network[0].fleet='shared';s.data.network[0].proof={method:'otp'};s.data.network[0].customer=null;load(h,s);vm.runInContext("go('trips')",h.context);const text=all(h.get('tripcontent')).map(e=>e.textContent).join(' ');assert.match(text,/NETWORK EARNINGS/);assert.doesNotMatch(text,/Fixture customer/);vm.runInContext("openHistory('orders')",h.context);const past=all(h.get('historycontent')).map(e=>e.textContent).join(' ');assert.match(past,/Synthetic parcel/);assert.doesNotMatch(past,/Report exact customer payment/);assert.doesNotMatch(text,/Report cash|Record customer payment|Fixture customer/);h.context.merchant=s.data.order;vm.runInContext('openPay(merchant)',h.context);assert.equal(vm.runInContext('payOrder',h.context),null);assert.deepEqual(h.actions,[]);});
test('exclusive merchant offers can be declined; expired and stale buttons cannot send actions',()=>{const h=harness(),o={...offer(h),network:true,fleet:'shared',merchantName:'Fixture shop',branchName:'Main',feeMinor:20000};load(h,free(h,[o]));const decline=all(h.get('deliveryalert')).find(e=>e.textContent==='Decline offer');assert.ok(decline);decline.onclick();assert.deepEqual(h.actions,[{action:'decline',orderId}]);h.actions.length=0;h.advance(31000);decline.onclick();assert.deepEqual(h.actions,[]);const h2=harness(),o2=offer(h2);load(h2,free(h2,[o2]));assert.equal(all(h2.get('deliveryalert')).some(e=>e.textContent==='Decline offer'),false);const old=all(h2.get('deliveryalert')).find(e=>e.textContent==='Claim this delivery →');h2.advance(16000);old.onclick();assert.deepEqual(h2.actions,[]);});
test('assigned customer contact goes through a scoped native control without an arbitrary phone parameter',()=>{const h=harness();load(h,merchantFixture());const contact=all(h.get('homecontent')).find(e=>e.textContent==='Call assigned customer');assert.ok(contact);contact.onclick();assert.deepEqual(h.navigation,['contactCustomer']);const s=merchantFixture([{payload:{action:'delivered',dispatchId,orderId},error:''}]);load(h,s);assert.equal(all(h.get('homecontent')).some(e=>e.textContent==='Call assigned customer'),false);});
test('rejected OTP correction uses the original receipt rather than making another completion report',()=>{const h=harness(),id='30000000-0000-4000-8000-000000000001',s=merchantFixture([{payload:{action:'delivered',orderId,dispatchId,operationId:id},proofRequired:true,error:'Enter the six-digit customer delivery OTP.'}]);s.data.assignment.stops[0].deliveredAt=h.now();load(h,s);vm.runInContext("go('account')",h.context);const correct=all(h.get('accountcontent')).find(e=>e.textContent==='Correct delivery OTP');assert.ok(correct);correct.onclick();h.get('deliveryotp').value='012345';vm.runInContext('submitProof({preventDefault(){}})',h.context);assert.deepEqual(h.navigation,[{retryOtp:id,otp:'012345'}]);assert.deepEqual(h.actions,[]);});
test('offline collection advances merchant navigation to drop-off and a queued finish removes the target',()=>{const h=harness();load(h,merchantFixture([{payload:{action:'collected',orderId,dispatchId},error:''}]));assert.equal(vm.runInContext('target().id',h.context),'delivery');load(h,merchantFixture([{payload:{action:'delivered',orderId,dispatchId},error:''}]));assert.equal(vm.runInContext('target()',h.context),null);assert.equal(all(h.get('homecontent')).some(e=>e.textContent==='Record customer payment'),false);});

function encodedRoad(points){let oldLat=0,oldLng=0,result='';const delta=n=>{let v=n<0?~(n<<1):n<<1;while(v>=32){result+=String.fromCharCode((32|(v&31))+63);v>>=5;}result+=String.fromCharCode(v+63);};for(const p of points){const lat=Math.round(p.lat*1e6),lng=Math.round(p.lng*1e6);delta(lat-oldLat);delta(lng-oldLng);oldLat=lat;oldLng=lng;}return result;}
function roadFixture(h){const s=fixture();s.point={lat:-1.281,lng:36.821,accuracy:5,recordedAt:h.now()};s.roadRoutes=[{dispatchId,stopId:'pickup',from:{...s.point},to:{lat:-1.28,lng:36.82},geometry:encodedRoad([s.point,{lat:-1.281,lng:36.82},{lat:-1.2805,lng:36.82},{lat:-1.28,lng:36.82}]),distanceMeters:345,durationSeconds:65,calculatedAt:h.now(),profile:'driving'}];return s;}
test('the packaged map follows road vertices and displays engine distance and estimated time',()=>{const h=harness(),s=roadFixture(h);load(h,s);vm.runInContext("go('route')",h.context);const text=all(h.get('routesummary')).map(e=>e.textContent).join(' ');assert.match(text,/0.34 km by road/);assert.match(text,/2 min estimated/);assert.match(text,/no live traffic/);const lines=all(h.get('mapline'));assert.equal(lines.filter(e=>e.tagName==='line').length,0);const poly=lines.find(e=>e.tagName==='polyline');assert.ok(poly);assert.equal(poly.attributes.points.split(' ').length,4);assert.equal(h.navigation.at(-1).dispatchId,dispatchId);});
test('invalid, mismatched, old or distant routes never become a misleading straight-line distance',()=>{for(const mutate of [s=>s.roadRoutes[0].geometry='~~~',s=>s.roadRoutes[0].dispatchId='foreign-job',s=>s.roadRoutes[0].to.lat=-1.3,s=>s.roadRoutes[0].calculatedAt-=600001,s=>s.roadRoutes[0].durationSeconds=-1,s=>s.point.lat=-1.3]){const h=harness(),s=roadFixture(h);mutate(s);load(h,s);vm.runInContext("go('route')",h.context);assert.equal(h.get('mapline').children.length,0);assert.doesNotMatch(all(h.get('routesummary')).map(e=>e.textContent).join(' '),/km by road|straight.line/);}});
test('offline collection switches targets and hides the previous leg; logout removes map geometry',()=>{const h=harness(),s=roadFixture(h);load(h,s);vm.runInContext("go('route')",h.context);assert.equal(h.get('mapline').children.length,1);s.commands=[{payload:{action:'collected',orderId,dispatchId},error:''}];load(h,s);assert.equal(vm.runInContext('target().id',h.context),'delivery');assert.equal(h.get('mapline').children.length,0);s.commands=[];load(h,s);assert.equal(h.get('mapline').children.length,1);s.paired=false;load(h,s);assert.equal(h.get('mapline').children.length,0);assert.equal(vm.runInContext('roadLines.size',h.context),0);});
test('legacy orders expose their assigned recipient and reject old call controls after a reassignment',()=>{const h=harness(),s=fixture();s.data.order.customer={name:'Synthetic recipient',phone:'+254712345678'};load(h,s);const call=all(h.get('homecontent')).find(e=>e.textContent==='Call assigned customer');assert.ok(call);assert.match(all(h.get('homecontent')).map(e=>e.textContent).join(' '),/Synthetic recipient/);call.onclick();assert.deepEqual(h.navigation,['contactCustomer']);s.data.assignment.id='replacement';load(h,s);call.onclick();assert.deepEqual(h.navigation,['contactCustomer']);});
test('older office orders explain where to add contact details and retain ordinary completion',()=>{const h=harness();load(h,fixture());assert.match(all(h.get('homecontent')).map(e=>e.textContent).join(' '),/Ask the office to add it/);assert.equal(all(h.get('homecontent')).some(e=>e.textContent==='Call assigned customer'),false);assert.equal(all(h.get('homecontent')).some(e=>e.textContent==='✓ Confirm delivery with OTP'),false);});
test('road download progress and pause controls remain usable, with a real portal update control',()=>{const h=harness(),s=fixture();s.point={lat:-1.281,lng:36.821,accuracy:5};s.roadLoading=true;s.roadProgress='Downloading road map · 5 / 33 MB';load(h,s);vm.runInContext("go('route')",h.context);assert.match(all(h.get('routesummary')).map(e=>e.textContent).join(' '),/5 \/ 33 MB/);all(h.get('routesummary')).find(e=>e.textContent==='Pause road download').onclick();vm.runInContext("go('account')",h.context);all(h.get('accountcontent')).find(e=>e.textContent==='Check for app updates').onclick();assert.ok(h.navigation.includes('cancelRoads'));assert.ok(h.navigation.includes('checkUpdate'));});

test('offline walk draws the saved measured trail without an assignment and retains it after upload',()=>{const h=harness(),tripId=crypto.randomUUID(),points=Array.from({length:10},(_,i)=>({eventId:crypto.randomUUID(),tripId,kind:'point',recordedAt:h.now()-30000+i*3000,lat:-1.28+i*.00005,lng:36.82,accuracy:5})),s={paired:true,recording:true,lastFix:h.now(),journey:{tripId,points,total:10,pending:10,synced:0,shown:10},data:{},commands:[]};load(h,s);vm.runInContext("go('route');fitJourney()",h.context);const paths=all(h.get('mapline')).filter(e=>e.attributes['data-journey']);assert.equal(paths.length,1);assert.equal((paths[0].attributes.d.match(/L/g)||[]).length,9);assert.match(all(h.get('journeycontent')).map(e=>e.textContent).join(' '),/10 waiting to sync/);s.journey.pending=0;s.journey.synced=10;load(h,s);assert.equal(all(h.get('mapline')).filter(e=>e.attributes['data-journey']).length,1);assert.match(all(h.get('journeycontent')).map(e=>e.textContent).join(' '),/10 uploaded/);s.paired=false;load(h,s);assert.equal(h.get('mapline').children.length,0);assert.equal(vm.runInContext('journeyPoints().length',h.context),0);});
test('native journey map filters an impossible jump and represents missing signal as separate segments',()=>{const h=harness(),tripId=crypto.randomUUID(),p=(at,lat,accuracy=5)=>({eventId:crypto.randomUUID(),tripId,kind:'point',recordedAt:h.now()+at*1000,lat,lng:36.82,accuracy,speed:1});load(h,{paired:true,journey:{points:[p(0,-1.28),p(5,-1.27995),p(8,-1.1),p(10,-1.2799),p(15,-1.2,700),p(140,-1.27),p(145,-1.26995),p(150,-1.2699)],total:8,pending:8,synced:0,shown:8},data:{},commands:[]});vm.runInContext("go('route')",h.context);const paths=all(h.get('mapline')).filter(e=>e.attributes['data-journey']);assert.equal(paths.length,2);assert.equal((paths[0].attributes.d.match(/L/g)||[]).length,2);assert.equal((paths[1].attributes.d.match(/L/g)||[]).length,2);});

test('exact cash plus till reporting refuses underpayment without queuing a receipt',()=>{const h=harness(),s=fixture();s.data.order.status='delivered';s.data.order.amountDue=1000;load(h,s);h.context.order=s.data.order;vm.runInContext('openPay(order)',h.context);h.get('amount').value='900';h.get('method').value='cash';vm.runInContext('submitPayment({preventDefault(){}})',h.context);assert.equal(h.actions.length,0);assert.match(h.get('payerror').textContent,/Expected/);h.get('amount').value='1000';h.get('method').value='mixed';h.get('cashamount').value='300';h.get('tillamount').value='700';h.get('reference').value='FIXTURE-TILL';vm.runInContext('submitPayment({preventDefault(){}})',h.context);assert.deepEqual(h.actions,[{action:'payment',orderId,amount:1000,method:'mixed',reference:'FIXTURE-TILL',cashAmount:300,tillAmount:700}]);});
test('past orders open in a separate history sheet and scoped restore uses the original delivery ID',()=>{const h=harness(),s=fixture();s.data.order.status='delivered';s.data.order.amountDue=0;s.data.payments=[{orderId,method:'cash',amountMinor:0,status:'verified'}];load(h,s);vm.runInContext("go('trips')",h.context);assert.equal(all(h.get('tripcontent')).some(e=>e.textContent==='Synthetic parcel'),false);all(h.get('tripcontent')).find(e=>e.textContent==='See past orders').onclick();assert.equal(h.get('historysheet').classList.contains('open'),true);const restore=all(h.get('historycontent')).find(e=>e.textContent==='Restore cloud journey');assert.ok(restore);restore.onclick();assert.ok(h.navigation.some(n=>n.history==='restore'&&n.kind==='order'&&n.id===orderId));});
