"use client";
import { useCallback,useEffect,useState,type FormEvent } from "react";
import { Copy,KeyRound,Plus,UserRound } from "lucide-react";
import type { Device } from "../../lib/tracking";
import { fleetApi } from "../tracking/use-fleet";
import { OfficeModal } from "./modal";
type Account={id:string;username:string;deviceId:string;driverName:string;phone:string;enabled:number};
type Credentials={username:string;password:string;driverName?:string};
export function DriverAccounts({devices,onChanged}:{devices:Device[];onChanged:()=>Promise<void>}){
  const [accounts,setAccounts]=useState<Account[]>([]),[open,setOpen]=useState(false),[credentials,setCredentials]=useState<Credentials|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState(false);
  const [deviceId,setDeviceId]=useState(""),[driverName,setDriverName]=useState(""),[phone,setPhone]=useState(""),[vehicle,setVehicle]=useState(""),[username,setUsername]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{const data=await fleetApi<{accounts:Account[]}>("/api/office/driver-accounts","GET",undefined,signal);if(!signal?.aborted)setAccounts(data.accounts);},[]);
  useEffect(()=>{const controller=new AbortController();void fleetApi<{accounts:Account[]}>("/api/office/driver-accounts","GET",undefined,controller.signal).then(data=>{if(!controller.signal.aborted)setAccounts(data.accounts);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Could not load driver logins.");});return()=>controller.abort();},[devices]);
  function selectDevice(id:string){setDeviceId(id);const d=devices.find(d=>d.id===id);setDriverName(d?.driverName??"");setPhone(d?.phoneLabel??"");setVehicle(d?.vehicleLabel??"");}
  async function create(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{const result=await fleetApi<Credentials>("/api/office/driver-accounts","POST",{driverName,phone,vehicleLabel:vehicle,...(username.trim()?{username:username.trim()}:{}),...(deviceId?{deviceId}:{})});setOpen(false);setCredentials(result);setCopied(false);setUsername("");selectDevice("");await Promise.all([load(),onChanged()]);}catch(e){setError(e instanceof Error?e.message:"Could not create the driver login.");}finally{setBusy(false);}}
  async function reset(a:Account){if(busy||!window.confirm(`Generate a new password for ${a.driverName}? Their current phone session will need to sign in again.`))return;setBusy(true);setError("");try{setCredentials(await fleetApi<Credentials>("/api/office/driver-accounts","PATCH",{id:a.id}));setCopied(false);await onChanged();}catch(e){setError(e instanceof Error?e.message:"Could not reset the password.");}finally{setBusy(false);}}
  return <section className="driver-accounts"><div className="office-section-heading"><div><h2><KeyRound size={19}/> Driver logins</h2><p className="office-note">Create access here, then give the rider their username and generated password.</p></div><button className="tracking-primary" onClick={()=>{setError("");setOpen(true);}}><Plus size={16}/> Add driver login</button></div>{error&&<p className="office-error" role="alert">{error}</p>}<div className="driver-account-list">{accounts.map(a=><article key={a.id}><UserRound size={20}/><div><strong>{a.driverName}</strong><small>{a.username} · {a.phone}</small></div><button className="office-secondary" disabled={busy} onClick={()=>void reset(a)}><KeyRound size={14}/>{a.enabled?"Reset password":"Restore access"}</button></article>)}</div>{!accounts.length&&<p className="office-note">Add your first driver login. A phone number is required.</p>}
    {open&&<OfficeModal title="Create a driver login" onClose={()=>{if(!busy)setOpen(false);}}><form className="office-form" onSubmit={create}><label>Driver record<select value={deviceId} onChange={e=>selectDevice(e.target.value)}><option value="">Onboard a new driver</option>{devices.filter(d=>!accounts.some(a=>a.deviceId===d.id)).map(d=><option key={d.id} value={d.id}>{d.driverName} · keep existing history</option>)}</select></label><label>Driver name<input required minLength={2} maxLength={80} value={driverName} disabled={!!deviceId} onChange={e=>setDriverName(e.target.value)} autoComplete="name"/></label><label>Phone number <span aria-hidden="true">*</span><input type="tel" required maxLength={30} value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" placeholder="0712345678 or +254712345678"/></label><label>Vehicle / registration<input maxLength={80} value={vehicle} disabled={!!deviceId} onChange={e=>setVehicle(e.target.value)}/></label><label>Custom username (optional)<input maxLength={32} value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off" autoCapitalize="none" placeholder="Leave blank to generate a username"/></label><p className="office-note">The system generates a password. Save it when it appears; you can generate a replacement later.</p>{error&&<p role="alert" className="office-error">{error}</p>}<div className="office-form-actions"><button type="button" className="office-secondary" disabled={busy} onClick={()=>setOpen(false)}>Back</button><button type="submit" className="tracking-primary" disabled={busy}>{busy?"Creating login…":"Generate driver login"}<KeyRound size={16}/></button></div></form></OfficeModal>}
    {credentials&&<OfficeModal title="Driver login is ready" onClose={()=>setCredentials(null)}><p className="office-note">Share these details with the rider. This password is shown here once.</p><dl className="driver-credentials"><dt>Username</dt><dd>{credentials.username}</dd><dt>Password</dt><dd>{credentials.password}</dd></dl><button className="office-secondary" onClick={()=>void navigator.clipboard.writeText(`Username: ${credentials.username}\nPassword: ${credentials.password}`).then(()=>setCopied(true)).catch(()=>setError("Copy is unavailable. Select the details above to copy them."))}><Copy size={15}/>{copied?"Copied":"Copy login details"}</button><p className="office-note">Install Rider 1.4 and sign in. For an existing driver, the same history and assignment stay linked.</p><div className="office-form-actions"><button className="tracking-primary" onClick={()=>setCredentials(null)}>I have saved the details</button></div></OfficeModal>}
  </section>;
}
