"use client";
import { useState } from "react";
import { LocateFixed, Phone, Send, Store, UserRound } from "lucide-react";
import type { Device } from "../../lib/tracking";
import type { Dispatch } from "../../lib/dispatch";
import { driverChoices, orderStatusLabels, phoneLink, type DriverProfile, type OfficeData, type OfficeOrder, type Place } from "../../lib/office";
import { fleetApi } from "../tracking/use-fleet";
import { DriverTelemetry } from "../tracking/operations";
import { OfficeModal } from "./modal";
import { PlacePicker } from "./place-picker";

type Shared={data:OfficeData;devices:Device[];dispatches:Dispatch[];onChanged:()=>Promise<void>;onClose:()=>void};
function DriverSelect({value,onChange,devices,profiles,dispatches,pickup}:{value:string;onChange:(id:string)=>void;devices:Device[];profiles:DriverProfile[];dispatches:Dispatch[];pickup?:Place|null}) {
  const choices=driverChoices(devices,profiles,dispatches,pickup),recommended=choices.find(c=>c.available);
  return <div className="office-driver-choice"><label>Assign a company driver<select value={value} onChange={event=>onChange(event.target.value)}><option value="auto">Automatic · free driver with longest idle time</option>{choices.map(c=><option key={c.device.id} value={c.device.id} disabled={!c.available}>{c.device.driverName} · {c.device.vehicleLabel||"Linked vehicle"} · {c.reason}</option>)}</select></label><p><UserRound size={15}/>{value==="auto"?recommended?`Suggested: ${recommended.device.driverName}${recommended.pickupMeters!=null?` · ${(recommended.pickupMeters/1000).toFixed(1)} km straight-line from pickup`:""}`:"No free driver with fresh GPS. Save the request to the queue.":"Manual assignment — availability is rechecked when you dispatch."}</p><small>Only paired company drivers appear. Busy, off-duty or delayed devices cannot receive a new dispatch. Ties use pickup proximity.</small></div>;
}
export function NewOrderForm({data,devices,dispatches,onChanged,onClose,initialDriver,previous=[]}:Shared&{initialDriver?:string;previous?:Place[]}){
  const [requestId]=useState(()=>crypto.randomUUID()),[title,setTitle]=useState(""),[notes,setNotes]=useState("");
  const [pickup,setPickup]=useState<Place|null>(data.settings.location?{...data.settings.location,name:data.settings.name,source:"office"}:null),[destination,setDestination]=useState<Place|null>(null);
  const [driver,setDriver]=useState(initialDriver??"auto"),[remember,setRemember]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [created,setCreated]=useState<OfficeOrder|null>(null);
  const choices=driverChoices(devices,data.profiles,dispatches,pickup),available=driver==="auto"?choices.some(c=>c.available):choices.some(c=>c.device.id===driver&&c.available);
  async function submit(dispatch:boolean){
    if(!created&&(!title.trim()||!pickup||!destination)){setError("Name the request and select both pickup and delivery locations.");return;}
    setBusy(true);setError("");
    try{
      let order=created;
      if(!order){
        let target=destination!;
        if(remember&&!target.partnerId){const partner=await fleetApi<{id:string;name:string;location:Place}>("/api/office/partners","POST",{name:target.name,location:target,phone:"",contact:""});target={...partner.location,name:partner.name,source:"partner",partnerId:partner.id};setDestination(target);}
        order=await fleetApi<OfficeOrder>("/api/office/orders","POST",{id:requestId,title:title.trim(),pickup,destination:target,notes:notes.trim()});setCreated(order);
      }
      if(dispatch){const current=data.orders.find(o=>o.id===order!.id)??order;setCreated(await fleetApi<OfficeOrder>("/api/office/orders","PATCH",{id:current.id,version:current.version,action:"assign",deviceId:driver}));}
      await onChanged();onClose();
    }catch(e){setError(e instanceof Error?e.message:"Could not save the delivery request.");await onChanged().catch(()=>{});}finally{setBusy(false);}
  }
  return <OfficeModal title="New collection & delivery" onClose={onClose}><form className="office-form" onSubmit={event=>{event.preventDefault();void submit(true);}}>
    {created&&<p className="office-saved-notice">Request saved · {orderStatusLabels[(data.orders.find(o=>o.id===created.id)??created).status]}. You can close this window safely.</p>}
    <fieldset disabled={busy||!!created}><label>Request / customer reference<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={100} placeholder="e.g. Collect customer parcel"/></label>
      <PlacePicker label="Collect from" value={pickup} onChange={setPickup} partners={data.partners} previous={previous} initialCenter={data.settings.location??devices.find(d=>d.latestPoint)?.latestPoint??undefined}/>
      {data.settings.location&&<button type="button" className="office-inline-button" onClick={()=>setPickup({...data.settings.location!,name:data.settings.name,source:"office"})}>Use main office as pickup</button>}
      <PlacePicker label="Deliver to" value={destination} onChange={setDestination} partners={data.partners} previous={previous} initialCenter={pickup??data.settings.location??undefined}/>
      {destination&&!destination.partnerId&&<label className="office-checkbox"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Register this destination as a partner for future deliveries</label>}
      <label>Collection / delivery instructions<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000} rows={2} placeholder="Contact person, parcel reference or entrance instructions"/></label>
    </fieldset>
    <DriverSelect value={driver} onChange={setDriver} devices={devices} profiles={data.profiles} dispatches={dispatches} pickup={pickup}/>
    {error&&<p role="alert" className="office-form-error">{error}{created?" Your saved request is retained. Check its latest office status.":""}</p>}
    <div className="office-form-actions"><button type="button" className="office-secondary" disabled={busy} onClick={()=>created?onClose():void submit(false)}>{created?"Close":"Save to queue"}</button><button className="tracking-primary" disabled={busy||!available||!!created&&(data.orders.find(o=>o.id===created.id)??created).status!=="queued"}><Send size={16}/>{busy?"Saving…":created?"Dispatch saved request":"Create & dispatch"}</button></div>
    <p className="office-note">The driver app keeps recording as it does now. The office tracks this assignment; driver-side route guidance will be added in the later app update.</p>
  </form></OfficeModal>;
}
export function AssignOrderForm({order,data,devices,dispatches,onChanged,onClose}:Shared&{order:OfficeOrder}){
  const [driver,setDriver]=useState("auto"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const choices=driverChoices(devices,data.profiles,dispatches,order.pickup),available=driver==="auto"?choices.some(c=>c.available):choices.some(c=>c.device.id===driver&&c.available);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{await fleetApi("/api/office/orders","PATCH",{id:order.id,version:order.version,action:"assign",deviceId:driver});await onChanged();onClose();}catch(e){setError(e instanceof Error?e.message:"Dispatch failed.");await onChanged().catch(()=>{});}finally{setBusy(false);}}
  return <OfficeModal title={`Dispatch ${order.title}`} onClose={onClose}><form className="office-form" onSubmit={submit}><div className="office-route-summary"><strong>Collect: {order.pickup.name}</strong><span>Deliver: {order.destination.name}</span></div><DriverSelect value={driver} onChange={setDriver} devices={devices} profiles={data.profiles} dispatches={dispatches} pickup={order.pickup}/>{error&&<p role="alert" className="office-form-error">{error}</p>}<div className="office-form-actions"><button type="button" className="office-secondary" onClick={onClose}>Back to office</button><button className="tracking-primary" disabled={busy||!available}><Send size={16}/>{busy?"Dispatching…":"Dispatch driver"}</button></div></form></OfficeModal>;
}
export function PartnerForm({data,devices,onChanged,onClose}:Pick<Shared,"data"|"devices"|"onChanged"|"onClose">){
  const [name,setName]=useState(""),[contact,setContact]=useState(""),[phone,setPhone]=useState(""),[location,setLocation]=useState<Place|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(event:React.FormEvent){event.preventDefault();if(!location){setError("Select the shop location first.");return;}setBusy(true);setError("");try{await fleetApi("/api/office/partners","POST",{name:name.trim(),contact:contact.trim(),phone:phone.trim(),location});await onChanged();onClose();}catch(e){setError(e instanceof Error?e.message:"Could not register partner.");}finally{setBusy(false);}}
  return <OfficeModal title="Register a partner destination" onClose={onClose}><form className="office-form" onSubmit={submit}><label>Shop / partner name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Name used by your office"/></label><PlacePicker label="Partner location" value={location} onChange={setLocation} partners={data.partners} initialCenter={data.settings.location??devices.find(d=>d.latestPoint)?.latestPoint??undefined}/><div className="office-form-columns"><label>Contact person<input maxLength={100} value={contact} onChange={e=>setContact(e.target.value)}/></label><label>Contact phone<input type="tel" maxLength={32} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+254…"/></label></div>{error&&<p role="alert" className="office-form-error">{error}</p>}<div className="office-form-actions"><button type="button" className="office-secondary" onClick={onClose}>Cancel</button><button className="tracking-primary" disabled={busy}><Store size={16}/>{busy?"Saving…":"Register destination"}</button></div></form></OfficeModal>;
}
export function DriverDetails({device,profile,dispatches,onChanged,onClose}:{device:Device;profile?:DriverProfile;dispatches:Dispatch[];onChanged:()=>Promise<void>;onClose:()=>void}){
  const [vehicle,setVehicle]=useState(profile?.vehicleLabel??device.vehicleLabel),[phone,setPhone]=useState(profile?.phone??device.phoneLabel),[onDuty,setOnDuty]=useState(profile?.onDuty??true),[rate,setRate]=useState(profile?.ratePerKm?.toString()??""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const assignment=dispatches.find(d=>d.deviceId===device.id&&d.stops.some(s=>!s.deliveredAt)),call=phoneLink(phone);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{await fleetApi("/api/office/drivers","PATCH",{deviceId:device.id,vehicleLabel:vehicle.trim(),phone:phone.trim(),onDuty,ratePerKm:rate.trim()?Number(rate):null});await onChanged();onClose();}catch(e){setError(e instanceof Error?e.message:"Could not update driver details.");}finally{setBusy(false);}}
  return <OfficeModal title={device.driverName} onClose={onClose}><div className="office-driver-identity"><UserRound size={27}/><div><strong>Onboarded company driver</strong><span>{device.deviceName||"Paired Android phone"} · {assignment?assignment.name:"No active dispatch"}</span></div>{call?<a className="tracking-primary" href={call}><Phone size={15}/> Call driver</a>:<small>Add a phone number to enable calling.</small>}</div><DriverTelemetry device={device}/><form className="office-form" onSubmit={submit}><label>Driver name<input value={device.driverName} readOnly/><small>Orders use this registered driver record.</small></label><div className="office-form-columns"><label>Vehicle / registration<input maxLength={80} value={vehicle} onChange={e=>setVehicle(e.target.value)}/></label><label>Driver phone<input type="tel" maxLength={32} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+254…"/></label></div><label className="office-checkbox"><input type="checkbox" checked={onDuty} onChange={e=>setOnDuty(e.target.checked)}/> On duty and available for future assignments</label><label>Agreed rate per recorded kilometre (KSh)<input type="number" min={0} max={10000} step="0.01" value={rate} onChange={e=>setRate(e.target.value)} placeholder="Leave blank if not set"/></label><small>The rate is captured on new orders. GPS mileage and suggested pay are estimates for office review; no payment is sent.</small>{error&&<p role="alert" className="office-form-error">{error}</p>}<div className="office-form-actions"><button type="button" className="office-secondary" onClick={onClose}>Close</button><button className="tracking-primary" disabled={busy}>{busy?"Saving…":"Save driver details"}</button></div></form></OfficeModal>;
}
export function OfficeSettingsForm({data,devices,onChanged,onClose}:Pick<Shared,"data"|"devices"|"onChanged"|"onClose">){
  const [name,setName]=useState(data.settings.name),[location,setLocation]=useState<Place|null>(data.settings.location),[busy,setBusy]=useState(false),[error,setError]=useState("");
  function locate(){if(!navigator.geolocation){setError("This browser cannot share a location. Search the office address or select a map pin.");return;}setBusy(true);navigator.geolocation.getCurrentPosition(position=>{setLocation({name:name||"Main office",address:`Office location · reported accuracy ±${Math.round(position.coords.accuracy)} m`,lat:position.coords.latitude,lng:position.coords.longitude,source:"office"});setBusy(false);},()=>{setError("Location was unavailable. Search the address or choose the pin on the map.");setBusy(false);},{enableHighAccuracy:true,timeout:10000,maximumAge:0});}
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{await fleetApi("/api/office/settings","PATCH",{name:name.trim(),location});await onChanged();onClose();}catch(e){setError(e instanceof Error?e.message:"Could not save the office.");}finally{setBusy(false);}}
  return <OfficeModal title="Main office" onClose={onClose}><form className="office-form" onSubmit={submit}><label>Office / company name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><PlacePicker label="Office location" value={location} onChange={setLocation} partners={data.partners} initialCenter={devices.find(d=>d.latestPoint)?.latestPoint??undefined}/><button type="button" className="office-secondary" disabled={busy} onClick={locate}><LocateFixed size={15}/> Use this computer&apos;s location</button><p className="office-note">Check the entrance pin before saving. This becomes the default collection point; driver GPS is not used as the office address.</p>{error&&<p role="alert" className="office-form-error">{error}</p>}<div className="office-form-actions"><button type="button" className="office-secondary" onClick={onClose}>Cancel</button><button className="tracking-primary" disabled={busy}>{busy?"Saving…":"Save office"}</button></div></form></OfficeModal>;
}
