"use client";
import { useState } from "react";
import { BadgeCheck, Banknote, CircleDollarSign, Download, Wallet } from "lucide-react";
import { moneyExact, salesSummary, type OfficeData, type Payment } from "../../lib/office";
import { csvCell } from "../../lib/csv";
import { fleetApi } from "../tracking/use-fleet";

export function SalesStrip({data,onOpen}:{data:OfficeData;onOpen:()=>void}){
  const totals=data.sales??salesSummary(data.orders,data.payments??[],data.serverTime);
  return <section className="office-sales-strip" aria-label="Customer payment totals"><div><span><CircleDollarSign size={17}/> CUSTOMER COLLECTIONS</span><strong>{moneyExact(totals.reportedMinor)}</strong><small>Driver reports · {totals.pendingReview} awaiting office review</small></div><div><span><Banknote size={16}/> CASH</span><strong>{moneyExact(totals.cashMinor)}</strong><small>Reported cash received</small></div><div><span><Wallet size={16}/> COMPANY TILL</span><strong>{moneyExact(totals.tillMinor)}</strong><small>Reported till payments</small></div><button className="office-secondary" onClick={onOpen}>Open sales & totals →</button></section>;
}
function downloadPayments(payments:Payment[]){
  const header=["order_id","driver","method","amount_ksh","review_status","receipt_reference","reported_at"];
  const content=[header.join(","),...payments.map(p=>[p.orderId,p.driverName,p.method,(p.amountMinor/100).toFixed(2),p.status,p.reference,new Date(p.reportedAt).toISOString()].map(csvCell).join(","))].join("\r\n");
  const url=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download="routeforge-payment-reports.csv";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function SalesWorkspace({data,onChanged}:{data:OfficeData;onChanged:()=>Promise<void>}){
  const [busy,setBusy]=useState(""),[error,setError]=useState("");
  const payments=data.payments??[],totals=data.sales??salesSummary(data.orders,payments,data.serverTime);
  async function review(p:Payment,status:"verified"|"void"){
    if(!window.confirm(status==="verified"?`Confirm you have checked ${moneyExact(p.amountMinor)} ${p.method==="cash"?"cash received":"company till receipt"} for ${p.driverName}?`:`Void this ${moneyExact(p.amountMinor)} driver report? The audit record is retained.`))return;
    setBusy(p.orderId);setError("");try{await fleetApi("/api/office/payments","PATCH",{orderId:p.orderId,version:p.version,status});await onChanged();}catch(e){setError(e instanceof Error?e.message:"Could not review the payment.");await onChanged().catch(()=>{});}finally{setBusy("");}
  }
  const days=Array.from({length:7},(_,i)=>{const end=Math.floor((data.serverTime+10800000)/86400000)*86400000-10800000+(i-5)*86400000,start=end-86400000;return {start,label:new Date(start).toLocaleDateString("en-KE",{timeZone:"Africa/Nairobi",weekday:"short"}),amount:payments.filter(p=>p.status!=="void"&&p.reportedAt>=start&&p.reportedAt<end).reduce((sum,p)=>sum+p.amountMinor,0)};}),max=Math.max(1,...days.map(d=>d.amount));
  const unpaid=data.orders.filter(o=>o.status==="delivered"&&!payments.some(p=>p.orderId===o.id&&p.status!=="void"));
  return <section className="office-sales"><div className="office-stats office-finance-stats"><div><span>VERIFIED COLLECTIONS</span><strong>{moneyExact(totals.verifiedMinor)}</strong><small>Office reviewed · included in reported totals</small></div><div><span>TODAY · NAIROBI</span><strong>{moneyExact(totals.todayMinor)}</strong><small>Customer payments reported today</small></div><div><span>EXPECTED ORDER VALUE</span><strong>{moneyExact(totals.expectedMinor)}</strong><small>Entered order amounts · excludes cancellations</small></div><div><span>DELIVERED / NO REPORT</span><strong>{totals.unpaidDelivered}</strong><small>{totals.delivered} deliveries completed · all time</small></div></div>
    <div className="office-finance-grid"><article className="office-finance-chart"><div className="office-section-heading"><h2>Recent customer collections</h2><span>Latest 500 reports · KSh</span></div><div className="office-chart-bars" role="img" aria-label={days.map(d=>`${d.label}: ${moneyExact(d.amount)}`).join("; ")}>{days.map(d=><div key={d.start}><small>{moneyExact(d.amount)}</small><i style={{height:`${Math.max(2,d.amount/max*125)}px`}}/><span>{d.label}</span></div>)}</div></article><article className="office-finance-chart"><h2>Journey & rider costs</h2><strong className="office-finance-number">{totals.measuredKm.toFixed(2)} km</strong><p>Recorded GPS mileage estimate across company orders.</p><strong className="office-finance-number">{moneyExact(totals.estimatedDriverCostMinor)}</strong><p>Suggested driver pay from each order&apos;s agreed kilometre rate. Review missing segments and mileage before payment.</p><small>Customer sales and driver pay are separate records. RouteForge does not transfer money or verify till transactions automatically.</small></article></div>
    <div className="office-section-heading"><h2><Wallet size={18}/> Customer payment ledger <span>{totals.pendingReview} pending review</span></h2><button className="office-secondary" disabled={!payments.length} onClick={()=>downloadPayments(payments)}><Download size={15}/> Export reports</button></div>{error&&<p role="alert" className="office-error">{error}</p>}
    <div className="office-ledger" role="table" aria-label="Driver reported customer payments"><div className="office-ledger-head" role="row"><span>ORDER / RIDER</span><span>RECEIVED</span><span>METHOD / REFERENCE</span><span>REVIEW</span></div>{payments.map(p=>{const o=data.orders.find(o=>o.id===p.orderId);return <div className={`office-ledger-row payment-${p.status}`} key={p.orderId} role="row"><div><strong>{o?.title??`Order #${p.orderId.slice(0,8)}`}</strong><small>{p.driverName} · {new Date(p.reportedAt).toLocaleString()}</small></div><strong>{moneyExact(p.amountMinor)}</strong><div>{p.method==="cash"?"Cash collected":"Company till"}<small>{p.reference||"No receipt reference"}{o?.amountDue!=null?` · Expected ${moneyExact(Math.round(o.amountDue*100))}`:""}</small></div><div><span className={`office-payment-status ${p.status}`}>{p.status==="verified"?<BadgeCheck size={13}/>:null}{p.status==="reported"?"Awaiting office review":p.status==="verified"?"Office verified":"Voided"}</span>{p.status==="reported"&&<div className="office-ledger-actions"><button disabled={busy===p.orderId} onClick={()=>void review(p,"verified")}>Verify received</button><button disabled={busy===p.orderId} onClick={()=>void review(p,"void")}>Void report</button></div>}</div></div>;})}{!payments.length&&<div className="office-empty"><CircleDollarSign size={32}/><h3>Your live sales ledger starts here</h3><p>Riders finish delivery, then report the amount received as cash or company till. Real reports populate these totals.</p></div>}</div>
    <div className="office-section-heading"><h2>Delivered orders awaiting a payment report</h2></div>{unpaid.slice(0,20).map(o=><div className="office-unpaid-row" key={o.id}><span><strong>{o.title}</strong><small>{o.driverName??"Company rider"}</small></span><span>{o.amountDue==null?"Expected amount not entered":moneyExact(Math.round(o.amountDue*100))}</span></div>)}{!unpaid.length&&<p className="office-note">No unmatched deliveries among the latest 500 office records.</p>}<p className="office-note">All-time totals are calculated from stored company records, including older orders beyond this view. Reports marked void remain visible for review and are excluded from monetary totals.</p>
  </section>;
}
