"use client";
import { useCallback, useEffect, useState } from "react";
import { ArrowRight, CheckCheck, Compass, Download, FolderClock, LayoutDashboard, MapPin, Package, Phone, Plus, Radio, RefreshCw, Send, Settings, Store, Truck, UserRound } from "lucide-react";
import { isOpenOrder, driverChoices, orderStatusLabels, phoneLink, type OfficeData, type OfficeOrder, type Place } from "../../lib/office";
import type { SavedPlan, OptimizationResult } from "../../lib/model";
import { money } from "../../lib/model";
import { csvCell, routeCsv } from "../../lib/csv";
import { fleetApi, useFleet } from "../tracking/use-fleet";
import { DispatchProgress, FleetAlerts } from "../tracking/operations";
import JourneyMap from "../tracking/map";
import { OfficeModal } from "./modal";
import { useOffice } from "./use-office";
import { FleetMonitor } from "./fleet-monitor";
import { AssignOrderForm, DriverDetails, NewOrderForm, OfficeSettingsForm, PartnerForm } from "./forms";

type View="dispatch"|"deliveries"|"fleet"|"partners"|"plans";
type Archive={plans:SavedPlan[];runs:{id:string;name:string;createdAt:number;result:OptimizationResult}[]};
const emptyOffice:OfficeData={orders:[],partners:[],profiles:[],settings:{name:"SHADOWNET Office",location:null},serverTime:0};
const views=[{id:"dispatch" as const,label:"Dispatch",Icon:LayoutDashboard},{id:"deliveries" as const,label:"Deliveries",Icon:Package},{id:"fleet" as const,label:"Drivers & fleet",Icon:Truck},{id:"partners" as const,label:"Partner destinations",Icon:Store},{id:"plans" as const,label:"Saved plans",Icon:FolderClock}];
function download(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function orderCsv(orders:OfficeOrder[]){return [["reference","status","pickup","destination","driver","vehicle","gps_km_estimate","excluded_segments","rate_ksh_km","suggested_pay_ksh","created_at"].join(","),...orders.map(o=>[o.title,orderStatusLabels[o.status],o.pickup.address,o.destination.address,o.driverName??"",o.vehicleLabel??"",o.measuredKm,o.excludedSegments,o.ratePerKm??"",o.ratePerKm==null?"":Math.round(o.measuredKm*o.ratePerKm),new Date(o.createdAt).toISOString()].map(csvCell).join(","))].join("\r\n");}

export default function OfficeWorkspace({signedIn,userName,signInPath}:{signedIn:boolean;userName:string;signInPath:string}) {
  const fleet=useFleet(signedIn),office=useOffice(signedIn),data=office.data??emptyOffice;
  const [view,setView]=useState<View>("dispatch"),[selectedId,setSelectedId]=useState("");
  const [trackerOpen,setTrackerOpen]=useState(false),[newOrder,setNewOrder]=useState<string|null>(null),[assignId,setAssignId]=useState<string|null>(null),[detailsId,setDetailsId]=useState<string|null>(null),[partnerOpen,setPartnerOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[guideOpen,setGuideOpen]=useState(false);
  const [filter,setFilter]=useState<"open"|"all"|"history">("open"),[busyId,setBusyId]=useState(""),[actionError,setActionError]=useState("");
  const [archive,setArchive]=useState<Archive>({plans:[],runs:[]}),[archiveError,setArchiveError]=useState(""),[archived,setArchived]=useState(false),[archivePlan,setArchivePlan]=useState<SavedPlan|null>(null);
  const drivers=fleet.devices.filter(d=>d.pairedAt&&!d.revokedAt),selected=drivers.find(d=>d.id===selectedId)??drivers[0];
  const active=data.orders.filter(isOpenOrder),legacy=fleet.dispatches.filter(d=>!d.orderId&&d.stops.some(s=>!s.deliveredAt));
  const choices=driverChoices(fleet.devices,data.profiles,fleet.dispatches),ready=choices.filter(c=>c.available),live=drivers.filter(d=>d.status==="live");
  const driverDetails=drivers.find(d=>d.id===detailsId),assignedOrder=data.orders.find(o=>o.id===assignId);
  const previousLocations=[...new Map([...archive.plans.flatMap(p=>p.scenario.deliveries),...fleet.dispatches.flatMap(d=>d.stops)].map(p=>[`${p.lat}:${p.lng}:${p.address}`,{name:p.name,address:p.address,lat:p.lat,lng:p.lng,source:"previous" as const}])).values()].slice(0,60);
  const {refresh:refreshOffice}=office,{refresh:refreshFleet}=fleet;
  const refresh=useCallback(async()=>{await Promise.all([refreshOffice(),refreshFleet()]);},[refreshOffice,refreshFleet]);
  const refreshArchive=useCallback(async()=>{if(!signedIn)return;try{setArchive(await fleetApi<Archive>("/api/plans"));setArchiveError("");}catch(e){setArchiveError(e instanceof Error?e.message:"Could not open saved plans.");}},[signedIn]);
  useEffect(()=>{
    if(!signedIn)return;
    const controller=new AbortController();
    void fleetApi<Archive>("/api/plans","GET",undefined,controller.signal).then(result=>{if(!controller.signal.aborted){setArchive(result);setArchiveError("");}}).catch(e=>{if(!controller.signal.aborted)setArchiveError(e instanceof Error?e.message:"Could not open saved plans.");});
    return()=>controller.abort();
  },[signedIn]);
  function navigate(next:View){setView(next);window.scrollTo({top:0,behavior:"smooth"});}
  async function orderAction(order:OfficeOrder,action:"confirm_pickup"|"confirm_delivery"|"cancel"){
    if(action==="cancel"&&!window.confirm(`Cancel ${order.title}? Driver GPS recording continues.`))return;
    setBusyId(order.id);setActionError("");try{await fleetApi("/api/office/orders","PATCH",{id:order.id,version:order.version,action});await refresh();}catch(e){setActionError(e instanceof Error?e.message:"Could not update the order.");await refresh().catch(()=>{});}finally{setBusyId("");}
  }
  async function togglePartner(id:string,enabled:boolean){setBusyId(id);setActionError("");try{await fleetApi("/api/office/partners","PATCH",{id,active:enabled});await office.refresh();}catch(e){setActionError(e instanceof Error?e.message:"Could not update destination.");}finally{setBusyId("");}}
  async function archiveAction(plan:SavedPlan){setBusyId(plan.id);try{await fleetApi("/api/plans","PATCH",{id:plan.id,archived:!plan.archivedAt});await refreshArchive();}catch(e){setArchiveError(e instanceof Error?e.message:"Could not update saved plan.");}finally{setBusyId("");}}
  const shownOrders=data.orders.filter(o=>filter==="all"||filter==="open"&&isOpenOrder(o)||filter==="history"&&!isOpenOrder(o));
  const cards=(orders:OfficeOrder[])=>orders.map(order=>{
    const d=drivers.find(d=>d.id===order.deviceId),profile=data.profiles.find(p=>p.deviceId===order.deviceId),call=phoneLink(profile?.phone||d?.phoneLabel||"");
    return <article className={`office-order-card order-${order.status}`} key={order.id}>
      <div className="office-order-heading"><div><small>#{order.id.slice(0,8).toUpperCase()} · {new Date(order.createdAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small><h3>{order.title}</h3></div><span className={`office-order-status ${order.status}`}>{orderStatusLabels[order.status]}</span></div>
      <div className="office-order-route"><div><span>COLLECT</span><strong>{order.pickup.name}</strong><small>{order.pickup.address}</small></div><ArrowRight size={18}/><div><span>DELIVER</span><strong>{order.destination.name}</strong><small>{order.destination.address}</small></div></div>
      {order.notes&&<p className="office-order-notes">{order.notes}</p>}
      <div className="office-order-driver"><UserRound size={16}/>{order.driverName?<><button disabled={!d} onClick={()=>setDetailsId(order.deviceId)}>{order.driverName}</button><span>{order.vehicleLabel}</span>{d&&<button onClick={()=>{setSelectedId(d.id);setTrackerOpen(true);}}><Radio size={14}/> Track</button>}{call&&<a href={call}><Phone size={14}/> Call</a>}</>:<span>Choose from your available company drivers</span>}</div>
      {order.assignedAt&&<div className="office-distance-row"><span><strong>{order.measuredKm.toFixed(2)} km</strong> recorded GPS estimate{order.excludedSegments?` · ${order.excludedSegments} gap / uncertain segments excluded`:""}</span><span>{order.ratePerKm==null?"Rate not set":`${money(order.ratePerKm)}/km · ${money(order.measuredKm*order.ratePerKm)} suggested pay`}</span><small>{order.estimatedKm?.toFixed(1)} km initial straight-line estimate including pickup approach · Review mileage before paying</small></div>}
      <div className="office-order-actions">{order.status==="queued"&&<button className="tracking-primary" onClick={()=>setAssignId(order.id)} disabled={!ready.length}><Send size={15}/> Assign driver</button>}{order.status==="pickup_arrived"&&<button className="tracking-primary" disabled={busyId===order.id} onClick={()=>void orderAction(order,"confirm_pickup")}><Package size={15}/> Confirm collection</button>}{order.status==="arrived"&&<button className="tracking-primary" disabled={busyId===order.id} onClick={()=>void orderAction(order,"confirm_delivery")}><CheckCheck size={15}/> Confirm delivery</button>}{isOpenOrder(order)&&<button className="office-inline-button" disabled={busyId===order.id} onClick={()=>void orderAction(order,"cancel")}>Cancel request</button>}{order.status==="delivered"&&<span><CheckCheck size={16}/> Confirmed {new Date(order.deliveredAt!).toLocaleString()}</span>}{order.status==="queued"&&!ready.length&&<small>Waiting for a free driver with live GPS</small>}{["assigned","en_route"].includes(order.status)&&<small>GPS arrival requires two precise fixes at the next destination.</small>}</div>
    </article>;
  });
  const monitor=<FleetMonitor devices={fleet.devices} dispatches={fleet.dispatches} profiles={data.profiles} selectedId={selected?.id??""} onSelect={setSelectedId} onDetails={setDetailsId}/>;
  return <main className="office-shell">
    <aside className="office-sidebar"><button className="brand" onClick={()=>navigate("dispatch")} aria-label="Open dispatch office"><span className="brand-mark"><Compass size={23}/></span>routeforge<span className="brand-period">.</span></button><button className="office-company" onClick={()=>setSettingsOpen(true)} disabled={!signedIn}><span>S</span><div><strong>{data.settings.name}</strong><small>Main office</small></div><Settings size={15}/></button><span className="tiny-label">OPERATIONS</span><nav aria-label="Office navigation">{views.map(({id,label,Icon})=><button key={id} className={view===id?"active":""} onClick={()=>navigate(id)}><Icon size={18}/>{label}{id==="deliveries"&&<span>{active.length}</span>}{id==="fleet"&&<span>{drivers.length}</span>}</button>)}<button onClick={()=>setTrackerOpen(true)}><Radio size={18}/> Live tracking <span className="office-live-dot"/></button></nav><div className="office-sidebar-bottom"><button onClick={()=>setGuideOpen(true)}><MapPin size={16}/> Office guide</button><div><span className="office-avatar">{userName.charAt(0).toUpperCase()}</span><p><strong>{userName}</strong><small>{signedIn?"Private office records":"Sign in to open your office"}</small></p></div></div></aside>
    <section className="office-content"><header className="office-topbar"><div><span className="tiny-label">MAIN OFFICE</span><h1>{view==="dispatch"?"Your office, in motion.":view==="deliveries"?"Every collection, connected.":view==="fleet"?"Your onboarded fleet.":view==="partners"?"Your partner destinations.":"Saved planning archive."}</h1><p>{view==="dispatch"?"Real drivers. Registered locations. One delivery desk.":view==="deliveries"?"Create a collection, assign an available driver and follow its progress.":view==="fleet"?"Only your paired company drivers and their actual vehicles appear here.":view==="partners"?"Save the shops and collection points your company works with.":"Past plans and optimizer runs stay here; they do not create live orders."}</p></div><div><button className="office-secondary" disabled={!signedIn} aria-label="Refresh office and drivers" onClick={()=>void refresh().catch(e=>setActionError(e.message))}><RefreshCw size={16}/></button><button className="office-secondary" onClick={()=>setTrackerOpen(true)}><Radio size={16}/> Track fleet</button><button className="tracking-primary" disabled={!signedIn||office.loading} onClick={()=>setNewOrder("auto")}><Plus size={17}/> New delivery</button></div></header>
      {!signedIn?<section className="office-signin"><Compass size={42}/><h2>Your office records stay private.</h2><p>Sign in to manage company drivers, destinations and deliveries.</p><a className="tracking-primary" href={signInPath} target="_top">Sign in with ChatGPT</a></section>:<>
        {(office.error||fleet.error||actionError)&&<p role="alert" className="office-error">{actionError||office.error||fleet.error}</p>}
        <div className="office-stats"><div><span>ONBOARDED DRIVERS</span><strong>{drivers.length}</strong><small>{live.length} with fresh GPS</small></div><div><span>FREE FOR DISPATCH</span><strong>{ready.length}</strong><small>On duty · fresh GPS · no active order</small></div><div><span>ACTIVE DISPATCHES</span><strong>{active.filter(o=>o.deviceId).length+legacy.length}</strong><small>Assigned company work</small></div><div><span>AWAITING DRIVER</span><strong>{active.filter(o=>o.status==="queued").length}</strong><small>Saved requests in your queue</small></div></div>
        {office.loading&&<p className="office-note" aria-live="polite">Opening your saved office records…</p>}
        {!data.settings.location&&<div className="office-setup-prompt"><MapPin size={20}/><p><strong>Set your main office location</strong><span>Use a searched place or checked map pin as your default collection point.</span></p><button onClick={()=>setSettingsOpen(true)}>Locate office <ArrowRight size={15}/></button></div>}
        {view==="dispatch"&&<><div className="office-section-heading"><h2><Radio size={19}/> Live operations map</h2><span>Feed updated {fleet.refreshed?new Date(fleet.refreshed).toLocaleTimeString():"—"}</span></div>{monitor}<div className="office-desk-grid"><section><div className="office-section-heading"><h2>Active delivery desk <span>{active.length+legacy.length}</span></h2><button onClick={()=>navigate("deliveries")}>All deliveries <ArrowRight size={14}/></button></div>{cards(active)}{legacy.map(dispatch=>{const device=drivers.find(d=>d.id===dispatch.deviceId);return device?<DispatchProgress key={dispatch.id} dispatch={dispatch} device={device} onChanged={refresh}/>:null;})}{!active.length&&!legacy.length&&<div className="office-empty"><Package size={33}/><h3>No active delivery requests</h3><p>Your linked drivers are ready to appear here when you assign a real collection.</p><button className="tracking-primary" onClick={()=>setNewOrder("auto")}><Plus size={16}/> Create a delivery</button></div>}</section><FleetAlerts alerts={fleet.alerts} notifications={fleet.notifications} onNotifications={()=>void fleet.toggleNotifications()}/></div></>}
        {view==="deliveries"&&<section><div className="office-section-heading"><div className="office-tabs">{(["open","all","history"] as const).map(next=><button key={next} className={filter===next?"active":""} onClick={()=>setFilter(next)}>{next==="open"?"Open requests":next==="all"?"All recent orders":"Completed & cancelled"}</button>)}</div><button className="office-secondary" disabled={!shownOrders.length} onClick={()=>download("routeforge-orders.csv",orderCsv(shownOrders))}><Download size={15}/> Export CSV</button></div><div className="office-order-list">{cards(shownOrders)}</div>{!shownOrders.length&&<div className="office-empty"><Package size={32}/><h3>No requests in this view</h3><p>Saved orders will stay here across refreshes. Your historic planner data is preserved in Saved plans.</p><button className="tracking-primary" onClick={()=>setNewOrder("auto")}>New delivery <Plus size={15}/></button></div>}<p className="office-note">Showing up to 500 recent records, with all open requests first. Mileage and suggested pay are estimates.</p></section>}
        {view==="fleet"&&<><div className="office-section-heading"><h2>Company drivers & vehicles</h2><a className="office-secondary" href="/tracking" target="_top"><Plus size={15}/> Onboard a driver</a></div><div className="office-fleet-cards">{choices.map(choice=><article key={choice.device.id}><div><Truck size={24}/><span className={choice.available?"office-ready":"office-unavailable"}>{choice.reason}</span></div><h3>{choice.device.driverName}</h3><p>{choice.device.vehicleLabel||"Add vehicle / registration in details"}</p><small>{choice.profile?.ratePerKm==null?"Kilometre rate not set":`${money(choice.profile.ratePerKm)} per recorded km`}</small><div><button className="office-secondary" onClick={()=>setDetailsId(choice.device.id)}><UserRound size={15}/> Driver details</button><button className="tracking-primary" disabled={!choice.available} onClick={()=>setNewOrder(choice.device.id)}><Send size={15}/> Dispatch</button></div></article>)}</div>{monitor}{!drivers.length&&<p className="office-note">Pair a company phone to register a driver. Sample vehicles are not included.</p>}</>}
        {view==="partners"&&<section><div className="office-section-heading"><h2>Registered shops & collection points <span>{data.partners.filter(p=>p.active).length}</span></h2><button className="tracking-primary" onClick={()=>setPartnerOpen(true)}><Plus size={16}/> Add destination</button></div><div className="office-partner-grid">{data.partners.map(partner=><article key={partner.id} className={partner.active?"":"inactive"}><Store size={25}/><h3>{partner.name}</h3><p>{partner.location.address}</p><small>{partner.location.lat.toFixed(6)}, {partner.location.lng.toFixed(6)}</small><p>{partner.contact}{partner.phone?` · ${partner.phone}`:""}</p><div>{phoneLink(partner.phone)&&<a className="office-secondary" href={phoneLink(partner.phone)!}><Phone size={14}/> Call</a>}<button className="office-secondary" disabled={busyId===partner.id} onClick={()=>void togglePartner(partner.id,!partner.active)}>{partner.active?"Pause destination":"Reactivate"}</button><a className="office-inline-button" href={`https://www.google.com/maps/search/?api=1&query=${partner.location.lat},${partner.location.lng}`} target="_blank" rel="noreferrer">View location ↗</a></div></article>)}</div>{!data.partners.length&&<div className="office-empty"><Store size={34}/><h3>Register your first partner shop</h3><p>Partner locations appear immediately in collection and destination suggestions.</p><button className="tracking-primary" onClick={()=>setPartnerOpen(true)}>Add a destination <Plus size={15}/></button></div>}</section>}
        {view==="plans"&&<section><div className="office-section-heading"><h2>Saved scenarios</h2><div><label className="office-checkbox"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Include archived</label><button className="office-secondary" onClick={()=>void refreshArchive()}><RefreshCw size={14}/> Refresh</button></div></div>{archiveError&&<p role="alert" className="office-error">{archiveError}</p>}{archive.plans.filter(p=>archived||!p.archivedAt).map(plan=><article key={plan.id} className="office-archive-card"><FolderClock size={23}/><div><strong>{plan.name}</strong><small>{plan.scenario.deliveries.length} planned stops · {new Date(plan.updatedAt).toLocaleString()}</small></div><button className="office-secondary" onClick={()=>setArchivePlan(plan)}>View real map</button><button className="office-secondary" onClick={()=>download("routeforge-plan-manifest.csv",routeCsv(plan.result))}><Download size={14}/> CSV</button><button className="office-inline-button" disabled={busyId===plan.id} onClick={()=>void archiveAction(plan)}>{plan.archivedAt?"Restore":"Archive"}</button></article>)}{!archive.plans.length&&<div className="office-empty"><FolderClock size={30}/><h3>No saved plans</h3><p>New operational requests are saved automatically in Deliveries.</p><button className="office-secondary" onClick={()=>navigate("dispatch")}>Back to dispatch <ArrowRight size={15}/></button></div>}<h2 className="office-history-title">Previous optimizer runs</h2>{archive.runs.map(run=><article className="office-archive-card" key={run.id}><FolderClock size={20}/><div><strong>{run.name}</strong><small>{new Date(run.createdAt).toLocaleString()} · {run.result.assigned} planned stops · {run.result.distanceKm.toFixed(1)} km estimate</small></div><button className="office-secondary" onClick={()=>download("routeforge-historical-manifest.csv",routeCsv(run.result))}><Download size={14}/> Manifest</button></article>)}<p className="office-note">Planning archive vehicles and stops do not register company drivers or create active orders.</p></section>}
        <footer className="office-footer"><span><i/> Private company records · SHADOWNET</span><span>Tracking refreshes about every 10 seconds</span></footer>
      </>}
    </section>
    {trackerOpen&&<OfficeModal title="Live fleet tracking" wide onClose={()=>setTrackerOpen(false)}>{signedIn?monitor:<p className="office-note">Sign in to view your private drivers.</p>}<div className="office-form-actions"><a className="office-secondary" href="/tracking" target="_top">Full history & device setup ↗</a><button className="tracking-primary" onClick={()=>{setTrackerOpen(false);navigate("dispatch");}}>Return to dispatch</button></div></OfficeModal>}
    {newOrder!==null&&office.data&&<NewOrderForm data={data} devices={fleet.devices} dispatches={fleet.dispatches} initialDriver={newOrder} previous={previousLocations as Place[]} onChanged={refresh} onClose={()=>setNewOrder(null)}/>}
    {assignedOrder&&office.data&&<AssignOrderForm order={assignedOrder} data={data} devices={fleet.devices} dispatches={fleet.dispatches} onChanged={refresh} onClose={()=>setAssignId(null)}/>}
    {driverDetails&&<DriverDetails key={driverDetails.id} device={driverDetails} profile={data.profiles.find(p=>p.deviceId===driverDetails.id)} dispatches={fleet.dispatches} onChanged={refresh} onClose={()=>setDetailsId(null)}/>}
    {partnerOpen&&office.data&&<PartnerForm data={data} devices={fleet.devices} onChanged={refresh} onClose={()=>setPartnerOpen(false)}/>}
    {settingsOpen&&office.data&&<OfficeSettingsForm data={data} devices={fleet.devices} onChanged={refresh} onClose={()=>setSettingsOpen(false)}/>}
    {archivePlan&&<OfficeModal title={`Archived plan: ${archivePlan.name}`} wide onClose={()=>setArchivePlan(null)}><p className="office-note">These are archived planning pins, not active company vehicles or assigned deliveries.</p><JourneyMap points={[]} latest={null} focusPlace={archivePlan.scenario.depot} destinations={archivePlan.scenario.deliveries.map(p=>({...p,arrivedAt:null,deliveredAt:null}))}/></OfficeModal>}
    {guideOpen&&<OfficeModal title="From collection to delivery" onClose={()=>setGuideOpen(false)}><div className="office-guide"><p>Set your main office location and register the shops you work with. Existing paired phones are your company fleet.</p><ol><li>Create a collection with a pickup and destination. Select a place suggestion or verify its map pin.</li><li>Use automatic assignment for a free driver with live GPS, or manually choose another available company driver.</li><li>Follow the driver on the office map. When GPS confirms arrival at pickup, confirm collection.</li><li>After arrival at the destination, confirm delivery. The driver is released for another order.</li><li>Review recorded GPS mileage, missing segments and the agreed kilometre rate before paying. No payment runs automatically.</li></ol><p>Live tracking opens the driver column and map in a popup. The full tracker keeps journey history and phone onboarding. The installed app continues recording; destination guidance on the phone is a later update.</p></div></OfficeModal>}
  </main>;
}
