package app.shadownet.routeforge.driver;
import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.webkit.JavascriptInterface;
import android.webkit.JsResult;
import android.webkit.WebChromeClient;
import android.webkit.WebResourceRequest;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;

/** Only the packaged, offline UI is bridged. No credentials are exposed to JavaScript. */
public final class MainActivity extends Activity {
 private WebView web;private boolean busy=false,ready=false;private final Handler handler=new Handler(Looper.getMainLooper());
 private final ExecutorService work=Executors.newSingleThreadExecutor(),poll=Executors.newSingleThreadExecutor();
 private final AtomicBoolean stateFetching=new AtomicBoolean();
 private final Runnable update=new Runnable(){public void run(){publish();if(Session.loggedIn(MainActivity.this)&&!TrackingService.running&&stateFetching.compareAndSet(false,true))poll.execute(()->{try{DriverApi.poll(getApplicationContext());}finally{stateFetching.set(false);}});handler.postDelayed(this,1000);}};
 @Override public void onCreate(Bundle saved){super.onCreate(saved);if(!Session.loggedIn(this))stopService(new Intent(this,TrackingService.class));DriverAlerts.channels(this);getWindow().setStatusBarColor(Color.rgb(8,16,32));getWindow().setNavigationBarColor(Color.rgb(8,16,32));web=new WebView(this);web.setBackgroundColor(Color.rgb(8,16,32));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(android.webkit.WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.getSettings().setDomStorageEnabled(false);web.getSettings().setUserAgentString(web.getSettings().getUserAgentString()+" RouteForgeRider/1.2 (+"+Session.API+")");web.addJavascriptInterface(new Bridge(),"Rider");web.setWebChromeClient(new WebChromeClient(){@Override public boolean onJsConfirm(WebView view,String url,String message,JsResult result){new AlertDialog.Builder(MainActivity.this).setTitle("Confirm delivery").setMessage(message).setNegativeButton("Back",(d,w)->result.cancel()).setPositiveButton("Confirm",(d,w)->result.confirm()).setOnCancelListener(d->result.cancel()).show();return true;}});web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return true;}@Override public void onPageFinished(WebView view,String url){ready=true;publish();openTab(getIntent());}});setContentView(web);try(java.io.InputStream input=getAssets().open("rider.html")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] chunk=new byte[4096];int n;while((n=input.read(chunk))!=-1)out.write(chunk,0,n);web.loadDataWithBaseURL(Session.API+"/rider-native/",out.toString("UTF-8"),"text/html","UTF-8",null);}catch(Exception ignored){Session.error(this,"Could not load the packaged rider interface.");}}
 private void publish(){if(!ready)return;try{JSONObject session=Session.get(this);JSONObject state=new JSONObject().put("paired",Session.loggedIn(this)).put("username",Session.loggedIn(this)?session.optString("username"):"").put("unlinkPending",Session.pendingUnlink(this)!=null).put("driver",Session.loggedIn(this)?Session.prefs(this).getString("driver",""):"").put("recording",TrackingService.running).put("gpsEnabled",DriverApi.gpsEnabled(this)).put("lastFix",Session.prefs(this).getLong("last_fix",0)).put("lastSync",Session.prefs(this).getLong("last_sync",0)).put("events",EventQueue.get(this).count()).put("commands",Session.loggedIn(this)?EventQueue.get(this).commands():new JSONArray()).put("savedReports",EventQueue.get(this).commandCount()).put("canStop",DriverApi.canStop(this)).put("error",Session.prefs(this).getString("error","")).put("stateError",Session.prefs(this).getString("state_error","")).put("alertsError",Session.prefs(this).getString("alerts_error","")).put("alerts",DriverAlerts.status(this)).put("busy",busy).put("data",Session.loggedIn(this)?DriverApi.cached(this):new JSONObject());String point=Session.prefs(this).getString("last_point",null);if(Session.loggedIn(this)&&point!=null)state.put("point",new JSONObject(point));web.evaluateJavascript("applyState("+state.toString().replace("\u2028","\\u2028").replace("\u2029","\\u2029")+")",null);}catch(Exception ignored){}}
 private void background(Runnable task){if(busy)return;busy=true;publish();work.execute(()->{try{task.run();}finally{runOnUiThread(()->{busy=false;publish();});}});}
 private void startDuty(){if(!Session.loggedIn(this)){Session.error(this,"Sign in with your rider account first.");publish();return;}
  ArrayList<String> permissions=new ArrayList<>();if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){permissions.add(Manifest.permission.ACCESS_COARSE_LOCATION);permissions.add(Manifest.permission.ACCESS_FINE_LOCATION);}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.POST_NOTIFICATIONS);
  if(!permissions.isEmpty()){requestPermissions(permissions.toArray(new String[0]),9);return;}try{Session.error(this,"");startForegroundService(new Intent(this,TrackingService.class));}catch(Exception ignored){Session.error(this,"Could not start duty. Open Android permission settings and retry.");}publish();
 }
 @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==9){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED&&(Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED))startDuty();else Session.error(this,"Allow precise location and notifications in Android settings to start duty.");publish();}}
 private void stopDuty(boolean privacy){
  if(privacy){try{DriverApi.enqueue(this,new JSONObject().put("action","pause"));}catch(Exception ignored){}Session.prefs(this).edit().putBoolean("duty",false).apply();stopService(new Intent(this,TrackingService.class));SyncJob.retry(this);publish();return;}
  if(!DriverApi.canStop(this)){Session.error(this,"Finish the current delivery before ending duty. Privacy pause is always available.");publish();return;}
  background(()->{try{JSONObject session=Session.get(this);if(session==null)return;JSONObject command=new JSONObject().put("action","stop_duty").put("operationId",UUID.randomUUID().toString());JSONObject assignment=DriverApi.cached(this).optJSONObject("assignment");boolean localDone=DriverApi.completedLocally(this,assignment);
   if(localDone||EventQueue.get(this).commandCount()>0)EventQueue.get(this).addCommand(session.getString("deviceId"),command);else Api.post("/api/driver/actions",command,session.getString("token"),12000);
   Session.prefs(this).edit().putBoolean("duty",false).apply();runOnUiThread(()->stopService(new Intent(this,TrackingService.class)));SyncJob.retry(this);DriverApi.flush(this);DriverApi.poll(this);
  }catch(Exception e){Session.error(this,e instanceof Api.Rejected?e.getMessage():"Connect to confirm duty has ended, or use Privacy pause now.");}});
 }
 private void finishSignOut(int attempt){if(TrackingService.running){if(attempt>=20){Session.error(this,"Recording is still stopping. Retry sign-out in a moment.");publish();return;}handler.postDelayed(()->finishSignOut(attempt+1),100);return;}background(()->{try{if(!DriverApi.flush(this)||!Api.sync(this)||EventQueue.get(this).commandCount()>0||EventQueue.get(this).count()>0)throw new IllegalStateException("Connect and sync saved reports before signing out. Duty is paused.");JSONObject session=Session.get(this);if(session==null)return;Api.post("/api/driver/logout",new JSONObject(),session.getString("token"),12000);Session.clear(this);}catch(Exception e){Session.error(this,e instanceof Api.Rejected||e instanceof IllegalStateException?e.getMessage():"Sign-out needs a connection. Duty is paused; saved reports stay on this phone.");}});}
 public final class Bridge {
  @JavascriptInterface public void login(String username,String password,boolean agreed){runOnUiThread(()->{if(!agreed){Session.error(MainActivity.this,"Agree to location sharing while on duty before signing in.");publish();return;}if(Session.loggedIn(MainActivity.this)||Session.pendingUnlink(MainActivity.this)!=null)return;background(()->{try{JSONObject input=new JSONObject().put("username",username.trim()).put("password",password).put("deviceName",Build.MANUFACTURER+" "+Build.MODEL).put("appVersion",4);if(EventQueue.get(MainActivity.this).count()>0||EventQueue.get(MainActivity.this).commandCount()>0){String previous=Session.queueOwner(MainActivity.this);if(previous.isEmpty())throw new IllegalStateException("The saved queue has no rider identity. Review it with the office before clearing it.");input.put("previousDeviceId",previous);}JSONObject response=Api.post("/api/driver/login",input,null,20000);Session.save(MainActivity.this,response);SyncJob.schedule(MainActivity.this);DriverApi.flush(MainActivity.this);Api.sync(MainActivity.this);DriverApi.poll(MainActivity.this);}catch(Exception e){Session.error(MainActivity.this,e instanceof Api.Rejected||e instanceof IllegalStateException?e.getMessage():"Could not sign in. Check your connection and retry.");}});});}
  @JavascriptInterface public void logout(){runOnUiThread(()->{if(busy||!Session.loggedIn(MainActivity.this))return;if(!DriverApi.canStop(MainActivity.this)){Session.error(MainActivity.this,"Finish delivery before signing out. Privacy pause is always available.");publish();return;}new AlertDialog.Builder(MainActivity.this).setTitle("Sign out of your rider account?").setMessage("Duty ends and saved reports sync first. Uploaded history stays with your rider account.").setNegativeButton("Stay signed in",null).setPositiveButton("Sign out",(d,w)->{Session.prefs(MainActivity.this).edit().putBoolean("duty",false).apply();stopService(new Intent(MainActivity.this,TrackingService.class));finishSignOut(0);}).show();});}
  @JavascriptInterface public void start(){runOnUiThread(MainActivity.this::startDuty);}
  @JavascriptInterface public void stop(){runOnUiThread(()->stopDuty(false));}
  @JavascriptInterface public void privacy(){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Pause location sharing?").setMessage("GPS stops immediately. Any unfinished delivery stays open for office follow-up; it is not marked delivered or paid.").setNegativeButton("Keep sharing",null).setPositiveButton("Pause GPS",(d,w)->stopDuty(true)).show());}
  @JavascriptInterface public void sync(){runOnUiThread(()->background(()->{DriverApi.flush(MainActivity.this);Api.sync(MainActivity.this);DriverApi.poll(MainActivity.this);}));}
  @JavascriptInterface public void settings(){runOnUiThread(()->startActivity(new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS)));}
  @JavascriptInterface public void permissions(){runOnUiThread(()->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))));}
  @JavascriptInterface public void alertSettings(String kind){runOnUiThread(()->startActivity(new Intent(Settings.ACTION_CHANNEL_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()).putExtra(Settings.EXTRA_CHANNEL_ID,"assignments".equals(kind)?DriverAlerts.ASSIGNMENTS:DriverAlerts.OFFERS)));}
  @JavascriptInterface public void testAlert(){runOnUiThread(()->DriverAlerts.test(MainActivity.this));}
  @JavascriptInterface public void action(String raw){runOnUiThread(()->background(()->{try{JSONObject input=new JSONObject(raw);String action=input.optString("action");if(!action.equals("accept")&&!action.equals("collected")&&!action.equals("delivered")&&!action.equals("payment"))throw new IllegalArgumentException("Unknown rider action.");if(action.equals("accept")){if(DriverApi.hasActive(MainActivity.this))throw new IllegalStateException("Finish your active delivery before claiming another.");if(!TrackingService.running||!DriverApi.gpsEnabled(MainActivity.this))throw new IllegalStateException("Go on duty with GPS enabled before claiming a delivery.");JSONObject session=Session.get(MainActivity.this);if(session==null)return;input.put("operationId",UUID.randomUUID().toString());Api.post("/api/driver/actions",input,session.getString("token"),12000);}else{DriverApi.enqueue(MainActivity.this,input);DriverApi.flush(MainActivity.this);}DriverApi.poll(MainActivity.this);}catch(Exception e){Session.error(MainActivity.this,e instanceof Api.Rejected||e instanceof IllegalStateException?e.getMessage():"Delivery action could not be confirmed. Saved reports are safe. Connect and retry; do not submit a second payment.");}}));}
  @JavascriptInterface public void discard(String id){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Discard rejected report?").setMessage("This removes a rejected local action, not a completed server record. Check with the office before deleting a payment report.").setNegativeButton("Keep",null).setPositiveButton("Discard",(d,w)->{EventQueue.get(MainActivity.this).commandDone(id);publish();SyncJob.retry(MainActivity.this);}).show());}
  @JavascriptInterface public void unlink(){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Unlink rider phone and clear queue?").setMessage("This ends duty and deletes "+EventQueue.get(MainActivity.this).count()+" unsent GPS events and "+EventQueue.get(MainActivity.this).commandCount()+" local delivery reports. Uploaded history stays in the office. Any unfinished assignment is cancelled for office follow-up. If offline, the unlink request retries securely when connected.").setNegativeButton("Keep link",null).setPositiveButton("Unlink",(d,w)->{Session.prefs(MainActivity.this).edit().putBoolean("duty",false).apply();stopService(new Intent(MainActivity.this,TrackingService.class));background(()->{try{DriverApi.clearLink(MainActivity.this);}catch(Exception ignored){Session.error(MainActivity.this,"Could not save the unlink request. The phone link has been retained.");}});}).show());}
  @JavascriptInterface public void navigate(){runOnUiThread(()->{try{JSONObject a=DriverApi.cached(MainActivity.this).optJSONObject("assignment");if(a==null)return;JSONArray stops=a.getJSONArray("stops");for(int i=0;i<stops.length();i++){JSONObject stop=stops.getJSONObject(i);if(!stop.isNull("deliveredAt"))continue;double lat=stop.getDouble("lat"),lng=stop.getDouble("lng");if(!Double.isFinite(lat)||!Double.isFinite(lng)||Math.abs(lat)>85||Math.abs(lng)>180)return;startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/dir/?api=1&destination="+lat+","+lng+"&travelmode=driving")));break;}}catch(Exception ignored){Session.error(MainActivity.this,"A navigation app could not be opened.");publish();}});}
 }
 private void openTab(Intent intent){String tab=intent.getStringExtra("tab");if(ready&&(tab!=null)&&(tab.equals("home")||tab.equals("offers")||tab.equals("route")||tab.equals("account")))web.evaluateJavascript("go("+JSONObject.quote(tab)+")",null);}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);publish();openTab(intent);poll.execute(()->DriverApi.poll(getApplicationContext()));}
 @Override protected void onResume(){super.onResume();handler.post(update);}
 @Override protected void onPause(){handler.removeCallbacks(update);super.onPause();}
 @Override protected void onDestroy(){handler.removeCallbacks(update);work.shutdown();poll.shutdown();web.removeJavascriptInterface("Rider");web.destroy();super.onDestroy();}
}
