package app.shadownet.routeforge.driver;
import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.webkit.JavascriptInterface;
import android.webkit.JsResult;
import android.webkit.WebChromeClient;
import android.webkit.WebResourceRequest;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;

/** Only the packaged, offline UI is bridged. No credentials are exposed to JavaScript. */
public final class MainActivity extends Activity {
 private WebView web;private boolean busy=false,ready=false;private final Handler handler=new Handler(Looper.getMainLooper());
 private final ExecutorService work=Executors.newSingleThreadExecutor(),poll=Executors.newSingleThreadExecutor(),roads=Executors.newSingleThreadExecutor();
 private final AtomicBoolean stateFetching=new AtomicBoolean(),routeQueued=new AtomicBoolean();
 private final Runnable update=new Runnable(){public void run(){publish();if(Session.loggedIn(MainActivity.this)&&!TrackingService.running&&stateFetching.compareAndSet(false,true))poll.execute(()->{try{DriverApi.poll(getApplicationContext());}finally{stateFetching.set(false);}});handler.postDelayed(this,1000);}};
 @Override public void onCreate(Bundle saved){super.onCreate(saved);if(!Session.loggedIn(this))stopService(new Intent(this,TrackingService.class));DriverAlerts.channels(this);roads.execute(()->{try{OfflineRoads.installBundle(getApplicationContext());}catch(Exception ignored){}});work.execute(()->UpdateApi.check(getApplicationContext(),false));getWindow().setStatusBarColor(Color.rgb(8,16,32));getWindow().setNavigationBarColor(Color.rgb(8,16,32));web=new WebView(this);web.setBackgroundColor(Color.rgb(8,16,32));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(android.webkit.WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.getSettings().setDomStorageEnabled(false);web.getSettings().setUserAgentString(web.getSettings().getUserAgentString()+" RouteForgeRider/"+UpdateApi.installedName(this)+" (+"+Session.API+")");web.addJavascriptInterface(new Bridge(),"Rider");web.setWebChromeClient(new WebChromeClient(){@Override public boolean onJsConfirm(WebView view,String url,String message,JsResult result){new AlertDialog.Builder(MainActivity.this).setTitle("Confirm delivery").setMessage(message).setNegativeButton("Back",(d,w)->result.cancel()).setPositiveButton("Confirm",(d,w)->result.confirm()).setOnCancelListener(d->result.cancel()).show();return true;}});web.setWebViewClient(new WebViewClient(){@Override public android.webkit.WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){return OfflineMaps.tile(getApplicationContext(),request.getUrl().toString());}@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return true;}@Override public void onPageFinished(WebView view,String url){ready=true;publish();openTab(getIntent());}});setContentView(web);try(java.io.InputStream input=getAssets().open("rider.html")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] chunk=new byte[4096];int n;while((n=input.read(chunk))!=-1)out.write(chunk,0,n);web.loadDataWithBaseURL(Session.API+"/rider-native/",out.toString("UTF-8"),"text/html","UTF-8",null);}catch(Exception ignored){Session.error(this,"Could not load the packaged rider interface.");}}
 private void publish(){if(!ready)return;try{JSONObject session=Session.get(this);boolean signedIn=session!=null&&session.optBoolean("loggedIn",false);JSONObject state=new JSONObject().put("appVersionName",UpdateApi.installedName(this)).put("paired",signedIn).put("username",signedIn?session.optString("username"):"").put("unlinkPending",Session.pendingUnlink(this)!=null).put("driver",signedIn?Session.prefs(this).getString("driver",""):"").put("recording",TrackingService.running).put("gpsEnabled",DriverApi.gpsEnabled(this)).put("gpsIssue",Session.prefs(this).getString("gps_issue","")).put("lastFix",Session.prefs(this).getLong("last_fix",0)).put("lastSync",Session.prefs(this).getLong("last_sync",0)).put("events",EventQueue.get(this).count()).put("commands",signedIn?EventQueue.get(this).commands():new JSONArray()).put("savedReports",EventQueue.get(this).commandCount()).put("canStop",DriverApi.canStop(this)).put("error",Session.prefs(this).getString("error","")).put("stateError",Session.prefs(this).getString("state_error","")).put("alertsError",Session.prefs(this).getString("alerts_error","")).put("alerts",DriverAlerts.status(this)).put("busy",busy).put("roadRoutes",signedIn?RoadApi.cached(this):new JSONArray()).put("roadLoading",signedIn&&RoadApi.loading()).put("roadProgress",signedIn?OfflineRoads.progress:"").put("roadIssue",signedIn?RoadApi.issue(this):new JSONObject()).put("data",signedIn?DriverApi.cached(this):new JSONObject());JSONObject journey=signedIn?EventQueue.get(this).journey(session.getString("deviceId")):new JSONObject();state.put("journey",journey).put("history",signedIn?JourneyApi.cached(this):new JSONObject()).put("maps",signedIn?OfflineMaps.state(this):new JSONObject()).put("update",UpdateApi.cached(this));String point=Session.prefs(this).getString("last_point",null);if(signedIn&&point!=null)state.put("point",new JSONObject(point));web.evaluateJavascript("applyState("+state.toString().replace("\u2028","\\u2028").replace("\u2029","\\u2029")+")",null);autoRoads();}catch(Exception ignored){}}
 private void autoRoads(){if(!Session.loggedIn(this)||!TrackingService.running||OfflineMaps.downloading||RoadApi.loading()||!routeQueued.compareAndSet(false,true))return;JSONObject a=DriverApi.cached(this).optJSONObject("assignment"),stop=a==null?null:DriverApi.nextStop(this,a);if(a==null||stop==null){routeQueued.set(false);return;}roads.execute(()->{try{if(RoadApi.fetch(getApplicationContext(),a.optString("id"),stop.optString("id"),false))runOnUiThread(MainActivity.this::publish);}finally{routeQueued.set(false);}});}
 private void background(Runnable task){if(busy)return;busy=true;publish();work.execute(()->{try{task.run();}finally{runOnUiThread(()->{busy=false;publish();});}});}
 private void startDuty(){if(!Session.loggedIn(this)){Session.error(this,"Sign in with your rider account first.");publish();return;}
  ArrayList<String> permissions=new ArrayList<>();if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){permissions.add(Manifest.permission.ACCESS_COARSE_LOCATION);permissions.add(Manifest.permission.ACCESS_FINE_LOCATION);}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.POST_NOTIFICATIONS);
  if(!permissions.isEmpty()){requestPermissions(permissions.toArray(new String[0]),9);return;}try{Session.error(this,"");startForegroundService(new Intent(this,TrackingService.class));}catch(Exception ignored){Session.error(this,"Could not start duty. Open Android permission settings and retry.");}publish();
 }
 @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==9){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED&&(Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED))startDuty();else Session.error(this,"Allow precise location and notifications in Android settings to start duty.");publish();}}
 private void stopDuty(boolean privacy){
  OfflineRoads.cancel();
  if(privacy){try{DriverApi.enqueue(this,new JSONObject().put("action","pause"));}catch(Exception ignored){}Session.prefs(this).edit().putBoolean("duty",false).apply();stopService(new Intent(this,TrackingService.class));SyncJob.retry(this);publish();return;}
  if(!DriverApi.canStop(this)){Session.error(this,"Finish the current delivery before ending duty. Privacy pause is always available.");publish();return;}
  background(()->{try{JSONObject session=Session.get(this);if(session==null)return;JSONObject command=new JSONObject().put("action","stop_duty").put("operationId",UUID.randomUUID().toString());JSONObject assignment=DriverApi.cached(this).optJSONObject("assignment");boolean localDone=DriverApi.completedLocally(this,assignment);
   if(localDone||EventQueue.get(this).commandCount()>0)EventQueue.get(this).addCommand(session.getString("deviceId"),command);else Api.post("/api/driver/actions",command,session.getString("token"),12000);
   Session.prefs(this).edit().putBoolean("duty",false).apply();runOnUiThread(()->stopService(new Intent(this,TrackingService.class)));SyncJob.retry(this);DriverApi.flush(this);DriverApi.poll(this);
  }catch(Exception e){Session.error(this,e instanceof Api.Rejected?e.getMessage():"Connect to confirm duty has ended, or use Privacy pause now.");}});
 }
 private void finishSignOut(int attempt){if(TrackingService.running){if(attempt>=20){Session.error(this,"Recording is still stopping. Retry sign-out in a moment.");publish();return;}handler.postDelayed(()->finishSignOut(attempt+1),100);return;}background(()->{try{if(!DriverApi.flush(this)||!Api.sync(this)||EventQueue.get(this).commandCount()>0||EventQueue.get(this).count()>0)throw new IllegalStateException("Connect and sync saved reports before signing out. Duty is paused.");JSONObject session=Session.get(this);if(session==null)return;Api.post("/api/driver/logout",new JSONObject(),session.getString("token"),12000);Session.clear(this);}catch(Exception e){Session.error(this,e instanceof Api.Rejected||e instanceof IllegalStateException?e.getMessage():"Sign-out needs a connection. Duty is paused; saved reports stay on this phone.");}});}
 public final class Bridge {
  @JavascriptInterface public void login(String username,String password,boolean agreed){runOnUiThread(()->{if(!agreed){Session.error(MainActivity.this,"Agree to location sharing while on duty before signing in.");publish();return;}if(Session.loggedIn(MainActivity.this)||Session.pendingUnlink(MainActivity.this)!=null)return;background(()->{try{JSONObject input=new JSONObject().put("username",username.trim()).put("password",password).put("deviceName",Build.MANUFACTURER+" "+Build.MODEL).put("appVersion",UpdateApi.installedVersion(MainActivity.this));if(EventQueue.get(MainActivity.this).count()>0||EventQueue.get(MainActivity.this).commandCount()>0){String previous=Session.queueOwner(MainActivity.this);if(previous.isEmpty())throw new IllegalStateException("The saved queue has no rider identity. Review it with the office before clearing it.");input.put("previousDeviceId",previous);}JSONObject response=Api.post("/api/driver/login",input,null,20000);Session.save(MainActivity.this,response);SyncJob.schedule(MainActivity.this);DriverApi.flush(MainActivity.this);Api.sync(MainActivity.this);DriverApi.poll(MainActivity.this);}catch(Exception e){Session.error(MainActivity.this,e instanceof Api.Rejected||e instanceof IllegalStateException?e.getMessage():"Could not sign in. Check your connection and retry.");}});});}
  @JavascriptInterface public void logout(){runOnUiThread(()->{if(busy||!Session.loggedIn(MainActivity.this))return;if(!DriverApi.canStop(MainActivity.this)){Session.error(MainActivity.this,"Finish delivery before signing out. Privacy pause is always available.");publish();return;}new AlertDialog.Builder(MainActivity.this).setTitle("Sign out of your rider account?").setMessage("Duty ends and saved reports sync first. Uploaded history stays with your rider account.").setNegativeButton("Stay signed in",null).setPositiveButton("Sign out",(d,w)->{Session.prefs(MainActivity.this).edit().putBoolean("duty",false).apply();stopService(new Intent(MainActivity.this,TrackingService.class));finishSignOut(0);}).show();});}
  @JavascriptInterface public void start(){runOnUiThread(MainActivity.this::startDuty);}
  @JavascriptInterface public void stop(){runOnUiThread(()->stopDuty(false));}
  @JavascriptInterface public void privacy(){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Pause location sharing?").setMessage("GPS stops immediately. Any unfinished delivery stays open for office follow-up; it is not marked delivered or paid.").setNegativeButton("Keep sharing",null).setPositiveButton("Pause GPS",(d,w)->stopDuty(true)).show());}
  @JavascriptInterface public void sync(){runOnUiThread(()->background(()->{DriverApi.flush(MainActivity.this);Api.sync(MainActivity.this);DriverApi.poll(MainActivity.this);}));}
  @JavascriptInterface public void settings(){runOnUiThread(()->startActivity(new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS)));}
  @JavascriptInterface public void permissions(){runOnUiThread(()->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))));}
  @JavascriptInterface public void alertSettings(String kind){runOnUiThread(()->startActivity(new Intent(Settings.ACTION_CHANNEL_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()).putExtra(Settings.EXTRA_CHANNEL_ID,"assignments".equals(kind)?DriverAlerts.ASSIGNMENTS:DriverAlerts.OFFERS)));}
  @JavascriptInterface public void testAlert(){runOnUiThread(()->DriverAlerts.test(MainActivity.this));}
  @JavascriptInterface public void action(String raw){runOnUiThread(()->background(()->{try{
   if(!Session.loggedIn(MainActivity.this))throw new IllegalStateException("Sign in with your rider account first.");
   JSONObject input=new JSONObject(raw);String action=input.optString("action");
   if(!action.equals("accept")&&!action.equals("decline")&&!action.equals("collected")&&!action.equals("delivered")&&!action.equals("payment"))throw new IllegalStateException("Unknown rider action.");
   Session.error(MainActivity.this,"");
   if(action.equals("accept")||action.equals("decline")){
    if(!DriverApi.liveOffer(MainActivity.this,input.optString("orderId")))throw new IllegalStateException("This offer is no longer available. Go on duty with GPS and refresh deliveries.");
    JSONObject session=Session.get(MainActivity.this);if(session==null)return;input.put("operationId",UUID.randomUUID().toString());
    Api.post("/api/driver/actions",input,session.getString("token"),12000);
   }else{
    JSONObject order=DriverApi.cached(MainActivity.this).optJSONObject("order");
    if(action.equals("delivered")&&order!=null&&order.optBoolean("requiresOtp",false)&&!input.optString("otp").matches("[0-9]{6}"))throw new IllegalStateException("Enter the six-digit customer delivery OTP.");
    if(action.equals("payment")&&order!=null&&order.optBoolean("network",false)&&order.optString("id").equals(input.optString("orderId")))throw new IllegalStateException("Merchant delivery charges are handled by the merchant. No payment is collected by this app.");
    if(action.equals("payment"))validatePayment(input);DriverApi.enqueue(MainActivity.this,input);DriverApi.flush(MainActivity.this);
   }
   DriverApi.poll(MainActivity.this);
  }catch(Exception e){Session.error(MainActivity.this,e instanceof Api.Rejected||e instanceof IllegalStateException?e.getMessage():"Delivery action could not be confirmed. Saved reports stay on this phone; connect and refresh before trying again.");}}));}
  private void validatePayment(JSONObject input)throws Exception{
   JSONObject data=DriverApi.cached(MainActivity.this),order=data.optJSONObject("order");if(order==null||!order.optString("id").equals(input.optString("orderId"))){order=null;JSONArray orders=data.optJSONArray("recentOrders");if(orders!=null)for(int i=0;i<orders.length();i++)if(orders.getJSONObject(i).optString("id").equals(input.optString("orderId")))order=orders.getJSONObject(i);}
   if(order==null)throw new IllegalStateException("Refresh this delivery before recording payment.");if(order.optJSONObject("source")!=null&&"supplier_to_hub".equals(order.getJSONObject("source").optString("purpose")))throw new IllegalStateException("Jumia hub pickups have no customer cash collection.");
   double amount=input.optDouble("amount",Double.NaN);if(!Double.isFinite(amount)||amount<0||amount>10000000||Math.abs(amount*100-Math.round(amount*100))>.000001)throw new IllegalStateException("Enter the exact amount with two decimal places or fewer.");String method=input.optString("method");long minor=Math.round(amount*100);
   if(!order.isNull("amountDue")&&order.has("amountDue")&&minor!=Math.round(order.getDouble("amountDue")*100))throw new IllegalStateException("The received total must match the expected payment. Ask the office to resolve any unpaid balance.");
   if(method.equals("mixed")){double cash=input.optDouble("cashAmount",Double.NaN),till=input.optDouble("tillAmount",Double.NaN);if(!Double.isFinite(cash)||!Double.isFinite(till)||cash<=0||till<=0||Math.abs(cash*100-Math.round(cash*100))>.000001||Math.abs(till*100-Math.round(till*100))>.000001||Math.round(cash*100)+Math.round(till*100)!=minor)throw new IllegalStateException("Enter cash and till amounts that add up to the exact total.");}
   else if(!method.equals("cash")&&!method.equals("till"))throw new IllegalStateException("Choose cash, till or cash + till.");if(!method.equals("cash")&&input.optString("reference").trim().isEmpty())throw new IllegalStateException("Add the till transaction reference.");
  }
  @JavascriptInterface public void history(String action,String kind,String id){runOnUiThread(()->background(()->{try{if(action.equals("list"))JourneyApi.list(MainActivity.this);else if(action.equals("view"))JourneyApi.view(MainActivity.this,kind,id);else if(action.equals("backup")){JourneyApi.requestBackup(MainActivity.this,kind,id);Api.sync(MainActivity.this);JourneyApi.flush(MainActivity.this);}else if(action.equals("restore"))JourneyApi.restore(MainActivity.this,kind,id);else if(action.equals("latest"))JourneyApi.latest(MainActivity.this);}catch(Exception e){Session.error(MainActivity.this,e instanceof Api.Rejected||e instanceof IllegalStateException?e.getMessage():"Journey action could not complete. Saved points remain on this phone; reconnect and retry.");}}));}
  @JavascriptInterface public void checkUpdate(){runOnUiThread(()->background(()->UpdateApi.check(MainActivity.this,true)));}
  @JavascriptInterface public void countyMap(String id){runOnUiThread(()->{if(OfflineMaps.downloading)return;new AlertDialog.Builder(MainActivity.this).setTitle("Download county roads?").setMessage("County roads use shared regional files. Nairobi/Kiambu roads are included. Other regions may use tens of MB. Downloads reuse maps already on this phone. Choose Wi-Fi if needed. This does not send rider or customer locations to the map server.").setNegativeButton("Later",null).setPositiveButton("Download",(d,w)->{Session.prefs(MainActivity.this).edit().putBoolean("roads_download_allowed",true).apply();roads.execute(()->{try{OfflineMaps.county(getApplicationContext(),id);}catch(Exception e){Session.error(getApplicationContext(),e instanceof IllegalStateException?e.getMessage():"Map download did not finish. Saved regions are retained; reconnect and retry.");}runOnUiThread(MainActivity.this::publish);});}).show();});}
  @JavascriptInterface public void kenyaMap(){runOnUiThread(()->{if(OfflineMaps.downloading)return;new AlertDialog.Builder(MainActivity.this).setTitle("Download Kenya offline basemap?").setMessage("About 320 MB, plus room to save the file. This map supplies streets and labels for all 47 counties and is shared by your county road packs. Use Wi-Fi. County road directions work without this optional map.").setNegativeButton("Later",null).setPositiveButton("Download",(d,w)->roads.execute(()->{try{OfflineMaps.basemap(getApplicationContext());}catch(Exception e){Session.error(getApplicationContext(),e instanceof IllegalStateException?e.getMessage():"Basemap download did not finish. Reconnect and try again.");}runOnUiThread(MainActivity.this::publish);})).show();});}
  @JavascriptInterface public void retryOtp(String id,String otp){runOnUiThread(()->background(()->{try{JSONObject session=Session.get(MainActivity.this);if(!Session.loggedIn(MainActivity.this)||session==null)throw new IllegalStateException("Sign in to the same rider account to correct your saved report.");EventQueue.get(MainActivity.this).correctOtp(session.getString("deviceId"),id,otp);SyncJob.retry(MainActivity.this);DriverApi.flush(MainActivity.this);DriverApi.poll(MainActivity.this);}catch(Exception e){Session.error(MainActivity.this,e instanceof IllegalStateException?e.getMessage():"Could not correct the saved report. Keep it and retry when connected.");}}));}
  @JavascriptInterface public void contactCustomer(){runOnUiThread(()->{try{
   if(!Session.loggedIn(MainActivity.this)||!DriverApi.hasActive(MainActivity.this))return;
   JSONObject data=DriverApi.cached(MainActivity.this),a=data.optJSONObject("assignment"),o=data.optJSONObject("order");
   if(a==null||o==null||!a.optString("orderId").equals(o.optString("id"))||DriverApi.completedLocally(MainActivity.this,a))return;
   JSONObject customer=o.optJSONObject("customer");if(customer==null)return;String phone=customer.optString("phone").replaceAll("[\\s()-]","");
   if(!phone.matches("\\+?[0-9]{7,15}"))throw new IllegalStateException("The assigned customer has no valid contact number. Ask the office or merchant for assistance.");
   startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone)));
  }catch(Exception e){Session.error(MainActivity.this,e instanceof IllegalStateException?e.getMessage():"A dialer could not be opened. Contact the office or merchant for assistance.");publish();}});}
  @JavascriptInterface public void cancelRoads(){RoadApi.pause(getApplicationContext());}
  @JavascriptInterface public void route(String dispatchId,String stopId,boolean force){if(!Session.loggedIn(MainActivity.this)||RoadApi.loading())return;if(force&&!Session.prefs(MainActivity.this).getBoolean("roads_download_allowed",false)){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Download road maps?").setMessage("The Nairobi region is about 34 MB. Other regions vary. Maps are saved on this phone for future rides and offline road directions. Your precise location and recipient details are not sent to the road-data service. Downloading uses your internet connection.").setNegativeButton("Later",null).setPositiveButton("Download",(dialog,which)->{Session.prefs(MainActivity.this).edit().putBoolean("roads_download_allowed",true).apply();route(dispatchId,stopId,true);}).show());return;}roads.execute(()->{if(RoadApi.fetch(getApplicationContext(),dispatchId,stopId,force))runOnUiThread(MainActivity.this::publish);});}
  @JavascriptInterface public void mapCredits(){runOnUiThread(()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.openstreetmap.org/copyright")));}catch(Exception ignored){}});}
  @JavascriptInterface public void updateApp(){runOnUiThread(()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(UpdateApi.downloadUrl(MainActivity.this))));}catch(Exception ignored){Session.error(MainActivity.this,"Open the RouteForge dashboard login page to download the latest rider update.");publish();}});}
  @JavascriptInterface public void discard(String id){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Discard rejected report?").setMessage("This removes a rejected local action, not a completed server record. Check with the office before deleting a payment report.").setNegativeButton("Keep",null).setPositiveButton("Discard",(d,w)->{EventQueue.get(MainActivity.this).commandDone(id);publish();SyncJob.retry(MainActivity.this);}).show());}
  @JavascriptInterface public void unlink(){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Unlink rider phone and clear queue?").setMessage("This ends duty and deletes "+EventQueue.get(MainActivity.this).count()+" unsent GPS events and "+EventQueue.get(MainActivity.this).commandCount()+" local delivery reports. Uploaded history stays in the office. Any unfinished assignment is cancelled for office follow-up. If offline, the unlink request retries securely when connected.").setNegativeButton("Keep link",null).setPositiveButton("Unlink",(d,w)->{Session.prefs(MainActivity.this).edit().putBoolean("duty",false).apply();stopService(new Intent(MainActivity.this,TrackingService.class));background(()->{try{DriverApi.clearLink(MainActivity.this);}catch(Exception ignored){Session.error(MainActivity.this,"Could not save the unlink request. The phone link has been retained.");}});}).show());}
  @JavascriptInterface public void navigate(){runOnUiThread(()->{try{if(!Session.loggedIn(MainActivity.this))return;JSONObject a=DriverApi.cached(MainActivity.this).optJSONObject("assignment");if(a==null)return;JSONObject stop=DriverApi.nextStop(MainActivity.this,a);if(stop==null)return;double lat=stop.getDouble("lat"),lng=stop.getDouble("lng");if(!Double.isFinite(lat)||!Double.isFinite(lng)||Math.abs(lat)>85||Math.abs(lng)>180)return;startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/dir/?api=1&destination="+lat+","+lng+"&travelmode="+(DriverApi.cached(MainActivity.this).optString("routingProfile").equals("cycling")?"bicycling":"driving"))));}catch(Exception ignored){Session.error(MainActivity.this,"A navigation app could not be opened.");publish();}});}
 }
 private void openTab(Intent intent){String tab=intent.getStringExtra("tab");if(ready&&(tab!=null)&&(tab.equals("home")||tab.equals("offers")||tab.equals("route")||tab.equals("account")))web.evaluateJavascript("go("+JSONObject.quote(tab)+")",null);}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);publish();openTab(intent);poll.execute(()->DriverApi.poll(getApplicationContext()));}
 @Override protected void onResume(){super.onResume();if(Session.loggedIn(this)&&Session.prefs(this).getBoolean("duty",false)&&!TrackingService.running)startDuty();handler.post(update);}
 @Override protected void onPause(){handler.removeCallbacks(update);super.onPause();}
 @Override protected void onDestroy(){handler.removeCallbacks(update);work.shutdown();poll.shutdown();roads.shutdown();web.removeJavascriptInterface("Rider");web.destroy();super.onDestroy();}
}
