import type { Board, Issue, Status } from "./board";
export function demoBoard(now = Date.now()): Board {
  const day = 86400000,
    date = (offset: number) =>
      new Date(now + offset * day).toISOString().slice(0, 10);
  const entries: [
    string,
    Status,
    number,
    Issue["kind"],
    Issue["priority"],
    Issue["assignee"],
    string[],
  ][] = [
    [
      "Build the product discovery experience",
      "doing",
      5,
      "story",
      "high",
      "alex",
      ["frontend"],
    ],
    [
      "Connect inventory to the storefront",
      "doing",
      5,
      "task",
      "high",
      "sam",
      ["api"],
    ],
    ["Polish mobile checkout", "doing", 3, "story", "medium", "jo", ["design"]],
    [
      "Support discount codes at checkout",
      "ready",
      3,
      "story",
      "medium",
      "you",
      ["commerce"],
    ],
    [
      "Fix cart totals after quantity changes",
      "ready",
      2,
      "bug",
      "urgent",
      "sam",
      ["checkout"],
    ],
    [
      "Add order confirmation emails",
      "ready",
      3,
      "task",
      "medium",
      "alex",
      ["api"],
    ],
    [
      "Improve empty states across the app",
      "ready",
      2,
      "task",
      "low",
      "jo",
      ["design"],
    ],
    [
      "Review the payment webhook contract",
      "review",
      3,
      "task",
      "high",
      "you",
      ["payments"],
    ],
    [
      "Add keyboard navigation to search",
      "review",
      2,
      "story",
      "medium",
      "jo",
      ["a11y"],
    ],
    [
      "Set up a repeatable release pipeline",
      "done",
      3,
      "task",
      "high",
      "sam",
      ["devops"],
    ],
    [
      "Define the storefront design system",
      "done",
      5,
      "story",
      "medium",
      "jo",
      ["design"],
    ],
    [
      "Ship the customer account API",
      "done",
      5,
      "task",
      "high",
      "alex",
      ["api"],
    ],
    [
      "Add customer wishlists",
      "backlog",
      5,
      "story",
      "medium",
      "unassigned",
      ["discovery"],
    ],
    [
      "Introduce stock availability alerts",
      "backlog",
      3,
      "story",
      "low",
      "unassigned",
      ["inventory"],
    ],
    [
      "Generate shareable product links",
      "backlog",
      2,
      "task",
      "medium",
      "you",
      ["growth"],
    ],
    [
      "Audit image loading performance",
      "backlog",
      3,
      "task",
      "high",
      "alex",
      ["performance"],
    ],
  ];
  const issues: Issue[] = entries.map(
    ([title, status, points, kind, priority, assignee, labels], index) => ({
      id: `demo-${index + 1}`,
      number: 101 + index,
      title,
      status,
      points,
      kind,
      priority,
      assignee,
      labels,
      dependsOn: index === 3 ? ["demo-5"] : [],
      sprintId: status === "backlog" ? null : "sprint-7",
      description:
        "Synthetic portfolio issue. Define acceptance criteria, link dependencies, and move this work through the sprint.",
      archived: false,
      createdAt: now - 8 * day,
      updatedAt: now - (index % 4) * day,
      comments: [],
    }),
  );
  return {
    name: "Storefront",
    key: "ST",
    description: "Build a shopping experience people love.",
    nextNumber: 117,
    issues,
    sprints: [
      {
        id: "sprint-7",
        name: "Sprint 07",
        goal: "A faster path from discovery to checkout.",
        startDate: date(-6),
        endDate: date(7),
        state: "active",
        baseline: 41,
        history: [41, 38, 35, 35, 31, 28, 28].map((remaining, index) => ({
          at: now - (6 - index) * day,
          remaining,
        })),
      },
    ],
    activity: [
      {
        id: "demo-activity-1",
        message: "Moved ST-112 to Done",
        at: now - 2 * 3600000,
        issueId: "demo-12",
      },
      {
        id: "demo-activity-2",
        message: "Added a dependency to ST-104",
        at: now - 5 * 3600000,
        issueId: "demo-4",
      },
      {
        id: "demo-activity-3",
        message: "Started Sprint 07 with 12 issues",
        at: now - 6 * day,
      },
    ],
  };
}
