import { z } from 'zod';
import { maintenanceStatus } from './network-maintenance';
import { networkDb as db,audit,rateLimit,networkEnv } from './network-security';
import { networkActor } from './network-access';
import { areaInput } from './network-model';
import { areas,deliverySummary,eventForOrder } from './network-store';
import { dispatchDelivery,tickNetwork } from './network-dispatch';
import { hashSecret,TrackingError } from './tracking';
import type { Dispatch } from './dispatch';
export async function deliveryTenant(orderId:string,riderOwner:string,dispatchId:string){const r=await db().prepare('SELECT d.merchant_id FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.order_id=? AND d.rider_owner=? AND o.dispatch_id=?').bind(orderId,riderOwner,dispatchId).first<{merchant_id:string}>();return r?.merchant_id??riderOwner;}
export async function checkDeliveryOtp(orderId:string,deviceId:string,owner:string,otp?:string){
  const d=await db().prepare('SELECT d.otp_hash,d.merchant_id,d.external_id FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.order_id=? AND d.rider_owner=? AND o.device_id=?').bind(orderId,owner,deviceId).first<{otp_hash:string;merchant_id:string;external_id:string}>();if(!d)return null;
  await rateLimit('otp:'+deviceId+':'+orderId,10,900000);if(!otp||!/^\d{6}$/.test(otp)||await hashSecret(d.merchant_id+':'+d.external_id+':'+otp)!==d.otp_hash)throw new TrackingError(422,'Enter the six-digit customer delivery OTP. Use the RouteForge rider portal if your installed app has no OTP control.');
  return JSON.stringify({method:'otp',verifiedAt:Date.now(),deviceId});
}
export async function cancelNetworkDelivery(owner:string,id:string,actor:string){
  const row=await db().prepare("SELECT o.version,o.status,o.dispatch_id,o.device_id,d.rider_owner FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.order_id=? AND d.merchant_id=?").bind(id,owner).first<{version:number;status:string;dispatch_id:string|null;device_id:string|null;rider_owner:string|null}>();if(!row)throw new TrackingError(404,'Delivery not found.');if(row.status==='delivered'||row.status==='cancelled')throw new TrackingError(409,'Delivery is already closed.');
  const now=Date.now(),result=await db().batch([
    db().prepare("UPDATE office_orders SET status='cancelled',version=version+1,updated_at=?,payload_json=json_set(payload_json,'$.status','cancelled','$.version',version+1,'$.updatedAt',?,'$.offerDeadline',NULL) WHERE id=? AND owner_id=? AND version=? AND status NOT IN ('delivered','cancelled') RETURNING id").bind(now,now,id,owner,row.version),
    db().prepare("UPDATE network_offers SET status='cancelled' WHERE order_id=? AND status='pending' AND EXISTS(SELECT 1 FROM office_orders WHERE id=? AND owner_id=? AND status='cancelled')").bind(id,id,owner),
    db().prepare("DELETE FROM driver_dispatches WHERE device_id=? AND owner_id=? AND json_extract(dispatch_json,'$.id')=? AND EXISTS(SELECT 1 FROM office_orders WHERE id=? AND owner_id=? AND status='cancelled')").bind(row.device_id,row.rider_owner,row.dispatch_id,id,owner),
  ]);if(!result[0].results.length)throw new TrackingError(409,'Delivery changed. Refresh and retry.');await eventForOrder(id);await audit(owner,actor,'delivery.cancelled',id);return {ok:true};
}
export async function deliveryAction(payload:unknown){const a=await networkActor('dispatch'),p=z.object({id:z.string().uuid(),action:z.enum(['ready','retry','cancel'])}).strict().safeParse(payload);if(!p.success)throw new TrackingError(422,'Choose a delivery and action.');const i=p.data;if(i.action==='cancel')return cancelNetworkDelivery(a.owner,i.id,a.actor);const {readyDelivery}=await import('./network-store');if(i.action==='ready')return readyDelivery(i.id,a.owner,a.actor);await deliverySummary(i.id,a.owner);await db().batch([db().prepare("UPDATE merchant_deliveries SET attempts=0,next_attempt_at=0,exception=NULL WHERE order_id=? AND merchant_id=? AND EXISTS(SELECT 1 FROM office_orders WHERE id=? AND status='queued')").bind(i.id,a.owner,i.id),db().prepare("UPDATE network_offers SET status='retried' WHERE order_id=? AND status IN ('expired','declined') AND EXISTS(SELECT 1 FROM office_orders WHERE id=? AND owner_id=? AND status='queued')").bind(i.id,i.id,a.owner)]);await dispatchDelivery(i.id);await audit(a.owner,a.actor,'delivery.retry.requested',i.id);return deliverySummary(i.id,a.owner);}
export async function adminData(){
  const a=await networkActor('admin');const [merchants,deliveries,riders,audits,webhooks,totals]=await Promise.all([
    db().prepare('SELECT id,name,email,phone,status,fleet_mode,subscription,created_at FROM merchants ORDER BY created_at DESC LIMIT 200').all(),
    db().prepare("SELECT o.id,o.status,o.updated_at,d.merchant_id,d.external_id,d.fee_minor,d.fleet,d.exception FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id ORDER BY o.updated_at DESC LIMIT 100").all(),
    db().prepare('SELECT n.device_id,n.merchant_id,n.enabled,n.vehicle_type,n.capacity_grams,n.area_id,t.driver_name,t.vehicle_label FROM network_riders n JOIN tracking_devices t ON t.id=n.device_id AND t.owner_id=n.owner_id').all(),
    db().prepare('SELECT * FROM network_audit ORDER BY created_at DESC LIMIT 50').all(),
    db().prepare('SELECT w.id,w.status,w.attempts,w.last_status,i.merchant_id,i.name FROM webhook_outbox w JOIN merchant_integrations i ON i.id=w.integration_id ORDER BY w.next_attempt_at DESC LIMIT 50').all(),
    db().prepare("SELECT COUNT(*) AS total,SUM(o.status='delivered') AS completed,COALESCE(SUM(CASE WHEN o.status='delivered' THEN d.fee_minor ELSE 0 END),0) AS completedFeesMinor,SUM(d.exception IS NOT NULL AND o.status NOT IN ('delivered','cancelled')) AS exceptions FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id").first(),
  ]);const ledger=await db().prepare('SELECT l.*,t.driver_name FROM network_ledger l LEFT JOIN tracking_devices t ON t.id=l.device_id ORDER BY l.created_at DESC LIMIT 100').all();const ledgerTotals=await db().prepare('SELECT COALESCE(SUM(commission_minor),0) AS commissionMinor,COALESCE(SUM(rider_earning_minor),0) AS riderEarningsMinor,COUNT(*) AS accrued FROM network_ledger').first();return {maintenance:await maintenanceStatus(),ledger:ledger.results,ledgerTotals,isAdmin:a.isAdmin,merchants:merchants.results,deliveries:deliveries.results,riders:riders.results,audits:audits.results,webhooks:webhooks.results,totals,areas:await areas(),payments:{liveEnabled:false,provider:'M-Pesa',state:'disabled'}};
}
export async function adminAction(payload:unknown){
  const a=await networkActor('admin'),p=z.discriminatedUnion('action',[
    z.object({action:z.literal('merchant'),id:z.string().min(1).max(150),status:z.enum(['pending','active','suspended']),subscription:z.enum(['standard','business','enterprise']).default('standard')}).strict(),
    z.object({action:z.literal('area'),area:areaInput}).strict(),
    z.object({action:z.literal('webhook_retry'),id:z.string().min(1).max(150)}).strict(),
    z.object({action:z.literal('settlement_review'),id:z.string().uuid()}).strict(),
    z.object({action:z.literal('rider'),id:z.string().uuid(),enabled:z.boolean()}).strict(),
    z.object({action:z.literal('tick')}).strict(),
  ]).safeParse(payload);if(!p.success)throw new TrackingError(422,'Check the platform configuration.');const i=p.data;
  if(i.action==='tick')return tickNetwork();
  if(i.action==='rider'){const r=await db().prepare('UPDATE network_riders SET enabled=? WHERE device_id=? RETURNING merchant_id').bind(Number(i.enabled),i.id).first<{merchant_id:string|null}>();if(!r)throw new TrackingError(404,'Network rider not found.');await audit(r.merchant_id??a.owner,a.actor,'rider.eligibility.changed',i.id);return {ok:true};}
  if(i.action==='settlement_review'){const r=await db().prepare("UPDATE network_ledger SET state='reviewed' WHERE order_id=? AND state='pending_review' RETURNING merchant_id").bind(i.id).first<{merchant_id:string}>();if(!r)throw new TrackingError(409,'Earnings are already reviewed or not accrued.');await audit(r.merchant_id,a.actor,'earnings.reviewed',i.id);return {ok:true,livePayment:false};}
  if(i.action==='merchant'){const r=await db().prepare('UPDATE merchants SET status=?,subscription=?,updated_at=? WHERE id=? RETURNING id').bind(i.status,i.subscription,Date.now(),i.id).first();if(!r)throw new TrackingError(404,'Merchant not found.');await audit(i.id,a.actor,'merchant.'+i.status,i.id);return {ok:true};}
  if(i.action==='webhook_retry'){const r=await db().prepare("UPDATE webhook_outbox SET status='pending',attempts=0,next_attempt_at=0,lease_until=0 WHERE id=? AND status='failed' RETURNING id").bind(i.id).first();if(!r)throw new TrackingError(409,'Only a failed callback can be retried manually.');await audit(a.owner,a.actor,'webhook.retry.requested',i.id);return {ok:true};}
  const id=i.area.id??crypto.randomUUID(),config={...i.area,id};await db().prepare('INSERT INTO service_areas(id,name,config_json,active,version) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET name=excluded.name,config_json=excluded.config_json,active=excluded.active,version=service_areas.version+1').bind(id,config.name,JSON.stringify(config),Number(config.active)).run();await audit(a.owner,a.actor,'service_area.updated',id);return {id};
}
export async function publicTracking(request:Request){await rateLimit('tracking:'+(request.headers.get('cf-connecting-ip')??'unknown'),60);const token=request.headers.get('authorization')?.replace(/^Bearer /,'')??'';if(!/^[a-f0-9]{64}$/.test(token))throw new TrackingError(401,'Open the tracking link supplied by the merchant.');const r=await db().prepare("SELECT o.id,o.status,o.payload_json,t.latest_point_json,t.latest_point_at,d.proof_json,t.last_event_kind,r.gps_enabled,r.on_duty FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id LEFT JOIN tracking_devices t ON t.id=o.device_id AND t.owner_id=d.rider_owner LEFT JOIN driver_runtime r ON r.device_id=t.id AND r.owner_id=t.owner_id WHERE d.tracking_hash=?").bind(await hashSecret(token)).first<{id:string;status:string;payload_json:string;latest_point_json:string|null;latest_point_at:number|null;proof_json:string|null;last_event_kind:string|null;gps_enabled:number|null;on_duty:number|null}>();if(!r)throw new TrackingError(404,'Tracking link not found.');const o=JSON.parse(r.payload_json);const point=r.latest_point_json?JSON.parse(r.latest_point_json):null;return {id:r.id,title:o.title,status:r.status,updatedAt:o.updatedAt,collectedAt:o.pickedUpAt,deliveredAt:o.deliveredAt,proofMethod:r.proof_json?'otp':null,riderLocation:!['delivered','cancelled','queued','offered'].includes(r.status)&&point&&r.gps_enabled===1&&r.on_duty===1&&r.last_event_kind==='point'&&(r.latest_point_at??0)>Date.now()-90000?{lat:point.lat,lng:point.lng,at:r.latest_point_at}:null};}
export async function guardLegacyDelivery(owner:string,dispatch:Dispatch,action:string){if(!dispatch.orderId)return;const r=await db().prepare('SELECT merchant_id FROM merchant_deliveries WHERE order_id=?').bind(dispatch.orderId).first<{merchant_id:string}>();if(!r)return;if(action==='cancel')return cancelNetworkDelivery(r.merchant_id,dispatch.orderId,owner);throw new TrackingError(409,'Confirm merchant delivery progress in the rider app with the customer OTP.');}
export function platformOwner(){return networkEnv().ROUTEFORGE_PLATFORM_OWNER;}
