import bcrypt from "bcryptjs";
import { z } from "zod";
import { registrationInput,branchInput,fleetInput,deliveryInput,quote,publicWebhookUrl,type Area,type AreaConfig,type Merchant } from "./network-model";
import { networkDb as db,networkEnabled,audit,rateLimit,encryptSecret } from "./network-security";
import { networkActor,activeMerchant } from "./network-access";
import { randomSecret,hashSecret,TrackingError } from "./tracking";
import { createDriverAccount } from "./accounts";
import { usernameInput } from "./account-input";
import type { OfficeOrder,Place } from "./office";
import { deferOffice } from "./office-context";
export async function areas():Promise<Area[]>{return (await db().prepare("SELECT * FROM service_areas").all<{id:string;name:string;config_json:string;active:number;version:number}>()).results.map(r=>({...r,config:JSON.parse(r.config_json) as AreaConfig}));}
export async function registerMerchant(request:Request,payload:unknown){
  networkEnabled();await rateLimit("register:"+(request.headers.get("cf-connecting-ip")??"unknown"),5,3600000);
  const p=registrationInput.safeParse(payload);if(!p.success)throw new TrackingError(422,p.error.issues[0]?.message??"Check your business details.");
  const i=p.data;if(bcrypt.truncates(i.password))throw new TrackingError(422,"Password must fit within 72 UTF-8 bytes.");
  const id=crypto.randomUUID(),accountId=crypto.randomUUID(),now=Date.now(),passwordHash=await bcrypt.hash(i.password,12);
  try{await db().batch([
    db().prepare("INSERT INTO merchants(id,name,email,phone,status,fleet_mode,created_at,updated_at) VALUES(?,?,?,?,'pending','owned',?,?)").bind(id,i.name,i.email,i.phone,now,now),
    db().prepare("INSERT INTO company_accounts(id,owner_id,username,username_key,password_hash,role,phone,enabled,version,created_at,updated_at) VALUES(?,?,?,?,?,'office',?,1,1,?,?)").bind(accountId,id,i.username,i.username.toLowerCase(),passwordHash,i.phone,now,now),
    db().prepare("INSERT INTO merchant_staff(account_id,merchant_id,role) VALUES(?,?,'owner')").bind(accountId,id),
    db().prepare("INSERT INTO network_audit(id,merchant_id,actor,action,subject_id,created_at) VALUES(?,?,?,'merchant.registered',?,?)").bind(crypto.randomUUID(),id,accountId,id,now),
  ]);}catch(e){if(e instanceof Error&&/UNIQUE constraint/.test(e.message))throw new TrackingError(409,"Choose a different dashboard username.");throw e;}
  return {id,status:"pending",username:i.username};
}
export async function adoptMerchant(payload:unknown){
  networkEnabled();const a=await networkActor("owner"),p=registrationInput.omit({username:true,password:true}).safeParse(payload);if(!p.success)throw new TrackingError(422,"Enter your company name, email and phone.");
  const i=p.data,now=Date.now();await db().prepare("INSERT INTO merchants(id,name,email,phone,status,fleet_mode,created_at,updated_at) VALUES(?,?,?,?,?,'owned',?,?) ON CONFLICT(id) DO NOTHING").bind(a.owner,i.name,i.email,i.phone,a.isAdmin?"active":"pending",now,now).run();
  if(a.accountId)await db().prepare("INSERT INTO merchant_staff(account_id,merchant_id,role) VALUES(?,?,'owner') ON CONFLICT(account_id) DO NOTHING").bind(a.accountId,a.owner).run();
  await audit(a.owner,a.actor,"merchant.profile.created",a.owner);return {ok:true};
}
export async function merchantData(){
  const a=await networkActor(),m=await db().prepare("SELECT * FROM merchants WHERE id=?").bind(a.owner).first<Merchant>();
  const areaList=await areas();if(!m)return {
    merchant:null,role:a.role,isAdmin:a.isAdmin,areas:areaList,
    branches:[],deliveries:[],riders:[],integrations:[],staff:[],tracking:[],
    events:[],audits:[],webhookAttempts:[],pricingAcceptances:[],ledger:[],
    metrics:{total:0,completed:0,cancelled:0,active:0,deliveredFeesMinor:0,averageMinutes:null},
    billing:{currency:'KES',livePayments:false,subscription:null},
  };
  const [branches,deliveries,riders,integrations,staff,events,audits]=await Promise.all([
    db().prepare("SELECT id,name,location_json,active FROM merchant_branches WHERE merchant_id=? ORDER BY created_at").bind(a.owner).all(),
    db().prepare("SELECT o.payload_json,d.external_id,d.ready,d.fee_minor,d.fleet,d.exception,d.proof_json,d.input_json FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.merchant_id=? ORDER BY o.updated_at DESC LIMIT 100").bind(a.owner).all(),
    db().prepare("SELECT n.device_id,n.vehicle_type,n.capacity_grams,n.area_id,n.enabled,d.driver_name,d.vehicle_label,d.latest_point_json,d.last_seen_at FROM network_riders n JOIN tracking_devices d ON d.id=n.device_id AND d.owner_id=n.owner_id WHERE n.merchant_id=?").bind(a.owner).all(),
    db().prepare("SELECT id,name,key_prefix,webhook_url,enabled,created_at FROM merchant_integrations WHERE merchant_id=?").bind(a.owner).all(),
    db().prepare("SELECT a.id,a.username,a.enabled,s.role FROM merchant_staff s JOIN company_accounts a ON a.id=s.account_id AND a.owner_id=s.merchant_id WHERE s.merchant_id=?").bind(a.owner).all(),
    db().prepare("SELECT e.id,e.order_id,e.event_type,e.created_at,e.payload_json FROM network_events e WHERE e.merchant_id=? ORDER BY created_at DESC LIMIT 30").bind(a.owner).all(),
    db().prepare("SELECT actor,action,subject_id,created_at FROM network_audit WHERE merchant_id=? ORDER BY created_at DESC LIMIT 30").bind(a.owner).all(),
  ]);
  const list=deliveries.results.map(r=>({order:JSON.parse(r.payload_json as string) as OfficeOrder,externalId:r.external_id,ready:r.ready,feeMinor:r.fee_minor,fleet:r.fleet,exception:r.exception,proof:r.proof_json?JSON.parse(r.proof_json as string):null,customer:JSON.parse(r.input_json as string).customer}));
  const tracking=await db().prepare("SELECT o.id,d.driver_name,d.latest_point_json,d.latest_point_at FROM merchant_deliveries m JOIN office_orders o ON o.id=m.order_id AND o.owner_id=m.merchant_id JOIN tracking_devices d ON d.id=o.device_id AND d.owner_id=m.rider_owner WHERE m.merchant_id=? AND o.status NOT IN ('delivered','cancelled')").bind(a.owner).all();
  const webhookAttempts=await db().prepare("SELECT w.id,w.status,w.attempts,w.last_status,w.next_attempt_at FROM webhook_outbox w JOIN merchant_integrations i ON i.id=w.integration_id WHERE i.merchant_id=? ORDER BY w.next_attempt_at DESC LIMIT 30").bind(a.owner).all();
  const metrics=await db().prepare("SELECT COUNT(*) AS total,SUM(o.status='delivered') AS completed,SUM(o.status='cancelled') AS cancelled,SUM(o.status NOT IN ('delivered','cancelled')) AS active,COALESCE(SUM(CASE WHEN o.status='delivered' THEN d.fee_minor ELSE 0 END),0) AS deliveredFeesMinor,AVG(CASE WHEN o.status='delivered' THEN (json_extract(o.payload_json,'$.deliveredAt')-json_extract(o.payload_json,'$.createdAt'))/60000 END) AS averageMinutes FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.merchant_id=?").bind(a.owner).first();
  const ledger=await db().prepare('SELECT order_id,fee_minor,commission_minor,rider_earning_minor,state,created_at FROM network_ledger WHERE merchant_id=? ORDER BY created_at DESC LIMIT 100').bind(a.owner).all();
  const pricingAcceptances=await db().prepare('SELECT area_id,version,accepted_at FROM merchant_pricing_acceptance WHERE merchant_id=?').bind(a.owner).all();
  return {pricingAcceptances:pricingAcceptances.results,ledger:['owner','manager'].includes(a.role)?ledger.results:[],merchant:m,role:a.role,isAdmin:a.isAdmin,areas:areaList,branches:branches.results.map(r=>({...r,location:JSON.parse(r.location_json as string),location_json:undefined})),deliveries:list,riders:riders.results.map(r=>({...r,point:r.latest_point_json?JSON.parse(r.latest_point_json as string):null,latest_point_json:undefined})),tracking:tracking.results.map(r=>({...r,point:r.latest_point_json?JSON.parse(r.latest_point_json as string):null,latest_point_json:undefined})),integrations:['owner','manager'].includes(a.role)?integrations.results:[],staff:a.role==='owner'?staff.results:[],events:events.results,audits:a.role==='owner'?audits.results:[],webhookAttempts:['owner','manager'].includes(a.role)?webhookAttempts.results:[],metrics,billing:{currency:'KES',livePayments:false,subscription:m.subscription}};
}
export async function merchantSetting(payload:unknown){
  const a=await networkActor("manage"),p=fleetInput.safeParse(payload);if(!p.success)throw new TrackingError(422,"Choose a fleet mode and confirm the current shared-fleet pricing.");
  const i=p.data,all=await areas(),accepted=i.pricingAcceptances??all.filter(z=>z.active&&z.version===i.acceptedPricingVersion).map(z=>({areaId:z.id,version:z.version}));
  if(new Set(accepted.map(c=>c.areaId)).size!==accepted.length||accepted.some(c=>!all.some(z=>z.id===c.areaId&&z.active&&z.version===c.version)))throw new TrackingError(409,"Pricing changed. Review and accept the current area rates.");
  if((i.fleetMode==='shared'||i.fleetMode==='hybrid'&&i.fallbackEnabled)&&!accepted.length)throw new TrackingError(422,"Accept the displayed shared-fleet rates before enabling shared dispatch.");
  const now=Date.now(),results=await db().batch([
    db().prepare("UPDATE merchants SET fleet_mode=?,fallback_enabled=?,accepted_pricing_version=?,updated_at=? WHERE id=? RETURNING id").bind(i.fleetMode,Number(i.fallbackEnabled),i.acceptedPricingVersion??null,now,a.owner),
    db().prepare('DELETE FROM merchant_pricing_acceptance WHERE merchant_id=?').bind(a.owner),
    ...accepted.map(c=>db().prepare("INSERT INTO merchant_pricing_acceptance(merchant_id,area_id,version,terms_json,accepted_by,accepted_at) SELECT ?,id,version,config_json,?,? FROM service_areas WHERE id=? AND active=1 AND version=? AND EXISTS(SELECT 1 FROM merchants WHERE id=?) RETURNING area_id").bind(a.owner,a.actor,now,c.areaId,c.version,a.owner)),
  ]);
  if(!results[0].results.length)throw new TrackingError(404,"Complete your merchant profile first.");
  if(results.slice(2).reduce((n,r)=>n+r.results.length,0)!==accepted.length)throw new TrackingError(409,"Pricing changed while saving. Review and accept the current area rates.");
  await audit(a.owner,a.actor,"fleet.preferences.updated",a.owner);return {ok:true};
}
export async function updateMerchantProfile(payload:unknown){const a=await networkActor('manage'),i=registrationInput.omit({username:true,password:true}).parse(payload);const r=await db().prepare('UPDATE merchants SET name=?,email=?,phone=?,updated_at=? WHERE id=? RETURNING id').bind(i.name,i.email,i.phone,Date.now(),a.owner).first();if(!r)throw new TrackingError(404,'Merchant profile not found.');await audit(a.owner,a.actor,'merchant.profile.updated',a.owner);return {ok:true};}
export async function addBranch(payload:unknown){const a=await networkActor("manage"),p=branchInput.safeParse(payload);if(!p.success)throw new TrackingError(422,"Set a branch name and valid pickup pin.");const id=crypto.randomUUID();const r=await db().prepare("INSERT INTO merchant_branches(id,merchant_id,name,location_json,created_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM merchants WHERE id=?) AND (SELECT COUNT(*) FROM merchant_branches WHERE merchant_id=?)<50 RETURNING id").bind(id,a.owner,p.data.name,JSON.stringify(p.data.location),Date.now(),a.owner,a.owner).first();if(!r)throw new TrackingError(409,"Complete the company profile or review your 50-branch limit.");await audit(a.owner,a.actor,"branch.created",id);return {id};}
export async function changeBranch(payload:unknown){
  const a=await networkActor("manage"),p=z.object({id:z.string().uuid(),active:z.boolean().optional(),name:z.string().trim().min(2).max(80).optional(),location:branchInput.shape.location.optional()}).strict().refine(v=>v.active!==undefined||v.name!==undefined||v.location!==undefined).parse(payload);
  const r=await db().prepare("UPDATE merchant_branches SET active=COALESCE(?,active),name=COALESCE(?,name),location_json=COALESCE(?,location_json) WHERE id=? AND merchant_id=? RETURNING id").bind(p.active===undefined?null:Number(p.active),p.name??null,p.location?JSON.stringify(p.location):null,p.id,a.owner).first();
  if(!r)throw new TrackingError(404,"Branch not found.");await audit(a.owner,a.actor,"branch.updated",p.id);return {ok:true};
}
export async function addStaff(payload:unknown){const a=await networkActor("owner"),p=z.object({username:usernameInput,role:z.enum(['manager','dispatcher']),password:z.string().min(12).max(72)}).strict().safeParse(payload);if(!p.success||bcrypt.truncates(p.data.password))throw new TrackingError(422,"Choose a staff username, role and password of at least 12 characters.");const i=p.data,id=crypto.randomUUID(),now=Date.now(),hash=await bcrypt.hash(i.password,12);try{await db().batch([db().prepare("INSERT INTO company_accounts(id,owner_id,username,username_key,password_hash,role,enabled,version,created_at,updated_at) SELECT ?,?,?,?,?,'office',1,1,?,? WHERE (SELECT COUNT(*) FROM merchant_staff WHERE merchant_id=?)<30").bind(id,a.owner,i.username,i.username.toLowerCase(),hash,now,now,a.owner),db().prepare("INSERT INTO merchant_staff(account_id,merchant_id,role) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM company_accounts WHERE id=?)").bind(id,a.owner,i.role,id)]);}catch(e){if(e instanceof Error&&/UNIQUE constraint/.test(e.message))throw new TrackingError(409,"That username is already registered.");throw e;}if(!await db().prepare("SELECT account_id FROM merchant_staff WHERE account_id=?").bind(id).first())throw new TrackingError(409,"Staff limit reached.");await audit(a.owner,a.actor,"staff.created",id);return {id,username:i.username,role:i.role};}
export async function changeStaff(payload:unknown){const a=await networkActor("owner"),p=z.object({id:z.string().uuid(),enabled:z.boolean()}).strict().parse(payload);const r=await db().prepare("UPDATE company_accounts SET enabled=?,version=version+1,updated_at=? WHERE id=? AND owner_id=? AND EXISTS(SELECT 1 FROM merchant_staff WHERE account_id=company_accounts.id AND merchant_id=? AND role<>'owner') RETURNING id").bind(Number(p.enabled),Date.now(),p.id,a.owner,a.owner).first();if(!r)throw new TrackingError(404,"Staff account not found or is the business owner.");await audit(a.owner,a.actor,"staff.access.changed",p.id);return {ok:true};}
export async function addIntegration(payload:unknown){const a=await networkActor("manage"),p=z.object({name:z.string().trim().min(2).max(80),webhookUrl:z.string().max(500).optional()}).strict().safeParse(payload);if(!p.success)throw new TrackingError(422,"Name the integration and check the callback URL.");let url:null|string=null;try{if(p.data.webhookUrl)url=publicWebhookUrl(p.data.webhookUrl);}catch{throw new TrackingError(422,"Use a public HTTPS callback URL.");}const id=crypto.randomUUID(),key='rf_live_'+randomSecret(),secret=randomSecret(),cipher=await encryptSecret(secret);await db().prepare("INSERT INTO merchant_integrations(id,merchant_id,name,key_hash,key_prefix,secret_cipher,webhook_url,created_at) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM merchants WHERE id=?) AND (SELECT COUNT(*) FROM merchant_integrations WHERE merchant_id=?)<10").bind(id,a.owner,p.data.name,await hashSecret(key),key.slice(0,18),cipher,url,Date.now(),a.owner,a.owner).run();if(!await db().prepare("SELECT id FROM merchant_integrations WHERE id=?").bind(id).first())throw new TrackingError(409,"Complete the company profile or review your integration limit.");await audit(a.owner,a.actor,"integration.created",id);return {id,apiKey:key,webhookSecret:secret};}
export async function changeIntegration(payload:unknown){const a=await networkActor("manage"),p=z.object({id:z.string().uuid(),enabled:z.boolean()}).strict().parse(payload);const r=await db().prepare("UPDATE merchant_integrations SET enabled=? WHERE id=? AND merchant_id=? RETURNING id").bind(Number(p.enabled),p.id,a.owner).first();if(!r)throw new TrackingError(404,"Integration not found.");await audit(a.owner,a.actor,"integration.access.changed",p.id);return {ok:true};}
export async function enrollRider(payload:unknown,shared=false){const a=await networkActor(shared?'admin':'manage'),p=z.object({deviceId:z.string().uuid(),vehicleType:z.enum(['bicycle','motorcycle','car','van']),capacityKg:z.number().positive().max(1000),areaId:z.string().uuid(),enabled:z.boolean().default(true)}).strict().safeParse(payload);if(!p.success)throw new TrackingError(422,"Choose your registered rider, vehicle, capacity and delivery area.");const i=p.data;if(!shared)await activeMerchant(a.owner);const r=await db().prepare("INSERT INTO network_riders(device_id,owner_id,merchant_id,vehicle_type,capacity_grams,area_id,enabled) SELECT id,?,?,?,?,?,? FROM tracking_devices WHERE id=? AND owner_id=? AND EXISTS(SELECT 1 FROM service_areas WHERE id=? AND active=1) ON CONFLICT(device_id) DO UPDATE SET merchant_id=excluded.merchant_id,vehicle_type=excluded.vehicle_type,capacity_grams=excluded.capacity_grams,area_id=excluded.area_id,enabled=excluded.enabled WHERE network_riders.owner_id=excluded.owner_id RETURNING device_id").bind(a.owner,shared?null:a.owner,i.vehicleType,Math.round(i.capacityKg*1000),i.areaId,Number(i.enabled),i.deviceId,a.owner,i.areaId).first();if(!r)throw new TrackingError(404,"Choose a rider owned by your office and an active service area.");await audit(a.owner,a.actor,shared?'shared.rider.enrolled':'merchant.rider.enrolled',i.deviceId);return {ok:true};}
export async function newRider(payload:unknown){const a=await networkActor('manage');await activeMerchant(a.owner);const result=await createDriverAccount(a.owner,payload);await audit(a.owner,a.actor,'rider.account.created',result.deviceId);return result;}
export async function eventForOrder(id:string){const row=await db().prepare("SELECT o.payload_json,o.version,o.owner_id,d.external_id,d.fee_minor FROM office_orders o JOIN merchant_deliveries d ON d.order_id=o.id AND d.merchant_id=o.owner_id WHERE o.id=?").bind(id).first<{payload_json:string;version:number;owner_id:string;external_id:string;fee_minor:number}>();if(!row)return;const o=JSON.parse(row.payload_json) as OfficeOrder,eventId=await hashSecret(id+':'+row.version),body=JSON.stringify({id:eventId,type:'delivery.'+o.status,orderId:id,externalId:row.external_id,status:o.status,feeMinor:row.fee_minor,currency:'KES',occurredAt:o.updatedAt,version:row.version});if(o.status==='delivered'&&o.deviceId)await db().prepare("INSERT INTO network_ledger(order_id,merchant_id,device_id,fee_minor,commission_minor,rider_earning_minor,created_at) SELECT d.order_id,d.merchant_id,?,d.fee_minor,CASE WHEN d.fleet='shared' THEN ROUND(d.fee_minor*d.commission_bps/10000.0) ELSE 0 END,CASE WHEN d.fleet='shared' THEN d.fee_minor-ROUND(d.fee_minor*d.commission_bps/10000.0) WHEN json_extract(o.payload_json,'$.ratePerKm') IS NOT NULL THEN ROUND(json_extract(o.payload_json,'$.measuredKm')*json_extract(o.payload_json,'$.ratePerKm')*100) ELSE NULL END,? FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.order_id=? AND o.status='delivered' AND d.proof_json IS NOT NULL ON CONFLICT(order_id) DO NOTHING").bind(o.deviceId,o.deliveredAt??Date.now(),id).run();await db().batch([db().prepare("INSERT INTO network_events(id,merchant_id,order_id,event_type,payload_json,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(eventId,row.owner_id,id,'delivery.'+o.status,body,o.updatedAt),db().prepare("INSERT INTO webhook_outbox(id,integration_id,event_id,next_attempt_at) SELECT ?||':'||id,id,?,? FROM merchant_integrations WHERE merchant_id=? AND enabled=1 AND webhook_url IS NOT NULL ON CONFLICT(integration_id,event_id) DO NOTHING").bind(eventId,eventId,Date.now(),row.owner_id)]);}
export async function createDelivery(owner:string,payload:unknown,actor=owner){
  networkEnabled();await activeMerchant(owner);const p=deliveryInput.safeParse(payload);if(!p.success)throw new TrackingError(422,p.error.issues[0]?.message??'Check the delivery details.');
  const i=p.data,{trackingToken,deliveryOtp,...canonical}=i,inputJson=JSON.stringify(canonical),trackingHash=await hashSecret(trackingToken),otpHash=await hashSecret(owner+':'+i.externalId+':'+deliveryOtp);
  const existing=await db().prepare("SELECT d.order_id,d.input_json,d.tracking_hash,d.otp_hash,o.payload_json FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.merchant_id=? AND d.external_id=?").bind(owner,i.externalId).first<{order_id:string;input_json:string;tracking_hash:string;otp_hash:string;payload_json:string}>();
  if(existing){if(existing.input_json!==inputJson||existing.tracking_hash!==trackingHash||existing.otp_hash!==otpHash)throw new TrackingError(409,'External order ID already exists with different details. Use the ready endpoint to change readiness.');await eventForOrder(existing.order_id);return deliverySummary(existing.order_id,owner);}
  const branch=await db().prepare("SELECT location_json FROM merchant_branches WHERE id=? AND merchant_id=? AND active=1").bind(i.branchId,owner).first<{location_json:string}>();if(!branch)throw new TrackingError(404,'Choose an active branch belonging to this merchant.');
  const pickup=JSON.parse(branch.location_json) as Place,all=await areas();let selected:Area|undefined;for(const a of all){try{quote(a,pickup,i.destination);selected=a;break;}catch{}}if(!selected)throw new TrackingError(422,'Pickup and destination must both lie within an active RouteForge service area.');
  if(i.windowEnd&&i.windowEnd<=Date.now())throw new TrackingError(422,'The delivery window has already expired.');const fee=quote(selected,pickup,i.destination),id=crypto.randomUUID(),now=Date.now();
  const base={id,title:i.title,pickup,destination:i.destination,notes:i.notes,amountDue:null};const o:OfficeOrder={...base,network:true,status:'queued',deviceId:null,dispatchId:null,driverName:null,vehicleLabel:null,createdAt:now,assignedAt:null,pickedUpAt:null,arrivedAt:null,deliveredAt:null,updatedAt:now,version:1,estimatedKm:fee.estimatedKm,measuredKm:0,excludedSegments:0,ratePerKm:null,distanceCheckedAt:0};
  await db().batch([
    db().prepare("INSERT INTO office_orders(id,owner_id,status,input_json,payload_json,version,updated_at) SELECT ?,?,'queued',?,?,1,? WHERE NOT EXISTS(SELECT 1 FROM merchant_deliveries WHERE merchant_id=? AND external_id=?) AND (SELECT COUNT(*) FROM office_orders WHERE owner_id=? AND status NOT IN ('delivered','cancelled'))<300").bind(id,owner,JSON.stringify(base),JSON.stringify(o),now,owner,i.externalId,owner),
    db().prepare("INSERT INTO merchant_deliveries(order_id,merchant_id,external_id,branch_id,input_json,ready,fee_minor,area_id,pricing_version,commission_bps,tracking_hash,otp_hash) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM office_orders WHERE id=? AND owner_id=?) ON CONFLICT(merchant_id,external_id) DO NOTHING").bind(id,owner,i.externalId,i.branchId,inputJson,Number(i.ready),fee.feeMinor,selected.id,selected.version,selected.config.commissionBps,trackingHash,otpHash,id,owner),
  ]);
  const saved=await db().prepare("SELECT order_id,input_json,tracking_hash,otp_hash FROM merchant_deliveries WHERE merchant_id=? AND external_id=?").bind(owner,i.externalId).first<{order_id:string;input_json:string;tracking_hash:string;otp_hash:string}>();if(!saved)throw new TrackingError(409,'Active delivery limit reached.');if(saved.input_json!==inputJson||saved.tracking_hash!==trackingHash||saved.otp_hash!==otpHash)throw new TrackingError(409,'This external ID was submitted concurrently with different details.');
  if(saved.order_id===id)await audit(owner,actor,'delivery.created',id);
  await eventForOrder(saved.order_id);deferOffice(async()=>{const {dispatchDelivery,flushWebhooks}=await import('./network-dispatch');if(i.ready)await dispatchDelivery(saved.order_id);await flushWebhooks();});return deliverySummary(saved.order_id,owner);
}
export async function deliverySummary(id:string,owner:string){const r=await db().prepare("SELECT o.payload_json,d.ready,d.fee_minor,d.fleet,d.exception,d.external_id,d.proof_json FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.order_id=? AND d.merchant_id=?").bind(id,owner).first();if(!r)throw new TrackingError(404,'Delivery not found.');const o=JSON.parse(r.payload_json as string) as OfficeOrder;return {id:o.id,externalId:r.external_id,status:o.status,ready:!!r.ready,feeMinor:r.fee_minor,currency:'KES',fleet:r.fleet,exception:r.exception,version:o.version,proof:r.proof_json?JSON.parse(r.proof_json as string):null};}
export async function readyDelivery(id:string,owner:string,actor=owner){await activeMerchant(owner);const r=await db().prepare("UPDATE merchant_deliveries SET ready=1,next_attempt_at=0,exception=NULL WHERE order_id=? AND merchant_id=? AND EXISTS(SELECT 1 FROM office_orders WHERE id=? AND owner_id=? AND status='queued') RETURNING order_id").bind(id,owner,id,owner).first();if(!r){const s=await deliverySummary(id,owner);if(!s.ready)throw new TrackingError(409,'Only a queued delivery can become ready.');return s;}await audit(owner,actor,'delivery.ready',id);const {dispatchDelivery}=await import('./network-dispatch');await dispatchDelivery(id);return deliverySummary(id,owner);}
