import { networkDb as db,audit,decryptSecret,signBody,networkEnv,networkEnabled } from './network-security';
import { eventForOrder } from './network-store';
import { TrackingError } from './tracking';
import { distanceMeters,type Dispatch } from './dispatch';
import type { OfficeOrder } from './office';
import type { AreaConfig,DeliveryInput,Merchant } from './network-model';
import { publicWebhookUrl } from './network-model';
import { deferOffice } from './office-context';
type DeliveryRow={order_id:string;merchant_id:string;input_json:string;ready:number;fee_minor:number;area_id:string;pricing_version:number;attempts:number;rider_owner:string|null;payload_json:string;version:number;status:string};
async function delivery(id:string){return db().prepare("SELECT d.*,o.payload_json,o.version,o.status FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id WHERE d.order_id=?").bind(id).first<DeliveryRow>();}
export async function dispatchDelivery(id:string){
  if(networkEnv().ROUTEFORGE_NETWORK_ENABLED!=='true')return;
  const now=Date.now(),lease=crypto.randomUUID();
  const locked=await db().prepare("UPDATE merchant_deliveries SET dispatch_lease_until=? WHERE order_id=? AND ready=1 AND dispatch_lease_until<? AND EXISTS(SELECT 1 FROM office_orders WHERE id=merchant_deliveries.order_id AND owner_id=merchant_deliveries.merchant_id AND status IN ('queued','offered')) RETURNING order_id").bind(now+30000,id,now).first();if(!locked)return;
  try{
    const d=await delivery(id);if(!d)return;const o=JSON.parse(d.payload_json) as OfficeOrder,i=JSON.parse(d.input_json) as DeliveryInput;
    const m=await db().prepare('SELECT * FROM merchants WHERE id=?').bind(d.merchant_id).first<Merchant>();
    if(!m||m.status!=='active'){await exception(id,'Merchant approval or reinstatement required.');return;}
    const area=await db().prepare('SELECT active,version,config_json FROM service_areas WHERE id=?').bind(d.area_id).first<{active:number;version:number;config_json:string}>();
    if(!area?.active){await exception(id,'Service area is paused. Manual review required.');return;}
    const branch=await db().prepare('SELECT id FROM merchant_branches WHERE id=? AND merchant_id=? AND active=1').bind(i.branchId,d.merchant_id).first();if(!branch){await exception(id,'Pickup branch is paused. Manual review required.');return;}
    if(i.windowEnd&&i.windowEnd<now){await exception(id,'Delivery window expired. Contact the merchant.');return;}
    const pending=await db().prepare("SELECT * FROM network_offers WHERE order_id=? AND status='pending'").bind(id).first<{id:string;expires_at:number;device_id:string}>();
    if(pending&&pending.expires_at>now)return;
    if(pending){await db().prepare("UPDATE network_offers SET status='expired' WHERE id=? AND status='pending' AND expires_at<=?").bind(pending.id,now).run();await audit(d.merchant_id,'dispatch','offer.expired',pending.id);}
    if(d.attempts>=20){await exception(id,'Dispatch exhausted 20 offers. A dispatcher must retry this request.');return;}
    const rows=await db().prepare("SELECT n.*,t.driver_name,t.vehicle_label,t.latest_point_json FROM network_riders n JOIN tracking_devices t ON t.id=n.device_id AND t.owner_id=n.owner_id JOIN driver_runtime r ON r.device_id=t.id AND r.owner_id=t.owner_id WHERE n.enabled=1 AND n.area_id=? AND (n.merchant_id=? OR n.merchant_id IS NULL) AND n.capacity_grams>=? AND (?='any' OR n.vehicle_type=?) AND t.paired_at IS NOT NULL AND t.revoked_at IS NULL AND t.token_hash IS NOT NULL AND t.last_event_kind='point' AND t.latest_point_at>? AND t.last_seen_at>? AND r.on_duty=1 AND r.gps_enabled=1 AND r.heartbeat_at>? AND COALESCE((SELECT json_extract(profile_json,'$.onDuty') FROM office_driver_profiles WHERE device_id=t.id),1)=1 AND NOT EXISTS(SELECT 1 FROM driver_dispatches dd,json_each(dd.dispatch_json,'$.stops') s WHERE dd.device_id=t.id AND json_extract(s.value,'$.deliveredAt') IS NULL) AND NOT EXISTS(SELECT 1 FROM network_offers f WHERE f.order_id=? AND f.device_id=t.id AND f.status IN ('declined','expired')) AND NOT EXISTS(SELECT 1 FROM network_offers f WHERE f.device_id=t.id AND f.status='pending' AND f.expires_at>?)").bind(d.area_id,d.merchant_id,Math.ceil(i.weightKg*1000),i.vehicleType,i.vehicleType,now-90000,now-90000,now-90000,id,now).all<{device_id:string;owner_id:string;merchant_id:string|null;vehicle_type:string;latest_point_json:string}>();
    const areaConfig=JSON.parse(area.config_json) as AreaConfig;
    const candidates=rows.results.map(r=>({...r,point:JSON.parse(r.latest_point_json) as {lat:number;lng:number;accuracy:number},fleet:r.merchant_id?'owned':'shared'})).filter(r=>r.point.accuracy<=100&&distanceMeters(r.point,areaConfig)<=areaConfig.radiusKm*1000);
    const own=candidates.filter(r=>r.fleet==='owned'),shared=candidates.filter(r=>r.fleet==='shared');
    const consent=await db().prepare('SELECT version FROM merchant_pricing_acceptance WHERE merchant_id=? AND area_id=?').bind(d.merchant_id,d.area_id).first<{version:number}>();
    const allowedShared=consent?.version===d.pricing_version&&area.version===d.pricing_version;
    const pool=m.fleet_mode==='owned'?own:m.fleet_mode==='shared'?(allowedShared?shared:[]):own.length?own:m.fallback_enabled&&allowedShared?shared:[];
    pool.sort((a,b)=>distanceMeters(a.point,o.pickup)/(a.vehicle_type==='bicycle'?18:30)-distanceMeters(b.point,o.pickup)/(b.vehicle_type==='bicycle'?18:30)||a.device_id.localeCompare(b.device_id));
    const candidate=pool[0];if(!candidate){await exception(id,!allowedShared&&(m.fleet_mode==='shared'||m.fleet_mode==='hybrid'&&m.fallback_enabled)?'Accept current shared-fleet pricing before fallback.':'No eligible online rider. Retry is scheduled; manual dispatch is available.');return;}
    const expiresAt=now+30000,next={...o,status:'offered' as const,offerDeadline:expiresAt,offerStartedAt:now,offerRiders:1,version:d.version+1,updatedAt:now};
    await db().batch([
      db().prepare("INSERT INTO network_offers(id,order_id,device_id,status,fleet,expires_at,created_at) SELECT ?,?,?,'pending',?,?,? WHERE EXISTS(SELECT 1 FROM office_orders WHERE id=? AND owner_id=? AND status IN ('queued','offered') AND version=?) AND NOT EXISTS(SELECT 1 FROM network_offers WHERE order_id=? AND status='pending')").bind(lease,id,candidate.device_id,candidate.fleet,expiresAt,now,id,d.merchant_id,d.version,id),
      db().prepare("UPDATE office_orders SET status='offered',payload_json=?,version=version+1,updated_at=? WHERE id=? AND owner_id=? AND version=? AND EXISTS(SELECT 1 FROM network_offers WHERE id=? AND status='pending')").bind(JSON.stringify(next),now,id,d.merchant_id,d.version,lease),
      db().prepare("UPDATE merchant_deliveries SET attempts=attempts+1,exception=NULL,next_attempt_at=? WHERE order_id=? AND EXISTS(SELECT 1 FROM network_offers WHERE id=? AND status='pending')").bind(expiresAt,id,lease),
    ]);
    await eventForOrder(id);await audit(d.merchant_id,'dispatch','offer.created',lease);
    deferOffice(async()=>{await new Promise(r=>setTimeout(r,30020));await dispatchDelivery(id);await flushWebhooks();});
  }finally{await db().prepare('UPDATE merchant_deliveries SET dispatch_lease_until=0 WHERE order_id=? AND dispatch_lease_until=?').bind(id,now+30000).run();}
}
async function exception(id:string,message:string){const now=Date.now();await db().batch([db().prepare("UPDATE merchant_deliveries SET exception=?,next_attempt_at=? WHERE order_id=?").bind(message,now+30000,id),db().prepare("UPDATE office_orders SET status='queued',payload_json=json_set(payload_json,'$.status','queued','$.offerDeadline',NULL,'$.version',version+1,'$.updatedAt',?),version=version+1,updated_at=? WHERE id=? AND status='offered' AND NOT EXISTS(SELECT 1 FROM network_offers WHERE order_id=? AND status='pending' AND expires_at>?)").bind(now,now,id,id,now)]);await eventForOrder(id);}
export async function claimNetworkOffer(owner:string,deviceId:string,orderId:string){
  const d=await delivery(orderId);if(!d)throw new TrackingError(404,'Delivery offer not found.');const o=JSON.parse(d.payload_json) as OfficeOrder;
  if(o.deviceId===deviceId&&d.rider_owner===owner&&o.status!=='cancelled'&&o.status!=='queued'&&o.status!=='offered')return o;
  networkEnabled();
  const offer=await db().prepare("SELECT id,fleet FROM network_offers WHERE order_id=? AND device_id=? AND status='pending' AND expires_at>?").bind(orderId,deviceId,Date.now()).first<{id:string;fleet:string}>();if(!offer)throw new TrackingError(409,'This offer expired or belongs to another rider.');
  const now=Date.now(),id=crypto.randomUUID(),t=await db().prepare('SELECT driver_name,vehicle_label,latest_point_json FROM tracking_devices WHERE id=? AND owner_id=? AND revoked_at IS NULL').bind(deviceId,owner).first<{driver_name:string;vehicle_label:string;latest_point_json:string|null}>();if(!t)throw new TrackingError(404,'Rider not found.');
  const area=await db().prepare('SELECT config_json FROM service_areas WHERE id=? AND active=1').bind(d.area_id).first<{config_json:string}>(),point=t.latest_point_json?JSON.parse(t.latest_point_json):null,config=area?JSON.parse(area.config_json) as AreaConfig:null;
  if(!point||!config||distanceMeters(point,config)>config.radiusKm*1000)throw new TrackingError(409,'Rider is outside the delivery service area.');
  const dispatch:Dispatch={id,deviceId,orderId,name:o.title,vehicleId:deviceId,vehicleName:t.vehicle_label,radius:100,assignedAt:now,updatedAt:now,revision:1,checkedAt:0,stops:[{...o.pickup,id:'pickup-'+orderId,name:'Collect · '+o.pickup.name,arrivedAt:null,deliveredAt:null},{...o.destination,id:'delivery-'+orderId,name:'Deliver · '+o.destination.name,arrivedAt:null,deliveredAt:null}]};
  const profile=await db().prepare('SELECT profile_json FROM office_driver_profiles WHERE device_id=? AND owner_id=?').bind(deviceId,owner).first<{profile_json:string}>();
  const rate=profile?JSON.parse(profile.profile_json).ratePerKm:null;
  const next={...o,ratePerKm:offer.fleet==='owned'?rate??null:null,status:'assigned',deviceId,dispatchId:id,driverName:t.driver_name,vehicleLabel:t.vehicle_label,assignedAt:now,updatedAt:now,version:d.version+1,offerDeadline:null};
  const gate="EXISTS(SELECT 1 FROM network_offers f JOIN merchant_deliveries m ON m.order_id=f.order_id JOIN merchants b ON b.id=m.merchant_id JOIN service_areas a ON a.id=m.area_id JOIN office_orders o ON o.id=m.order_id AND o.owner_id=m.merchant_id JOIN network_riders n ON n.device_id=f.device_id JOIN tracking_devices t ON t.id=n.device_id AND t.owner_id=n.owner_id JOIN driver_runtime r ON r.device_id=t.id WHERE f.id=? AND f.status='pending' AND f.expires_at>CAST((julianday('now')-2440587.5)*86400000 AS INTEGER) AND o.status='offered' AND o.version=? AND m.ready=1 AND b.status='active' AND a.active=1 AND n.enabled=1 AND n.capacity_grams>=json_extract(m.input_json,'$.weightKg')*1000 AND (json_extract(m.input_json,'$.vehicleType')='any' OR n.vehicle_type=json_extract(m.input_json,'$.vehicleType')) AND (json_extract(m.input_json,'$.windowEnd') IS NULL OR json_extract(m.input_json,'$.windowEnd')>CAST((julianday('now')-2440587.5)*86400000 AS INTEGER)) AND EXISTS(SELECT 1 FROM merchant_branches WHERE id=m.branch_id AND merchant_id=m.merchant_id AND active=1) AND n.owner_id=? AND n.area_id=m.area_id AND (n.merchant_id=b.id AND b.fleet_mode IN ('owned','hybrid') OR n.merchant_id IS NULL AND (b.fleet_mode='shared' OR b.fleet_mode='hybrid' AND b.fallback_enabled=1) AND EXISTS(SELECT 1 FROM merchant_pricing_acceptance c WHERE c.merchant_id=b.id AND c.area_id=m.area_id AND c.version=m.pricing_version) AND a.version=m.pricing_version) AND t.revoked_at IS NULL AND t.paired_at IS NOT NULL AND t.token_hash IS NOT NULL AND json_extract(t.latest_point_json,'$.accuracy')<=100 AND t.last_event_kind='point' AND t.latest_point_at>? AND t.last_seen_at>? AND r.on_duty=1 AND r.gps_enabled=1 AND r.heartbeat_at>? AND COALESCE((SELECT json_extract(profile_json,'$.onDuty') FROM office_driver_profiles WHERE device_id=t.id),1)=1 AND t.latest_point_json=? AND a.config_json=?)";
  const binds=[offer.id,d.version,owner,now-90000,now-90000,now-90000,t.latest_point_json,area!.config_json];
  const result=await db().batch([
    db().prepare("DELETE FROM driver_dispatches WHERE device_id=? AND owner_id=? AND NOT EXISTS(SELECT 1 FROM json_each(dispatch_json,'$.stops') WHERE json_extract(value,'$.deliveredAt') IS NULL) AND "+gate).bind(deviceId,owner,...binds),
    db().prepare("INSERT INTO driver_dispatches(device_id,owner_id,dispatch_json,revision,updated_at) SELECT ?,?,?,1,? WHERE "+gate+" ON CONFLICT(device_id) DO NOTHING RETURNING device_id").bind(deviceId,owner,JSON.stringify(dispatch),now,...binds),
    db().prepare("UPDATE office_orders SET device_id=?,dispatch_id=?,status='assigned',payload_json=?,version=version+1,updated_at=? WHERE id=? AND owner_id=? AND version=? AND status='offered' AND EXISTS(SELECT 1 FROM driver_dispatches WHERE device_id=? AND owner_id=? AND json_extract(dispatch_json,'$.id')=?) RETURNING id").bind(deviceId,id,JSON.stringify(next),now,orderId,d.merchant_id,d.version,deviceId,owner,id),
    db().prepare("UPDATE network_offers SET status='accepted' WHERE id=? AND status='pending' AND EXISTS(SELECT 1 FROM office_orders WHERE id=? AND dispatch_id=?)").bind(offer.id,orderId,id),
    db().prepare("UPDATE merchant_deliveries SET rider_owner=?,fleet=?,exception=NULL WHERE order_id=? AND EXISTS(SELECT 1 FROM office_orders WHERE id=? AND dispatch_id=?)").bind(owner,offer.fleet,orderId,orderId,id),
  ]);if(!result[2].results.length)throw new TrackingError(409,'The rider, consent, offer or delivery changed. Refresh before accepting.');
  await eventForOrder(orderId);await audit(d.merchant_id,deviceId,'offer.accepted',offer.id);deferOffice(()=>flushWebhooks());return next;
}
export async function declineNetworkOffer(deviceId:string,orderId:string){const r=await db().prepare("UPDATE network_offers SET status='declined' WHERE order_id=? AND device_id=? AND status='pending' RETURNING id").bind(orderId,deviceId).first();if(!r)throw new TrackingError(409,'The offer is no longer pending.');await dispatchDelivery(orderId);return {ok:true};}
export async function tickNetwork(){const ids=await db().prepare("SELECT d.order_id FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id WHERE d.ready=1 AND o.status IN ('queued','offered') AND d.next_attempt_at<=? AND d.attempts<20 ORDER BY CASE WHEN json_extract(d.input_json,'$.priority')='urgent' THEN 0 ELSE 1 END,COALESCE(json_extract(d.input_json,'$.windowEnd'),9999999999999),o.updated_at LIMIT 10").bind(Date.now()).all<{order_id:string}>();for(const r of ids.results)await dispatchDelivery(r.order_id);const recovery=await db().prepare("SELECT o.id FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id LEFT JOIN network_events e ON e.order_id=o.id GROUP BY o.id HAVING o.version>COALESCE(MAX(json_extract(e.payload_json,'$.version')),0) LIMIT 20").all<{id:string}>();for(const o of recovery.results)await eventForOrder(o.id);await flushWebhooks();return {processed:ids.results.length};}
export async function networkRiderData(owner:string,deviceId:string){
  const [offers,assigned]=await Promise.all([
    db().prepare("SELECT o.payload_json,f.expires_at,f.fleet,d.fee_minor,d.input_json,m.name AS merchant_name,b.name AS branch_name FROM network_offers f JOIN office_orders o ON o.id=f.order_id JOIN merchant_deliveries d ON d.order_id=o.id AND d.merchant_id=o.owner_id JOIN merchants m ON m.id=d.merchant_id JOIN merchant_branches b ON b.id=d.branch_id AND b.merchant_id=m.id JOIN network_riders n ON n.device_id=f.device_id WHERE f.device_id=? AND n.owner_id=? AND n.enabled=1 AND m.status='active' AND f.status='pending' AND f.expires_at>? AND o.status='offered'").bind(deviceId,owner,Date.now()).all<{payload_json:string;expires_at:number;fleet:string;fee_minor:number;input_json:string;merchant_name:string;branch_name:string}>(),
    db().prepare("SELECT o.payload_json,d.input_json,d.fee_minor,d.fleet,d.proof_json,l.rider_earning_minor,m.name AS merchant_name,b.name AS branch_name FROM merchant_deliveries d JOIN office_orders o ON o.id=d.order_id AND o.owner_id=d.merchant_id JOIN merchants m ON m.id=d.merchant_id JOIN merchant_branches b ON b.id=d.branch_id AND b.merchant_id=m.id LEFT JOIN network_ledger l ON l.order_id=d.order_id WHERE o.device_id=? AND d.rider_owner=? ORDER BY o.updated_at DESC LIMIT 20").bind(deviceId,owner).all<{payload_json:string;input_json:string;fee_minor:number;fleet:string;proof_json:string|null;rider_earning_minor:number|null;merchant_name:string;branch_name:string}>(),
  ]);
  return {offers:offers.results.map(r=>{const i=JSON.parse(r.input_json);return {...JSON.parse(r.payload_json),network:true,offerDeadline:r.expires_at,fleet:r.fleet,feeMinor:r.fee_minor,merchantName:r.merchant_name,branchName:r.branch_name,priority:i.priority,windowEnd:i.windowEnd};}),orders:assigned.results.map(r=>{const order=JSON.parse(r.payload_json) as OfficeOrder;return {order,customer:['assigned','pickup_arrived','en_route','arrived'].includes(order.status)?JSON.parse(r.input_json).customer:null,merchantName:r.merchant_name,branchName:r.branch_name,feeMinor:r.fee_minor,earningsMinor:r.rider_earning_minor,fleet:r.fleet,proofRequired:true,proof:r.proof_json?JSON.parse(r.proof_json):null};})};
}
export async function flushWebhooks(){
  const now=Date.now(),rows=await db().prepare("SELECT w.*,i.webhook_url,i.secret_cipher,e.payload_json FROM webhook_outbox w JOIN merchant_integrations i ON i.id=w.integration_id JOIN network_events e ON e.id=w.event_id WHERE w.status='pending' AND w.next_attempt_at<=? AND w.lease_until<? AND i.enabled=1 AND i.webhook_url IS NOT NULL ORDER BY w.next_attempt_at LIMIT 5").bind(now,now).all<{id:string;webhook_url:string;secret_cipher:string;payload_json:string;attempts:number}>();
  for(const r of rows.results){const acquiredAt=Date.now(),leaseUntil=acquiredAt+15000;const locked=await db().prepare("UPDATE webhook_outbox SET lease_until=? WHERE id=? AND status='pending' AND lease_until<? AND attempts=? AND next_attempt_at<=? AND EXISTS(SELECT 1 FROM merchant_integrations WHERE id=webhook_outbox.integration_id AND enabled=1) RETURNING id").bind(leaseUntil,r.id,acquiredAt,r.attempts,acquiredAt).first();if(!locked)continue;let status=0;try{const url=publicWebhookUrl(r.webhook_url),timestamp=String(Math.floor(Date.now()/1000)),signature=await signBody(await decryptSecret(r.secret_cipher),timestamp+'.'+r.payload_json);const response=await fetch(url,{method:'POST',redirect:'manual',signal:AbortSignal.timeout(8000),headers:{'Content-Type':'application/json','X-RouteForge-Timestamp':timestamp,'X-RouteForge-Signature':signature,'X-RouteForge-Event-Id':JSON.parse(r.payload_json).id},body:r.payload_json});status=response.status;await response.body?.cancel();}catch{/* Retry persisted below without logging a secret or customer data. */}
    const attempt=r.attempts+1,ok=status>=200&&status<300;await db().prepare("UPDATE webhook_outbox SET status=?,attempts=?,last_status=?,next_attempt_at=?,lease_until=0 WHERE id=? AND lease_until=?").bind(ok?'delivered':attempt>=8?'failed':'pending',attempt,status||null,Date.now()+Math.min(3600000,10000*2**attempt),r.id,leaseUntil).run();
  }
}
