/* eslint-disable */
// Generated by Wrangler by running `wrangler types operations/retry-worker/worker-configuration.d.ts --config operations/retry-worker/wrangler.jsonc --env-interface RetryWorkerEnv --include-runtime false` (hash: b9d91f021c4f8b90801a4b8ea986a08b)
interface __BaseEnv_RetryWorkerEnv {
	ROUTEFORGE_URL: "https://routeforge-shadownet.sammymuya167.chatgpt.site";
	ROUTEFORGE_JOB_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_RetryWorkerEnv {}
}
interface RetryWorkerEnv extends __BaseEnv_RetryWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ROUTEFORGE_URL" | "ROUTEFORGE_JOB_KEY">> {}
}
