plugins { id 'com.android.application' }
android {
 namespace 'app.shadownet.routeforge.driver'
 compileSdk 35
 buildToolsVersion '35.0.0'
 defaultConfig { applicationId 'app.shadownet.routeforge.rider'; minSdk 26; targetSdk 35; versionCode 3; versionName '1.1-rider'; testInstrumentationRunner 'app.shadownet.routeforge.driver.QueueInstrumentation' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
 lint { abortOnError true }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
