"use client";
import Link from "next/link";
import { useState,type FormEvent } from "react";
import { ArrowRight,Compass,Eye,EyeOff,LockKeyhole,ShieldCheck } from "lucide-react";
import { loginReturnPath } from "../../lib/login-path";
export default function LoginScreen({returnTo="/"}:{returnTo?:string}){
  const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error??"Could not sign in.");setPassword("");window.location.assign(loginReturnPath(returnTo));}catch(e){setError(e instanceof Error?e.message:"Check your connection and try again.");setBusy(false);}}
  return <main className="login-page"><section className="login-story"><Link href="/" className="login-brand"><Compass/>routeforge<span>.</span></Link><div><span className="tiny-label">SHADOWNET DELIVERY OPERATIONS</span><h1>Your fleet.<br/>Your office.<br/>One connection.</h1><p>Sign in to manage riders, deliveries, route planning and every customer collection.</p><div className="login-orbit" aria-hidden="true"><i/><i/><i/><b><Compass size={45}/></b></div></div><small><ShieldCheck size={15}/> Company records stay behind your office login.</small></section><section className="login-panel"><div className="login-card"><span className="login-lock"><LockKeyhole size={25}/></span><span className="tiny-label">OFFICE ACCESS</span><h2>Welcome back.</h2><p>Use your dashboard username and password.</p><form onSubmit={submit}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} required autoComplete="username" autoCapitalize="none" maxLength={32} autoFocus placeholder="Your office username"/></label><label>Password<div className="login-password"><input value={password} onChange={e=>setPassword(e.target.value)} type={show?"text":"password"} required autoComplete="current-password" maxLength={72}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<p className="office-error" role="alert">{error}</p>}<button className="tracking-primary" disabled={busy} type="submit">{busy?"Signing in…":"Open my dashboard"}<ArrowRight size={18}/></button></form><p><a href="/register">Register a business</a> · <a href="/rider">Open rider portal</a></p><p className="login-help">Rider usernames are used in the Android app. Contact your office if you need a rider password reset.</p><a className="office-inline-button" href="/downloads/routeforge-rider.apk?v=5">Download RouteForge Rider 1.3 APK ↗</a></div><small>Connected routes. Clear collections.</small></section></main>;
}
