"use client";
import { useCallback,useEffect,useRef,useState,type FormEvent } from 'react';
import Link from 'next/link';
import { Compass,Bell,Navigation,Phone,Package,CheckCheck,WifiOff } from 'lucide-react';
import type { Dispatch } from '../../lib/dispatch';
import type { OfficeOrder } from '../../lib/office';
import { moneyExact,phoneLink } from '../../lib/office';
type Session={deviceId:string;token:string;driverName:string;vehicleLabel:string};
type Command={operationId:string;action:string;error?:string;orderId?:string;dispatchId?:string;otp?:string};
type Event={eventId:string;tripId:string;kind:'start'|'stop'|'point';recordedAt:number;lat?:number;lng?:number;accuracy?:number;speed?:number;heading?:number};
type State={serverTime:number;assignment:Dispatch|null;order:(OfficeOrder&{requiresOtp?:boolean;customer?:{name:string;phone:string}})|null;offers:OfficeOrder[];recentOrders:OfficeOrder[];network:{order:OfficeOrder;feeMinor:number;earningsMinor:number|null;fleet:string;customer:{name:string;phone:string}|null;proofRequired:boolean}[];canStop:boolean};
async function call<T>(path:string,token:string|undefined,value:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(value)});const v=await r.json() as T & {error?:string};if(!r.ok){const e=new Error(v.error??'Connection failed.') as Error & {status?:number};e.status=r.status;throw e;}return v as T;}
function readQueue<T>(key:string){try{return JSON.parse(localStorage.getItem(key)??'[]') as T[];}catch{return [];}}
export default function RiderPortal(){
  const [session,setSession]=useState<Session|null>(null),[data,setData]=useState<State|null>(null),[online,setOnline]=useState(false),[gps,setGps]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(0),[eventsPending,setEventsPending]=useState(0),[now,setNow]=useState(0),[otp,setOtp]=useState(''),[failed,setFailed]=useState<Command[]>([]);
  const clockOffset=useRef(0),duty=useRef(false),gpsOn=useRef(false),watch=useRef<number|null>(null),trip=useRef(''),syncing=useRef(false),sessionRef=useRef<Session|null>(null),notifications=useRef(new Set<string>()),mounted=useRef(false),lastGps=useRef(0);
  useEffect(()=>{mounted.current=true;const restore=setTimeout(()=>{try{const s=JSON.parse(sessionStorage.getItem('routeforge-rider-session')??'null') as Session|null;if(s?.deviceId&&s.token){setSession(s);sessionRef.current=s;}}catch{}},0);return()=>{clearTimeout(restore);mounted.current=false;if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);};},[]);
  const queueKey=useCallback((kind:string)=>'routeforge-'+kind+'-'+sessionRef.current?.deviceId,[]);
  function saveEvent(e:Event){try{const key=queueKey('gps'),q=readQueue<Event>(key);if(q.length>=5000){setError('GPS queue full. Connect and sync before continuing.');return;}q.push(e);localStorage.setItem(key,JSON.stringify(q));setEventsPending(q.length);}catch{setError('This browser could not save GPS. Use the native rider app for a durable trip recorder.');}}
  const refreshAndSync=useCallback(async()=>{const s=sessionRef.current;if(!s||syncing.current)return;syncing.current=true;try{
    const commands=readQueue<Command>(queueKey('actions'));for(const c of commands.filter(c=>!c.error).slice(0,10)){try{const {error:ignored,...payload}=c;void ignored;await call('/api/driver/actions',s.token,payload);}catch(e){const failure=e as Error & {status?:number};if(failure.status&&failure.status!==401&&failure.status!==429&&failure.status<500){const q=readQueue<Command>(queueKey('actions')).map(v=>v.operationId===c.operationId?{...v,error:failure.message}:v);localStorage.setItem(queueKey('actions'),JSON.stringify(q));continue;}throw e;}const current=readQueue<Command>(queueKey('actions')).filter(v=>v.operationId!==c.operationId);localStorage.setItem(queueKey('actions'),JSON.stringify(current));setPending(current.length);}
    const points=readQueue<Event>(queueKey('gps')).slice(0,50);if(points.length){const ack=await call<{acknowledged:string[]}>('/api/tracking/ingest',s.token,{events:points}),remain=readQueue<Event>(queueKey('gps')).filter(e=>!ack.acknowledged.includes(e.eventId));localStorage.setItem(queueKey('gps'),JSON.stringify(remain));setEventsPending(remain.length);}
    const state=await call<State>('/api/driver/state',s.token,{appVersion:4,onDuty:duty.current,gpsEnabled:gpsOn.current});clockOffset.current=state.serverTime-Date.now();if(mounted.current){setData(state);setError('');setPending(readQueue<Command>(queueKey('actions')).filter(c=>!c.error).length);setEventsPending(readQueue(queueKey('gps')).length);setFailed(readQueue<Command>(queueKey('actions')).filter(c=>!!c.error));}
    for(const offer of state.offers){if(!notifications.current.has(offer.id)){notifications.current.add(offer.id);if(typeof Notification!=='undefined'&&Notification.permission==='granted')new Notification('RouteForge delivery offer',{body:offer.title,tag:offer.id});}}
  }catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Connection interrupted. Saved updates will retry.');}finally{syncing.current=false;}},[queueKey]);
  useEffect(()=>{sessionRef.current=session;if(!session)return;const initial=setTimeout(()=>void refreshAndSync(),0);const interval=setInterval(()=>void refreshAndSync(),3000),clock=setInterval(()=>setNow(Date.now()+clockOffset.current),1000),reconnect=()=>void refreshAndSync();window.addEventListener('online',reconnect);return()=>{clearTimeout(initial);clearInterval(interval);clearInterval(clock);window.removeEventListener('online',reconnect);};},[session,refreshAndSync]);
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{const previousDeviceId=localStorage.getItem('routeforge-rider-last-device')??undefined,s=await call<Session>('/api/driver/login',undefined,{username:form.get('username'),password:form.get('password'),deviceName:'RouteForge web rider',appVersion:4,...(previousDeviceId?{previousDeviceId}:{})});sessionStorage.setItem('routeforge-rider-session',JSON.stringify(s));localStorage.setItem('routeforge-rider-last-device',s.deviceId);setSession(s);sessionRef.current=s;setData(null);}catch(e){setError(e instanceof Error?e.message:'Sign in failed.');}finally{setBusy(false);}}
  async function action(value:Omit<Command,'operationId'>,queue=true){const s=sessionRef.current;if(!s)return;const c={...value,operationId:crypto.randomUUID()};if(queue){try{const key=queueKey('actions'),q=readQueue<Command>(key);q.push(c);localStorage.setItem(key,JSON.stringify(q));setPending(q.length);void refreshAndSync();}catch{setError('Could not save this action on the device.');}}else{setBusy(true);try{await call('/api/driver/actions',s.token,c);await refreshAndSync();}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}}}
  function goOnline(){if(!navigator.geolocation){setError('This browser does not support location. Use the native rider app.');return;}trip.current=crypto.randomUUID();duty.current=true;gpsOn.current=false;setOnline(true);saveEvent({eventId:crypto.randomUUID(),tripId:trip.current,kind:'start',recordedAt:Date.now()});void action({action:'start_duty'});watch.current=navigator.geolocation.watchPosition(p=>{gpsOn.current=true;setGps(true);if(Date.now()-lastGps.current<10000)return;lastGps.current=Date.now();saveEvent({eventId:crypto.randomUUID(),tripId:trip.current,kind:'point',recordedAt:p.timestamp,lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,...(p.coords.speed!==null?{speed:p.coords.speed}:{}),...(p.coords.heading!==null?{heading:p.coords.heading}:{})});void refreshAndSync();},e=>{gpsOn.current=false;setGps(false);setError('Location unavailable: '+e.message);},{enableHighAccuracy:true,maximumAge:10000,timeout:20000});}
  function pause(){if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;if(trip.current)saveEvent({eventId:crypto.randomUUID(),tripId:trip.current,kind:'stop',recordedAt:Date.now()});duty.current=false;gpsOn.current=false;setOnline(false);setGps(false);void action({action:'pause'});}
  async function signout(){if(!session)return;setBusy(true);try{if(readQueue(queueKey('actions')).length||readQueue(queueKey('gps')).length)throw new Error('Sync your saved actions and GPS before signing out.');await call('/api/driver/logout',session.token,{});if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);duty.current=false;setOnline(false);sessionStorage.removeItem('routeforge-rider-session');setSession(null);sessionRef.current=null;}catch(e){setError(e instanceof Error?e.message:'Sign out failed.');}finally{setBusy(false);}}
  const assignment=data?.assignment,active=assignment?.stops.some(s=>!s.deliveredAt),network=data?.network?.find(n=>n.order.dispatchId===assignment?.id),currentStop=assignment?.stops.find(s=>!s.deliveredAt),openOffers=online&&gps&&!active?data?.offers.filter(o=>(o.offerDeadline??0)>now)??[]:[];
  return <main className="rider-portal bwm-office"><header><Link className="login-brand" href="/"><Compass/>routeforge<span>.</span></Link><span className="network-badge">RIDER</span></header>{error&&<p className="office-error" role="alert">{error}</p>}{!session?<section className="network-card"><span className="tiny-label">YOUR DELIVERY WORKSPACE</span><h1>Ready for your next ride.</h1><p>Sign in with your office-issued rider account.</p><form className="network-form" onSubmit={e=>void login(e)}><label>Rider username<input name="username" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="tracking-primary" disabled={busy}>Sign in</button></form><a href="/downloads/routeforge-rider.apk?v=5" className="office-secondary">Download the Android rider app ↗</a></section>:<><section className="network-card"><span className="tiny-label">{session.vehicleLabel}</span><h1>{session.driverName}</h1><div className="network-toolbar"><span className={'network-badge '+(online?'active':'')}>{online?gps?'ONLINE · GPS ENABLED':'ONLINE · WAITING FOR GPS':'OFFLINE'}</span>{online?<button className="office-secondary" onClick={pause}>Pause location sharing</button>:<button className="tracking-primary" onClick={goOnline}>Go online & share location</button>}</div><p className="office-note">Location sharing is voluntary while this page is open. Android background tracking and notifications use the existing native app.</p><div className="network-toolbar"><button className="office-secondary" onClick={()=>{if(typeof Notification!=='undefined')void Notification.requestPermission();}}><Bell size={16}/> Enable offer notifications</button><button className="office-secondary" onClick={()=>void refreshAndSync()}>Sync now</button><button className="office-inline-button" disabled={busy||!!active} onClick={()=>void signout()}>Sign out</button></div>{failed.map(c=><p className="office-error" key={c.operationId}>{c.action}: {c.error} <button className="office-secondary" onClick={()=>{const q=readQueue<Command>(queueKey('actions')).filter(v=>v.operationId!==c.operationId);localStorage.setItem(queueKey('actions'),JSON.stringify(q));setFailed(q.filter(v=>!!v.error));void refreshAndSync();}}>Dismiss rejected update</button></p>)}{error&&<button className="office-secondary" onClick={()=>{pause();sessionStorage.removeItem('routeforge-rider-session');setSession(null);sessionRef.current=null;}}>Sign in again · keep saved updates</button>}{!!(pending||eventsPending)&&<p className="network-notice"><WifiOff size={16}/> {pending} saved actions · {eventsPending} saved GPS events. Updates retry when connected.</p>}</section>
    {openOffers.map(o=><article className="network-card network-offer" key={o.id}><span className="tiny-label">NEW DELIVERY · {Math.max(0,Math.ceil(((o.offerDeadline??now)-now)/1000))}s</span><h2>{o.title}</h2><p>{o.pickup.name} → {o.destination.name}</p><p>{o.pickup.address}</p><div className="network-toolbar"><button className="tracking-primary" disabled={busy} onClick={()=>void action({action:'accept',orderId:o.id},false)}>Accept delivery</button><button className="office-secondary" disabled={busy} onClick={()=>void action({action:'decline',orderId:o.id},false)}>Decline</button></div></article>)}
    {active&&assignment&&<section className="network-card"><span className="tiny-label">YOUR ACTIVE DELIVERY</span><h2>{assignment.name}</h2>{currentStop&&<><p><MapPinLabel name={currentStop.name}/></p><p>{currentStop.address}</p><a className="tracking-primary" href={`https://www.google.com/maps/dir/?api=1&destination=${currentStop.lat},${currentStop.lng}`} target="_blank" rel="noreferrer"><Navigation size={17}/> Navigate to {assignment.stops[0].deliveredAt?'customer':'pickup'}</a></>}{data?.order?.customer&&data.order.id===assignment.orderId&&phoneLink(data.order.customer.phone)&&<><p>Recipient: {data.order.customer.name}</p><a className="office-secondary" href={phoneLink(data.order.customer.phone)!}><Phone size={16}/> Call assigned customer</a></>}{!assignment.stops[0].deliveredAt?<button className="tracking-primary" disabled={busy||pending>0} onClick={()=>void action({action:'collected',orderId:assignment.orderId,dispatchId:assignment.id})}><Package size={17}/> Confirm collection</button>:<form className="network-form" onSubmit={e=>{e.preventDefault();void action({action:'delivered',orderId:assignment.orderId,dispatchId:assignment.id,...(network?{otp}:{})});setOtp('');}}>{network&&<label>Customer delivery OTP<input value={otp} onChange={e=>setOtp(e.target.value)} pattern="[0-9]{6}" minLength={6} maxLength={6} inputMode="numeric" required autoComplete="one-time-code" placeholder="6-digit OTP"/></label>}<button className="tracking-primary" disabled={busy||pending>0}><CheckCheck size={17}/> Confirm delivery</button></form>}</section>}
    {!active&&!openOffers.length&&<section className="network-card network-empty"><Package size={34}/><h2>{online?'Waiting for your next offer.':'Go online when you are ready.'}</h2><p>Only suitable delivery offers are sent to your account.</p></section>}
    <section className="network-card"><h2>Completed deliveries & fee history</h2>{data?.network?.filter(n=>n.order.status==='delivered').map(n=><p key={n.order.id}>{n.order.title} · {n.earningsMinor==null?'Earnings agreement not configured':moneyExact(n.earningsMinor)+' provisional earnings'} · {n.fleet} fleet<br/><small>Settlement and payouts remain disabled.</small></p>)}{data?.recentOrders?.filter(o=>o.status==='delivered'&&!data.network.some(n=>n.order.id===o.id)).map(o=><p key={o.id}>{o.title} · Completed {o.deliveredAt?new Date(o.deliveredAt).toLocaleString():''}</p>)}</section>
  </>}</main>;
}
function MapPinLabel({name}:{name:string}){return <strong>{name}</strong>;}
